### PR TITLE
Canonical bbolt

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR is related to - but does **not** fix - #4380 and #4835

This changes the import path of the `bbolt` library used by Grove to provide its cache from `github.com/coreos/bbolt` to `go.etcd.io/bbolt`, as that is the canonical import path as per [go.etcd.io/bbolt#224](https://github.com/etcd-io/bbolt/issues/224). That makes switching to a Go-module based dependency system impossible. So this is necessary to move to that.

## Which Traffic Control components are affected by this PR?
- Grove

## What is the best way to verify this PR?
Run all the tests, make sure Grove builds.

## The following criteria are ALL met by this PR
- [x] Tests are unnecessary
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by rob05c** [comment]
retest this please

**Comment by rob05c** [comment]
Retest this please.

**Comment by zrhoffman** [comment]
Weasel fails on this PR, it should have been rebased onto master so the checks could run.

**Comment by rob05c** [comment]
Yeah, I see. I'm fixing it

**Pull request merged**
