### PR TITLE
Add TM GC CPU fraction to stat endpoint

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Adds TM GC CPU fraction to stat endpoint, for debugging and profiling.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Run Monitor, verify `/publish/Stats` endpoint has `gc-cpu-fraction` key.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2752/
Test PASSed.

**Comment by rob05c** [comment]
I'm not sure what a test for this would even look like? It's adding a single field to a struct. What is there to test?

I guess we could test that the variable assignment works? But it seems like we can trust the language at least that far.

At the high level, an Integration Test for the `/publish/Stats` endpoint would be good. But the Monitor doesn't currently have an Integration Test Framework, it'd take weeks if not months to write one. Are we going to require that, for this tiny PR just to add one debug stat to the endpoint? I agree, that'd be great to have. But it seems like a lot, to require months of work, for a single field PR?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2798/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2799/
Test FAILed.

**Pull request merged**
