### PR TITLE
Fix login issues for TP integration test

### PR DESCRIPTION
**Pull request by dpham692**
## What does this PR (Pull Request) do?

- [x] This PR  is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Portal
- CI tests

## What is the best way to verify this PR?

Go to **traffic_portal/test/integration** and run command below and make sure test pass.
`npm test -- --params.baseUrl https://localhost --capabilities.shardTestFiles true`

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [ ] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by dpham692** [comment]
I put 10 seconds because when I test on local with 1 instances and it took 6 to 8 average time to load on my machine.

**Comment by ocket8888** [comment]
It's taking 6 to 8 seconds to load the TP login page on your machine? That's a huge issue for usability

**Comment by dpham692** [comment]
@ocket8888 I don't think it take that long to load TP login page but I check the reports folder and it took around 6 to 8 seconds to perform a login function.

**Comment by ocket8888** [comment]
Oh, I see. I misunderstood. I thought you were saying it was taking that long in general.

**Comment by dpham692** [comment]
Yeah, I'm sorry. I did not word it correctly. The total time it take for my computer to run the login test is about 6 to 8 seconds. It will run faster on Github Actions for sure.

**Review by ocket8888 — APPROVED** [review]

**Pull request merged**
