### PR TITLE
Fix TV Postgres reencrypt tool

### PR DESCRIPTION
**Pull request by rawlinp**
The "id" column of the "sslkey" table was removed, but the queries in
the reencrypt tool were not updated. Change the queries to select and
update by the "deliveryservice" (XML ID) column instead.

Also, fix some error logging where the error was not being appended to
the message.

Closes: #6061

## Which Traffic Control components are affected by this PR?
- Traffic Vault

## What is the best way to verify this PR?
Run the added test (note: this will also be run by the TODB GHA workflow now):
```
./pkg traffic_ops_build # and copy the resulting rpm to traffic_ops/app/db/trafficvault/test/traffic_ops.rpm
cd traffic_ops/app/db/trafficvault/test
docker-compose build
docker-compose up --exit-code-from trafficvault-db-admin
```

## If this is a bug fix, what versions of Traffic Control are affected?
- master

## The following criteria are ALL met by this PR
- [x] This PR includes tests
- [x] Bugfix, no docs necessary
- [x] Unreleased, no changelog necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
`WIP` label removed, ready for review.

**Review by ocket8888 — APPROVED** [review]
Testing looks good, and I can confirm they pass

**Comment by rawlinp** [comment]
Rebased due to conflict https://github.com/apache/trafficcontrol/pull/6065/files#diff-1eee1a599706fea7cd67d1d9413a0bcc8d1a11dade2f0adb9178460aba851177R55-R56 (just updated those lines to add the `--diff-filter=d` option.

**Review by mattjackson220 — APPROVED** [review]
code looks good, reencrypt works again, tests look good and pass!

**Pull request merged**
