### PR TITLE
secondary IPs support: add interface and ip

### PR DESCRIPTION
**Pull request by jifyang**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1605/
Test PASSed.

**Comment by jifyang** [comment]
fixes #2293

**Comment by mhoppa** [comment]
@jifyang The placement of the api handlers should be moved to be under https://github.com/apache/trafficcontrol/tree/master/traffic_ops/traffic_ops_golang

**Comment by mitchell852** [comment]
I'm closing this old PR as it has no activity and is probably accomplished by this anyhow: https://github.com/apache/trafficcontrol/blob/master/blueprints/multi-interface-servers.md

**Pull request closed without merging**
