### PR TITLE
Fix DS SSL keys not updating when updating CDN

### LINKED ISSUE #1847: Missing sync between Riak and Traffic-Ops on DS CDN change
Version: On TC 2.1 
I created an https delivery service in cdn "x".
It was then moved to cdn "y".
However, even when creating new ssl keys for the DS, the keys did not appear in 
https://ops.ocn-tc3.tc-dev.cqloud.com/api/1.2/cdns/name/y/sslkeys.json
Looking into the riak, I see that the keys are related to CDN "x".

As a workaround we can block the option to change DS cdn

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR fixes #1847

## Which Traffic Control components are affected by this PR?

- Traffic Control Client (Go) 
- Traffic Ops

## What is the best way to verify this PR?
Given two CDNs `x1` and `x2`:
-  Create a DS `y` on CDN `x1`
-  Generate SSL keys for `y`
-  Update `y` to be on CDN `x2`
-  Verify SSL keys are now on `x2` and **not** `x1`

Run the api tests and verify that they pass. **Note:** the ssl keys test are marked as a system test as they need riak to work.

## If this is a bug fix, what versions of Traffic Control are affected?

master (55b3b03)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by mitchell852** [comment]
@shamrickus - is this related or a fix to #1847

**Comment by shamrickus** [comment]
Yes

**Comment by mitchell852** [comment]
@shamrickus - can you fix the conflict?

**Comment by shamrickus** [comment]
Done

**Comment by mitchell852** [comment]
> Run the api tests and verify that they pass

Not sure you have to mention that anymore due to our nifty GHA that runs the API tests :)

**Review by mitchell852 — APPROVED** [review]
LGTM. works as expected.

**Pull request merged**
