### PR TITLE
Fixed cachegroup deliveryservice ISE

### LINKED ISSUE #2932: /api/1.x/cachegroups/{{ID}}/deliveryservices endpoint should have a more informative error message
trying to assign a cachegroup with no cache servers to a deliveryservice via the `/api/1.x/cachegroups/{{ID}}/deliveryservices` endpoint returns a 500 response with the body:
```json
{
  "alerts": [
    {
      "text": "Internal Server Error",
      "level": "error"
    }
  ]
}
```
In the debug logs it explains that this is because there aren't any cache servers in the group, so it can't deliver content. However, "Internal Server Error" doesn't really tell you what went wrong.

### PR DESCRIPTION
**Pull request by moltzaum**
## What does this PR (Pull Request) do?

- [x] This PR fixes #2932

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Create a cachegroup with no severs.

Perform the following command:
`curl -XPOST --cookie $mc -Lvsk https://localhost:6443/api/1.4/cachegroups/473/deliveryservices -d @cachegroup_deliveryservice.json | jq .`

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
    - I don't think I could test anything useful.
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
    - No new significant updates.
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
    - No new significant updates.
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3658/
Test FAILed.

**Comment by mitchell852** [comment]
you could write a test that tries to

`POST api/1.4/cachegroups/473/deliveryservices` where 473 has zero caches and ensure that a 400 comes back...

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3668/
Test PASSed.

**Pull request merged**
