### PR TITLE
CDN-in-a-box trafficrouter uses openjdk

### PR DESCRIPTION
**Pull request by dangogh**
#### What does this PR do?

replaces oracle jdk with openjdk in cdn-in-a-box

Fixes #(issue_number)

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other cdn-in-a-box

#### What is the best way to verify this PR?

```
cd infrastructure/cdn-in-a-box
docker-compose up -d
```

Run tests on trafficrouter container (help needed here)

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2610/
Test PASSed.

**Comment by JBevillC** [comment]
Since we are now running with openjdk instead of oracle java, we should

1) Install the traffic router via yum/rpm instead of unpacking it with rpm2cpio.  I used the rpm2cpio method at the time due to issues in the RPMs that no longer exist.
2) We don't need to build the tomcat-native manually at this point and can just install tomcat-native via yum/rpm

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2743/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2748/
Test PASSed.

**Comment by mitchell852** [comment]
merging based on @ocket8888 validation

**Pull request merged**
