### PR TITLE
Adding edge

### PR DESCRIPTION
**Pull request by ocket8888**
Adding an edge cache in the same fashion as the previously-added mid-tier cache.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
because I also added things to the docker-compose.yml at the same place.  So it doesn't know that they're both additions that need to be kept. If it did,  it's not smart enough to know what order they should be in.   Please rebase on master -- otherwise, you're going to have to resolve a lot of conflicts.

**Comment by ocket8888** [comment]
I rebased on master and force-pushed twice, but it's still giving me this merge conflict.

**Comment by ocket8888** [comment]
Oh, that's weird. I just did another rebase and found more conflicts than last time.

**Pull request merged**
