### PR TITLE
Fix Docker compose build Grafana CDN in a Box

### PR DESCRIPTION
**Pull request by ntheanh201**
Fix error while building Grafana in CDN in a Box

```
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.130.132 80]
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

<hr/>

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

Build CDN in a Box with Docker-compose with Grafana

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by ntheanh201** [comment]
Error

**Review by zrhoffman — CHANGES_REQUESTED** [review]
Does changing the base image to grafana/grafana:10.1.5-ubuntu work? We should avoid using an unsupported Debian version if we can.

**Comment by ntheanh201** [comment]
> Does changing the base image to grafana/grafana:10.1.5-ubuntu work? We should avoid using an unsupported Debian version if we can.

Yes it worked. I updated the base image

**Review by zrhoffman — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
