### PR TITLE
Change Monitor to third-party JSON, for performance

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Change Monitor to third-party JSON, for performance

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Run the monitor, verify it generally works. This is an internal change, the interface does not change.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2749/
Test FAILed.

**Comment by ezelkow1** [comment]
Just adding that I had tested json-iterator fastest mode briefly (not to this extent) and saw no issues with using that mode and it had a good reduction as far as memory and cpu usage percent by the json calls

Talking with Rob and from the documentation we might want to be careful though with un/marshalling anything that may have floats due to the loss of precision, though I dont think it currently affects anything we use. However in the future if we do we may need to fine tune the json-iterator mode for that specific use case

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2791/
Test FAILed.

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2808/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2814/
Test FAILed.

**Pull request merged**
