### PR TITLE
Traffic Monitor fix unnecessary structs

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Fixes the Monitor using unnecessarily large structs, which cause unnecessary CPU from Garbage Collection.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Run monitor, verify it generally works. This is an internal change, the interface does not change.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2750/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2751/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2754/
Test FAILed.

**Comment by rob05c** [comment]
Can you explain what you're hoping to see tested? I'm having a hard time coming up with a useful test. This just changes a large struct with unnecessary fields, to a struct with only the necessary fields. I'm not sure what there is to test there?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2800/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2802/
Test FAILed.

**Comment by dneuman64** [comment]
Thanks for writing tests, @rob05c!  I know it can sometimes be inconvenient to do so, but I think it makes our product better and easier to support, especially for future developers.

**Pull request merged**
