### PR TITLE
Use prebuilt images to build Traffic Control components

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR:
    - Adds docker tags for prebuilt builder images to the build docker-compose.yml
    - is not related to any issue
    
Right now, building the RPMs requires first building the builder images, which takes 8.67 minutes on my Linux machine but almost certainly longer on MacOS. Since the builder images are mainly just yum installs, we can use prebuilt Docker images without losing flexibility in terms of the code in each component.

Besides time saved, the other benefit of using prebuilt builder images is that it improves CI reliability in that CI pipelines would no longer fail in cases where installing yum packages fails.

I left commented-out `build` fields in the docker-compose.yml for cases where someone wants to test a new builder image (e.g., new Go version).

## Which Traffic Control components are affected by this PR?

- Build system

## What is the best way to verify this PR?

Run `./pkg -v` to verify that all of the components still build.

## The following criteria are ALL met by this PR

- [x] Docker environment update, no tests necessary
- [x] Builders are not mentioned in the documentation, no docs change necessary
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
So, I'm kinda torn here, because I think this would be good, but it worries me that we don't really have an official supported process/automation for updating the builder images in the docker hub. Ideally, we would have a jenkins job in place that rebuilds and updates the builder images every time a commit is merged to master. Maybe we would also need images per official release (e.g. 4.0.x, 4.1.x, etc).

**Comment by zrhoffman** [comment]
> Ideally, we would have a jenkins job in place that rebuilds and updates the builder images every time a commit is merged to master.

Docker Hub does this by default (and I just re-enabled it). Note that the build statuses are viewable under the :heavy_check_mark: or :x: [in the list of commits](https://github.com/zrhoffman/trafficcontrol/commits/master).

You can also make it build for Git refs that match a certain regex.

As you say, triggering webhooks with Jenkins would work, too.

**Comment by zrhoffman** [comment]
Added build tag regexes. Now, in addition to the `latest` tag being updated the `master` branch is updated, the following tags are built when a new release tag is pushed to the repo (e.g., `RELEASE-4.0.0`): `RELEASE-4.0.0`, `RELEASE-4.0`, `RELEASE-4`, `4.0.0`, `4.0`, `4`, and `stable`.

The following docker image tags are built when a new release candidate tag is pushed to the repo (e.g., `RELEASE-4.0.0-RC4`): `RELEASE-4.0.0-RC4`, `RELEASE-4.0-RC4`, `RELEASE-4-RC4`, `RELEASE-4.0.0-RC`, `RELEASE-4.0-RC`, `RELEASE-4-RC`, `4.0.0-RC4`, `4.0-RC4`, `4-RC4`, `4.0.0-RC`, `4.0-RC`, `4-RC`, `RC`

**Comment by zrhoffman** [comment]
Also, Docker Hub tags for every update to a release branch (e.g., `4.0.x`).

**Comment by zrhoffman** [comment]
Okay, the Docker Hub repositories should be little more usable now.

For the tags listed above, Docker Hub has images for releases from `RELEASE-2.0.0` through `RELEASE-4.1.0-RC0` (built locally and pushed after waiting the full 1 week timeout for Docker Hub's queue of images to build. It probably didn't finish because that was 7749 separate builds).

Removed release candidate tags that are not well-defined at all times (examples for RC tag `RELEASE-4.0.0-RC2`: `RELEASE-4.0-RC2`, `RELEASE-4-RC2`, `RELEASE-RC2`, `4.0-RC2`, `4-RC2`, `RC2`).

Also generated a list of tags for each repo that link to the Dockerfiles. The top of `trafficcontrol/traffic_monitor_builder`'s readme, for example:

> ## Supported tags and respective `Dockerfile` links
> * [master](https://github.com/apache/trafficcontrol/blob/master/infrastructure/docker/build/Dockerfile-traffic_monitor)
> * [RELEASE-4.1.0-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4.1.0-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4.1-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4.1-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.1.0-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.1.0-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.1-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.1-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4-RC0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4-RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RC](https://github.com/apache/trafficcontrol/blob/RELEASE-4.1.0-RC0/infrastructure/docker/build/Dockerfile-traffic_monitor)
> * [RELEASE-4.0.0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4.0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-4](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.0.0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4.0](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [4](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [latest](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0/infrastructure/docker/build/Dockerfile-traffic_monitor)
> * [RELEASE-3.1.0](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-3.1](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE-3](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [RELEASE](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [3.1.0](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [3.1](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor), [3](https://github.com/apache/trafficcontrol/blob/RELEASE-3.1.0/infrastructure/docker/build/Dockerfile-traffic_monitor)

Updating the tags in the READMEs is something that Docker Hub doesn't do itself, so maybe we could write a Jenkins job to update them.

Repos:

* https://hub.docker.com/r/trafficcontrol/docs_builder
* https://hub.docker.com/r/trafficcontrol/grove_builder
* https://hub.docker.com/r/trafficcontrol/grovetccfg_builder
* https://hub.docker.com/r/trafficcontrol/source_tarballer
* https://hub.docker.com/r/trafficcontrol/traffic_monitor_builder
* https://hub.docker.com/r/trafficcontrol/traffic_ops_builder
* https://hub.docker.com/r/trafficcontrol/traffic_portal_builder
* https://hub.docker.com/r/trafficcontrol/traffic_router_builder
* https://hub.docker.com/r/trafficcontrol/traffic_stats_builder

**Comment by ocket8888** [comment]
This needs a rebase. My local git is having issues with `docker-compose.yml`, even though GitHub itself only has a problem with `CHANGELOG.md`.

**Comment by zrhoffman** [comment]
Okay, rebased. Now there's no conflicts in any of the git history and the merge commit is gone.

**Pull request merged**
