### PR TITLE
Removed deprecated UI dependencies

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
Removes web dependencies used by the now-deprecated Traffic Ops UI. This will cause links on TO UI pages to be broken (not that anyone should ever see it) but shouldn't affect any API code because it doesn't touch any of the Perl code responsible for serving those pages.

- [x] This PR is not related to any Issue

## Which Traffic Control components are affected by this PR?
- Traffic Ops

No documentation or tests because the change is removing undocumented resources and is only (possibly) tested by the Perl test suite which is well-known to be utterly broken.

## What is the best way to verify this PR?
Start up a test Traffic Ops instance and hit it with a test of its API routes (only the ones not yet re-written to Go are necessary).

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3571/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3572/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3573/
Test PASSed.

**Comment by mitchell852** [comment]
unit and api tests all pass. works for me.

**Pull request merged**
