### PR TITLE
Fixing the tag name for %pre - preinstall script

### LINKED ISSUE #4882: Traffic Router upgrades is not cleaning up webapps from previous installation
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
`preinstall.sh` is not getting executed during upgrades and hence `webapps` folder is not getting deleted.

## Expected / new behavior:
`webapps` directory from the existing install should get deleted during upgrades

## Minimal reproduction of the problem with instructions:
Upgrade Traffic Router RPM (`rpm -Uvh`)

### PR DESCRIPTION
**Pull request by Vijay-1**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4882

## Which Traffic Control components are affected by this PR?
- Traffic Router

This doesn't require any documentation since it fixes only the install time defect.

## What is the best way to verify this PR?
Upgrade and make sure the following is getting printed during upgrade.

```
Preparing...                          ################################# [100%]
Deleting previous version of Traffic Router webapp
```

## The following criteria are ALL met by this PR
- [x] Tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by ocket8888** [comment]
Would you mind adding a changelog entry? We're trying to do that with all bugs from now on. I think it's also preferred that all bugs have related Issues, but you don't have to do that if you don't want to.

**Comment by Vijay-1** [comment]
Addressed @ocket8888 comments on CHANGELOG.

**Comment by ocket8888** [comment]
I'll be happy to merge when conflicts are fixed

**Comment by mitchell852** [comment]
@Vijay-1 - can you fix the conflict so this can be merged?

**Comment by mitchell852** [comment]
I fixed the conflict

**Pull request merged**
