### PR TITLE
Remove unnecessary JOIN

### LINKED ISSUE #3528: Fix Traffic Ops monitoring.json missing DeliveryServices
Traffic Ops `monitoring.json` is missing DeliveryServices. This is mostly ok, because the Monitor is smart enough to copy them in from the CRConfig. But, the CRConfig doesn't have thresholds. So, Delivery Service thresholds are broken, until this is fixed.

It looks like the bug is that the endpoint is only using DS Profiles which are also a Router Profile. See https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/monitoring/monitoring.go#L350

It may be as simple as removing that line, and the join above it.

### LINKED ISSUE #5180: Global Max Mbps and Tps is not send to TM
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Monitor
-  Traffic Ops
-  Traffic Portal

## Current behavior:

When a value for Global Max Mbps or Global Max Tps is defined through TP these values is not sent to TM and can not be seen at "api/monitor-config", consequently when the amount of traffic which is being delivered for DS reaches those values extra traffic won't be redirected to HTTP or DNS bypass FQDN or IP.
## Expected behavior:

Values which are defined for Global Max Mbps or Global Max should be sent to TM. As a result when current DS traffic reaches those values TM is supposed to mark that DS unavailable and sent extra traffic to HTTP or DNS bypass FQDN or IP.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #5180 and fixes #3528.

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
Make a GET request to `/cdn/{{Some CDN}}/configs/monitoring` where `Some CDN` is the name of some CDN containing at least one Delivery Service. Notice the array of Delivery Services is not empty.

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 4.1
- 4.0
- 5.0 (RC0)

## The following criteria are ALL met by this PR
- [x] This PR includes tests
- [x] No documentation changes for bug fix
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by mitchell852** [comment]
2 birds w/ one stone. i like it!

**Comment by mitchell852** [comment]
seems like more than a `minor`

**Comment by ocket8888** [comment]
idk, things seem to have been working fine without this fix for the past year and a half, so I think it's minor. But I don't care what you do to the labels, make it whatever you want

**Comment by mitchell852** [comment]
> idk, things seem to have been working fine without this fix for the past year and a half, so I think it's minor. But I don't care what you do to the labels, make it whatever you want

well ds thresholds have been broken, right? seems more than minor for anyone wanting to use ds thresholds :)

**Review by zrhoffman — APPROVED** [review]
- Confirmed that the correct values for `TotalTpsThreshold and `TotalKbpsThreshold` show up in
    - TM's `/api/monitor-config`
    - API versions 1.1, 2.0, and 3.0 of `/cdns/{name}/configs/monitoring`

We don't lose any specificity by removing the JOIN, since a Delivery Service (optionally unless using MSO) has only 1 profile.

**Pull request merged**
