### PR TITLE
Updates for traffic_ops_ort.pl for 4.1.x for CentOS 8

### PR DESCRIPTION
**Pull request by hbeatty**
And some minor bug fixes for starting ATS

## What does this PR (Pull Request) do?

This allows trafffic_ops_ort.pl 4.1.x to run on CentOS 8 and fixes some minor bugs with starting ATS.

- [x] This PR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Ops ORT

Documentation not required because there were not functionality updates made to the script.

## What is the best way to verify this PR?

Run it on a CentOS 8 cache server

## If this is a bug fix, what versions of Traffic Control are affected?

4.1.0

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by mitchell852** [comment]
imo we just let this change go into TC 5.x rather than rolling another 4.1.x release

**Comment by hbeatty** [comment]
That's fine. I did it in case anyone else wanted it. They can still find it when it is closed and if anyone asks, maybe someone will remember it's here.

**Comment by hbeatty** [comment]
Since we are planning a 4.1.1 release, I would like to get this merged in.

**Comment by rawlinp** [comment]
This backports https://github.com/apache/trafficcontrol/pull/4928 (noting for tracking purposes).

**Review by rawlinp — APPROVED** [review]
Looks good to me

**Pull request merged**
