### PR TITLE
Fix Golang client setting of cache-control max-age

### LINKED ISSUE #3550: TC Golang client incorrectly sets cache-control max-age
https://github.com/apache/trafficcontrol/blob/master/lib/go-tc/crconfig.go#L36

It would seem that the go client sets an incorrect json key when generating data structures for calls.  the API is expecting "max-age" and not "max_age"

### PR DESCRIPTION
**Pull request by rapenchukd**
## What does this PR (Pull Request) do?

- [x] This PR fixes #3550

## Which Traffic Control components are affected by this PR?

- Traffic Control Client (Golang)

## What is the best way to verify this PR?
Import and use golang client, POST to TC API using an appropriate struct to apply a cache response header for cache-control max-age, it should now set the parameter in the header correctly. Currently no solid test harness exists for most of this functionality, a separate issue will need to be established for better testing the Golang client

## If this is a bug fix, what versions of Traffic Ops are affected?

- ALL versions including Golang client

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
ok to test

thanks for the contribution!    Can you change the title of the PR to describe the fix rather than the issue number?   That helps when we look back at the history when we are ready for a release.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3647/
Test PASSed.

**Comment by rapenchukd** [comment]
Done! Yeah I just got a little lazy and direct linked the issue instead of doing the right thing :)

**Comment by mhoppa** [comment]
we should merge this @ocket8888 . @rapenchukd can you fix the merge conflict??

**Comment by ocket8888** [comment]
no need, I got this

**Pull request merged**
