### PR TITLE
Do not run all GHA workflows twice when a new branch is created

### PR DESCRIPTION
**Pull request by zrhoffman**
This PR makes it so that GHA workflows only run when files are changed. Previously, all GHAs workflows were being run when a branch was created (`create` trigger), so if the GHA workflow was also triggered by paths under the `push` trigger, each such GHA workflow would run twice, which is unnecessary.

This PR also disables the ansible/molecule GHA workflows, since they always fail.
<hr/>

## Which Traffic Control components are affected by this PR?

- Automation 

## What is the best way to verify this PR?

Verify that all GHAs workflows in #7825 pass, unless they were failing already before this PR.

## PR submission checklist
- [ ] This PR has tests 
- [ ] This PR has documentation 
- [ ] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by ericholguin — APPROVED** [review]
LGTM

**Comment by ocket8888** [comment]
looks like Ubuntu runners no longer support Python 2. Can we just drop support for it? Please?

**Comment by zrhoffman** [comment]
> looks like Ubuntu runners no longer support Python 2. Can we just drop support for it? Please?

We could drop Python 2.7 support if we make `python36` a dependency of Traffic Ops. Otherwise, it would have to wait until we drop CentOS 7 support, whenever that is.

**Comment by zrhoffman** [comment]
> > looks like Ubuntu runners no longer support Python 2. Can we just drop support for it? Please?
> 
> We could drop Python 2.7 support if we make `python36` a dependency of Traffic Ops. Otherwise, it would have to wait until we drop CentOS 7 support, whenever that is.

We could even make the TO SPEC file only include python36 as a dependency on RHEL 7 but no RHEL version above that. So RHEL 8 would be unaffected.

**Pull request merged**
