### PR TITLE
Return error when getting fed users for non-existent fed

### LINKED ISSUE #4091: GET Requests: /federations/1231/users success when Federation doesn't exist
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Do not create Federation. 
GET Request : `https://{{TO_BASE_URL}}/api/{{api_version}}/federations/1231/users`
It will return 200 OK 
```json
{
    "response": []
}
```
## Expected / new behavior:

Should return 404 Not Found

### PR DESCRIPTION
**Pull request by mhoppa**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4091 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Run TO API tests or request users for a fed that doesnt exist. Should return 404

## If this is a bug fix, what versions of Traffic Control are affected?

master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
> _"Run TO API tests or request users for a fed that doesnt exist. Should not return 404"_

Shouldn't it though?

**Comment by mhoppa** [comment]
mistype!

**Comment by ocket8888** [comment]
Without any configured federations I still get a 200 and empty array from `/federations/1/users`

**Comment by mhoppa** [comment]
huh can you please check you are using the new code??? 

Screen Shot 2019-12-04 at 11 34 10 AM

**Comment by ocket8888** [comment]
Turns out I'm on `mhoppa/bug/fix_fed_user_err` not `mhoppa/bug/fix_fed_user_error`. Very confusing.

**Pull request merged**
