### PR TITLE
Store Apache Traffic Server and grove logs in /var/log/trafficserver

### PR DESCRIPTION
**Pull request by zrhoffman**
This PR changes configuration to log Apache Traffic Server and Grove to `/var/log/trafficserver` instead of `/opt/trafficserver/var/log/trafficserver` so that the logs are on a different partition than the application itself.
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Control Cache Config (`t3c`, formerly ORT) - tests
- Apache Traffic Server
- Grove
- Transitive Source Build targeting ATS
- Automation - Ansible roles configuration for grove log directory 

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by ntheanh201** [comment]
Should we also upgrade ATS's version? https://github.com/apache/trafficcontrol/pull/7958

**Comment by zrhoffman** [comment]
> Should we also upgrade ATS's version? #7958

Definitely. I think the only reason that #7958 is not approved already is the `realpath` on macOS issue that the reviewer encounted. Hopefully #7981 will unblock that.

**Comment by ntheanh201** [comment]
I cannot test DS with your new ATS Edge, when I try to start ATS service, it shows that you still have to change to `/var/log/trafficserver` with `traffic.out`
image

**Comment by zrhoffman** [comment]
> I cannot test DS with your new ATS Edge, when I try to start ATS service, it shows that you still have to change to `/var/log/trafficserver` with `traffic.out`
> 
> P/s: I created a PR to your repo to fix this issue, can you take a look? @zrhoffman image

Thanks @ntheanh201! zrhoffman/trafficcontrol#122 is merged.

**Comment by ntheanh201** [comment]
Is there anything else in this PR that you need to check? the CI failed? @zrhoffman

**Comment by zrhoffman** [comment]
> Is there anything else in this PR that you need to check? the CI failed? @zrhoffman

If CI passes and the logs show up in `/var/log/trafficserver`, then it should be safe to merge :)

**Comment by ntheanh201** [comment]
> > Is there anything else in this PR that you need to check? the CI failed? @zrhoffman
> 
> 
> 
> If CI passes and the logs show up in `/var/log/trafficserver`, then it should be safe to merge :)

Looks like it's safe now 😁

**Comment by ntheanh201** [comment]
anything to check? @zrhoffman

**Comment by zrhoffman** [comment]
That covers it, thanks @ntheanh201!

**Pull request merged**
