### PR TITLE
Integrate t3c apps

### PR DESCRIPTION
**Pull request by rob05c**
Integrates t3c apps for the ORT Rewrite Blueprint, see blueprint for details.

Includes tests, existing unit and integration tests test behavior is unchanged.
Includes docs, each app is documented in multiple places.
Includes changelog.

- [x] This PR is not related to any other Issue

## Which Traffic Control components are affected by this PR?
- Traffic Ops ORT

## What is the best way to verify this PR?
Run unit tests. Run integration tests. Run `t3c apply`, verify everything generates and applies correctly.

## If this is a bug fix, what versions of Traffic Control are affected?
Not a bug fix.

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by jrushford — COMMENTED** [review]
Fix the Usage() function in t3c-apply/config.go.  Should print "Usage: t3c-apply" vs "Usage: t3c"

**Review by jrushford — COMMENTED** [review]
Should the t3c wrapper have a -h or 'help' command?

**Review by jrushford — COMMENTED** [review]
This didn't crop up with the t3c transliteration as the top level /tmp/ort directory for backups has existed.  I've noticed when running t3c apply/update that it errors out and exits because the renamed top level directory `'/tmp/trafficcontrol-cache-config` does not exist.  Perhaps instead of logging an error and exiting, the directory should be created?

**Review by jrushford — COMMENTED** [review]
I overlooked this but these apps t3c-update, t3c-request should implement the the --traffic-ops-insecure option.  I noticed this when using the staging environment for testing.

**Review by jrushford — COMMENTED** [review]
Should implement the --traffic-ops-insecure option.

**Comment by rob05c** [comment]
> This didn't crop up with the t3c transliteration as the top level /tmp/ort directory for backups has existed. I've noticed when running t3c apply/update that it errors out and exits because the renamed top level directory '/tmp/trafficcontrol-cache-config does not exist. Perhaps instead of logging an error and exiting, the directory should be created?

Done. It looks like it already was in non-report mode, but report mode didn't create, but then it tried to clean and failed.
I fixed it to not clean the tmp dir in report mode.

**Review by jrushford — APPROVED** [review]
looks good.

**Review by zrhoffman — COMMENTED** [review]
There are still some references to `traffic_ops_ort` in the repo. Opened #5837 for the 2 cases that affect behavior and #5838 for cases in the documentation only.

**Pull request merged**
