### PR TITLE
Added Layered Profile to TM

### PR DESCRIPTION
**Pull request by rimashah25**
Adding layered profile feature to traffic monitor to create monitoring.json that contains all profiles.

<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Monitor

## What is the best way to verify this PR?

Run route `cdns/test/configs/monitoring` to ensuring monitoring.json includes all profiles for a given server.

## PR submission checklist
- [x] This PR has tests 
- [ ] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
Is the plan for this to update `monitoring.json` so each server's profile name is an array of profile names instead? Will that only happen for this API in v5.0, while pre-5.0 API versions still use the single profile name?

**Comment by rimashah25** [comment]
> Is the plan for this to update `monitoring.json` so each server's profile name is an array of profile names instead? Will that only happen for this API in v5.0, while pre-5.0 API versions still use the single profile name?

Is the plan for this to update `monitoring.json` so each server's profile name is an array of profile names instead? ==> Yes.

Will that only happen for this API in v5.0, while pre-5.0 API versions still use the single profile name? Pre-5.0 API since layered profile is part of APIv4

**Comment by rawlinp** [comment]
That might be problematic because after upgrading TO and snapshotting the CDN, all old versions of TM will fail to unmarshal the new monitoring.json due to it being a breaking change. Or, if you upgrade TMs first, they'd be expecting the new format and would also fail that way.

I wonder if instead it would be possible for TO to "squash" the layered profiles into a single profile which is then used in the monitoring.json, which would allow the monitoring.json format to remain the same without any breaking changes?

For instance, if a given server had the profiles A, B, and C, TO could just squash those into something like `"profile": "A+B+C"` (in the `trafficServers` object) and have the "squashed" profile like a normal one:
```
             {
               "name": "A+B+C",
               "parameters": {
                 "health.connection.timeout": 2000,
                 "health.polling.url": "http://${hostname}/_astats?application=&inf.name=${interface_name}",
                 "health.threshold.availableBandwidthInKbps": ">1750000",
                 "health.threshold.loadavg": "60.0",
                 "health.threshold.queryTime": 1000,
                 "history.count": 30
               },
               "type": "EDGE"
             }
```
in the monitoring.json?

**Comment by rimashah25** [comment]
Closed this PR since I developed with a difference [solution](https://github.com/apache/trafficcontrol/pull/7291)

**Pull request closed without merging**
