### PR TITLE
Add TO cdn/ksk/generate endpoint

### PR DESCRIPTION
**Pull request by rob05c**
This adds an API endpoint for what is currently only in the old Perl
UI: regenerating CDN KSK DNSSEC keys.

#### What does this PR do?

This adds an API endpoint for what is currently only in the old Perl
UI: regenerating CDN KSK DNSSEC keys.

The API tests don't support Riak yet, but I manually tested, verified the CDN's keys are updated as expected, previous new key becomes the expired key, and other keys aren't changed.

Adds docs for 1.4 and new endpoint.

#### Which TC components are affected by this PR?

- [x] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Make a request to the new route, `POST /api/1.4/cdns/{name}/dnsseckeys/ksk/generate`, and verify the CDN's KSK keys are updated (which can be checked at `/api/1.2/cdns/name/{name}/dnsseckeys`).

#### Check all that apply

- [ ] This PR includes tests
- [x] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2574/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2576/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2653/
Test PASSed.

**Comment by elsloo** [comment]
Rob and I tested this together and the new code generates the keys as expected.

**Comment by ocket8888** [comment]
The documentation for this is straight-up wrong: it says it's used via a `GET` when it's actually a `POST`, labels parameters that need to be in the request body as being "query parameters", says that there are no required roles but in fact you must be "admin", and the response example isn't valid JSON

**Comment by anna-k-1** [comment]
^ fixes issue above: https://github.com/apache/trafficcontrol/pull/2971

**Pull request merged**
