### PR TITLE
Tabs now use CSS instead of JS

### PR DESCRIPTION
**Pull request by ocket8888**
#### What does this PR do?

Changes the table tabs in the Traffic Monitor web UI to use pure CSS instead of Javascript.
Just something I did in my spare time a while ago, decided to PR it in case anyone cares

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Build and run Traffic Monitor, then check that the tables display and update fine in Chrome, Firefox and Edge (tested Firefox DE 63.0b)

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2561/
Test FAILed.

**Comment by ocket8888** [comment]
I can do all of that, but I do have an objection to the Last Val and Number of Updates being at the bottom. The tables get huge and push those off the screen, but there's plenty of room for them where they are, and fixing the way the tabs look should make it clear that those aren't tabs

**Comment by rob05c** [comment]
>I do have an objection to the Last Val and Number of Updates being at the bottom
Sure. Maybe somewhere in the whitespace above the tabs? Maybe to the right of the "api" endpoint links?

**Comment by ocket8888** [comment]
How's that look?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2585/
Test PASSed.

**Pull request merged**
