### PR TITLE
CIAB: Export UDP ports for the DNS

### PR DESCRIPTION
**Pull request by bakerolls**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

By default, [Docker only exposes TCP](https://docs.docker.com/compose/reference/port/) but most DNS servers use UDP. The protocol can be specified by [appending `/protocol` to the exposed port](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports). In case TCs DNS switches to TCP in the future, both protocols are specified.

Since this is a very small change that does not modify any code or functionality, I hope it can be reviewed without being discussed on the mailing list.

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] CDN in a Box

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

Start CIAB as described in its readme, then use dig to test the DNS:

```
$ docker-compose -f docker-compose.yml -f docker-compose.expose-ports.yml up -d
$ dig @127.0.0.1 -p 3053 video.demo1.mycdn.ciab.test
```

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3350/
Test PASSed.

**Comment by dangogh** [comment]
@shihta you're a committer now.  Would you like to merge this since you've already tested it?

**Pull request merged**
