### PR TITLE
Logo recreated as vector. New versions of each added. .sketch source

### PR DESCRIPTION
**Pull request by chadgilloth**
files included

#### What does this PR do?
This replaces the old bitmap logos with freshly created vector versions. SVG, PNG and Sketch source files included. Removed old files.

Fixes #(issue_number)
No git issue to fix

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Download and view the logos. Source requires Sketch app for Mac

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ x] This PR does *NOT* fix a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2340/
Test FAILed.

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2374/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2409/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2410/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2411/
Test PASSed.

**Comment by dangogh** [comment]
Looks like `rat` is complaining about the .sketch files:
```
2 Unknown Licenses
+ perl -lne 'print if /Files with unapproved licenses:/ .. /^\*\*\*/' ratreport.txt
+ sed s:<https://builds.apache.org/job/trafficcontrol-PR-rat/ws/>::
Files with unapproved licenses:

  apache-trafficcontrol-3.0.0/misc/logos/ATC-SVG-FULL.sketch
  apache-trafficcontrol-3.0.0/misc/logos/ATC-SVG.sketch

```

That pattern needs to be added to the `.rat-excludes` file as well.

**Comment by dangogh** [comment]
I do like the way these turned out..   Nicely done!

**Comment by chadgilloth** [comment]
@dangogh Added sketch to rat-excludes

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2455/
Test FAILed.

**Pull request merged**
