### PR TITLE
Add TO Go deliveryservices/id/capacity

### LINKED ISSUE #3788: Rewrite /deliveryservices/{{id}}/capacity to Go
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/deliveryservices/{{id}}/capacity` is handled by Perl

## Expected / new behavior:
`/deliveryservices/{{id}}/capacity` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

# Anything Else
PR in progress: #2459 (waiting on #2305)

### PR DESCRIPTION
**Pull request by rob05c**
Branched from #2305 - recommend merging that first. Closes #3788

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1901/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2059/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4164/
Test PASSed.

**Comment by rob05c** [comment]
Rebased with master and #2305, includes #3927 changes.
Manually tested again, still works as expected, still matches Perl.

**Pull request merged**
