### PR TITLE
Change Traffic Ops Go CRUDer to use Generic Funcs

### PR DESCRIPTION
**Pull request by rob05c**
Uses generic functions to create, read, update, and delete.

It basically removes 2,000 lines of duplicate code, essentially half of the CRUD handlers.

```
$ git diff --shortstat f71da4c~3 f71da4c
 96 files changed, 2073 insertions(+), 4366 deletions(-)
```

The generic functions and interfaces are in `api/crud.go` here: https://github.com/apache/trafficcontrol/pull/2751/files#diff-9dac0d020889863a0647b45774af2437

### CODE REVIEW

**Comment by rob05c** [comment]
@DylanVolz Thoughts?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2334/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2335/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2336/
Test PASSed.

**Comment by rob05c** [comment]
Removed WIP - the API tests all pass now, this should be good to merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2376/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2390/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2391/
Test FAILed.

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2397/
Test FAILed.

**Comment by rob05c** [comment]
@DylanVolz The `Tx` and `Txx` thing was really just a convenience. I feel pretty strongly though, about keeping bottom-level funcs that don't need `sqlx` using standard Go, to maintain vendor-agnosticism where possible, and where it doesn't hurt and callers can easily pass `Tx.Tx`.

Would you be ok with a middle ground, if I removed the `Tx` vs `Txx` thing, but still kept low-level things using `sql.Tx` and being given `Tx.Tx`?

**Comment by DylanVolz** [comment]
Yeah that middle ground works for me it removes the complexity in the ApiInfo object.

**Comment by rob05c** [comment]
@DylanVolz Changed, removed Txx/Tx alias.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2398/
Test FAILed.

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2403/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2406/
Test PASSed.

**Pull request merged**
