### PR TITLE
Add CRConfig DS Modified fields

### PR DESCRIPTION
**Pull request by rob05c**
Adds a "modified" field to the CRConfig deliveryServices objects,
indicating the last time that DS's database table row was modified.

Adds a "anyModified" field to the CRConfig deliveryServices objects,
indicating the last time any database field used to create the JSON
object was modified, also including the server assignments (which
are in the contentServers key, not the deliveryServices key)

Adds a "version" field to the CRConfig object, indicating the API
version used to create that CRConfig.

Adds database triggers updating the deliveryservices last_modified
timestamp when a ds_regex, ds_server, or staticdnsentry is deleted.

These features are being added, with the goal of making it possible
for Traffic Router to determine if any individual DS in the CRConfig
has been modified, and only reload modified DSes, not everything.

### CODE REVIEW

**Comment by rob05c** [comment]
Tested the database migrations to succeed and roll back, tested the database triggers to properly update the modified fields when dependent table entries are deleted, tested the CRConfig timestamps with real data to update properly when any dependent field is updated.

**Comment by rob05c** [comment]
I'll also note, I strongly dislike SQL triggers; but in this case, it's the best, safest way to guarantee the fields are updated properly, and future-proof it against code in the future forgetting to do it. It will be critical that the DS timestamp is updated, once the Router is changed to reload only modified DSes via the `anyModified` fields.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1544/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1558/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1604/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1765/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1905/
Test PASSed.

**Comment by DylanVolz** [comment]
The migration needs to be renamed to a later date so that it will run.
It also appears to have syntax errors:
`Migrating database...
goose: migrating db environment 'development', current version: 20180606000000, target: 20180625000000
2018/06/25 14:11:58 FAIL 20180625000000_add_ds_updated_triggers.sql (pq: unterminated dollar-quoted string at or near "$$
begin
  update deliveryservice set last_updated=now() where id = old.deliveryservice;
"), quitting migration.
Can't run goose`

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2192/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2433/
Test PASSed.

**Comment by rob05c** [comment]
Rebased, migration renamed, builds, tests pass.

**Comment by rob05c** [comment]
#### What does this PR do?

Add CRConfig DS Modified fields

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

`GET /api/1.2/cdns/name/snapshot/new`

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2434/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2847/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2853/
Test FAILed.

**Comment by rob05c** [comment]
The Router dynamic reloading this was written to help no longer needs timestamps, so this isn't necessary.

**Pull request closed without merging**
