### PR TITLE
Immutable ds cdn master

### PR DESCRIPTION
**Pull request by nir-sopher**
CDN of a DS is Immutable.

This is actually a workaround so we need to decide if we want to pull it or not.
It comes to solve the inconsistency with the riak DB when changing the the DS CDN.

One may argue that the real solution should update the riak as well, when changing the DS  CDN.  However, as the DS domain name changes as well under such circumstances, the SSL key would not be valid, and we will just "move the bug"

Please share your thoughts
Nir

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1010/
Test PASSed.

**Comment by mitchell852** [comment]
@nir-sopher - your explanation makes sense to me but maybe this is something you want to take to the dev mailing list for more discussion?

basically, there are potentially problems (riak) when you change the CDN of a delivery service. should we:

a) prevent a cdn change on ds update or
b) fix all the things that break when a cdn change is made to a ds

**Comment by dneuman64** [comment]
If we decide to go down this route, I would like to see this PR include a change to the UIs (portal and traffic ops) so that a user cannot even edit the CDN.  This would be similar to the xml_id.

**Comment by anna-k-1** [comment]
@nir-sopher are you interested in porting this to Go?

**Comment by mitchell852** [comment]
this perl code has been deprecated so closing PR. this would need to be done in the golang now.

**Pull request closed without merging**
