### PR TITLE
Add Scope Parameter to Oauth Login

### PR DESCRIPTION
**Pull request by dsouza93**
The current implementation of the OAuth login is missing the scope query parameter. In order for Oauth to work properly we must add the scope.
https://oauth.net/2/scope/

<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?

You could stand up a TP/TO and SSO service. Try logging in with SSO. Currently SSO providers were throwing an error saying something along the lines of "scope not provided". With this addition, the error should no longer exist and the SSO provider should provide TP with a code.

## PR submission checklist
This is a small bug fix without tests
This PR should not change any functionality. The usage should be entirely the same. No documentation necessary.
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
TP test failure is related to driver version mismatch; not this PR

**Comment by dsouza93** [comment]
@ocket8888 - Is there a way to resolve this or get the tests to run again?

**Comment by ocket8888** [comment]
No, they're just gonna keep failing for no good reason

**Review by kdamichie — APPROVED** [review]
stamped approved

**Pull request merged**
