### PR TITLE
ATS TSB Dockerfile: Define RHEL_VERSION in CMD

### LINKED ISSUE #5916: Building ATS: Unable to get file status /etc/scl/conf/devtoolset-7: No such file or directory
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Server (Transitive Source Build)

## Current behavior:

ATS fails to build when using `pkg`.

## Expected behavior:

ATS should build successfully.

## Minimal reproduction of the problem with instructions:

```shell
[user@computer trafficcontrol]$ ./pkg -vo ats
Building ats.
Pulling ats ... 
Pulling ats ... done
Creating build_ats_run ... 
Creating build_ats_run ... done
Building ats_build.
Building ats_build
[...]
Creating _tsb_ats_build_run ... 
Creating _tsb_ats_build_run ... done
Unable to get file status /etc/scl/conf/devtoolset-7: No such file or directory
3
Failed to build ats_build.
Results in 'dist':
total 0
Failed to build ats.
Results in 'dist':
total 0
```

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5916

## Which Traffic Control components are affected by this PR?

-  Traffic Server (Transitive Source Build)

## What is the best way to verify this PR?

Try to build ATS:

```shell
./pkg -vo ats
```

## If this is a bug fix, what versions of Traffic Control are affected?

- master (5ad059f0af)
- 5.1.2

## The following criteria are ALL met by this PR

- [x] Build system changed only, no tests necessary
- [x] Bugfix, documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by jrushford — APPROVED** [review]
looks good

**Review by jrushford — COMMENTED** [review]
@zrhoffman in 'pkg' see lines 213-219 handling the existence of the 'list' directory.  Personally, I think the script should create that directory up front prior to the build if it does not exist.

**Comment by zrhoffman** [comment]
@jrushford  No longer symlinking the dist directory in bbf33c5f00. As with all bind mounts, the directory will be created if it does not exist.

**Comment by zrhoffman** [comment]
Rebased onto master to get 52436a75a2/ATS 8.1 in CDN in a Box so CI passes

**Review by jrushford — COMMENTED** [review]
@zrhoffman this looks ok.  It fixes the pkg build problem.  However, in the traffic_server/_tsb/src directory has an old 8.0 version of traffic_server.  We use 8.1 in production and will be deploying 9.1 soon.  I think we can improve on this PR by checking out these source directories rather than have them in the trafficcontrol source tree.  Let's say that the run.sh uses environment variables defined for each src directory, say JANSSON_URL, JANSSON_BRANCH, CJOSE_URL, CJOSE_BRANCH, OPENSSL_URL, OPENSSL_BRANCH, ATS_URL, ATS_BRANCH.  Then run.sh would use these to checkout the branch of the package from git and build using that.  Then going forward we just have to edit the docker-compose and change the BRANCH.  Just a suggestion.

**Comment by zrhoffman** [comment]
@jrushford Good ideas, but let's save them for a separate PR, since we try to limit each PR to doing 1 thing.

**Pull request merged**
