### PR TITLE
CDN in a Box: CentOS 8.3 fixes

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR is not related to any Issue 

This PR fixes problems in CDN in a Box caused by breaking changes in CentOS 8.3. The issue building the `trafficportal` CDN in a Box image has already been fixed in nodesource/distributions#1147.

Fixes the `Error: Unknown repo: 'PowerTools'` error that you will get when trying to build the `trafficops-perl` CDN in a Box image.

The `centos:8` Docker image updated to CentOS version 8.3.2011 yesterday. CentOS 8.3 changed the PowerTools repo ID [from `PowerTools`](https://git.centos.org/rpms/centos-repos/c/b759b17557#_24) [to `powertools`](https://git.centos.org/rpms/centos-repos/c/b759b17557#_22), and repo IDs are case-sensitive.

I couldn't find any mention of this in the [Red Hat 8.3 release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.3_release_notes/index), though a related [Fedora Websites documentation bug](https://bugzilla.redhat.com/show_bug.cgi?id=1900785) is still open.

If we really wanted, we could support CentOS 8 versions older than 8.3.2011 for `trafficops-perl` in CDN in a Box by doing `--enablerepo=[Pp]ower[Tt]ools`, but let's not.

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

1. Pull a newer `centos:8` image
    ```shell
    docker pull centos:8
    ```

2. Build Traffic Ops Perl
    ```shell
    docker-compose build trafficops-perl
    ```

## If this is a bug fix, what versions of Traffic Control are affected?

- master (c0126fca5d)
- 5.0.0 (RC2)

## The following criteria are ALL met by this PR

- [x] Only CDN in a Box is affected, no test beyond testing CDN in a Box is necessary
- [x] Usage of CDN in a Box is unchanged, documentation is not necessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by zrhoffman** [comment]
Removed the fix for rpm.nodesource.com, as nodesource/distributions#1147 already fixes that issue.

**Review by ocket8888 — APPROVED** [review]
This works, per CI build results

**Comment by zrhoffman** [comment]
> I'm guessing the CI caching of perl dependencies hides this error.

That sounds correct. A quick search reveals that [File::Stat](https://metacpan.org/pod/File::Stat) does not exist but [File::stat](https://metacpan.org/pod/File::stat) does. I wonder how long that's been the case.

**Comment by zrhoffman** [comment]
The `trafficops-perl` image builds successfully for me with no caching. Still looking into this...

**Comment by rawlinp** [comment]
Yeah I blew away my centos7-based `local` dir, and it built successfully.

**Pull request merged**
