### PR TITLE
Add TO Go configurable riak port

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Add TO Go configurable Riak port.

If port is not configured, a default is used, which is the same as the existing hard-coded port.

The "API Tests" don't support Riak yet, but unit tests pass, and I tested this manually, verified a configured port was used, and that TO behaved exactly as before if a port was not configured.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

With a complete TO setup, including Riak/Traffic Vault, set the key `riak_port` in `cdn.conf`, and request a Riak endpoint such as `/api/1.2/riak/ping`, and verify the configured port is used (you don't have to actually configure Riak to use that port, you should be able to check the error logs of TO and see failed attempts to get to the port you set).

Remove the `riak_port` key, and verify TO uses the default port of `8087`. With a default Riak installed and configured, this should be the default, and a request to `/api/1.2/riak/ping` should succeed.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2555/
Test FAILed.

**Comment by rawlinp** [comment]
I thought the idea was that once all the Riak stuff is handled in traffic_ops_golang, we'd just use the `server.tcp_port` column in the Go stuff and take out the hardcoded 8087. Is that not the plan anymore?

**Comment by rob05c** [comment]
Riak uses a number of ports. The port here is what's used by `traffic_ops_golang` to talk to Riak, which is the Protobuf port, which defaults to 8087. Riak also has HTTP and HTTPS APIs which default to 8098 and 8088, respectively.

Someone may want to set the TO Server "TCP Port" to a different API, HTTP or HTTPS, which will require configuring the TO app to know the Protobuf API port. We currently do this, our Riak TO port is the HTTPS API.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3135/
Test PASSed.

**Comment by mitchell852** [comment]
@rivasj is going to review this PR

**Comment by rivasj** [comment]
Verified that unit tests pass and that the riak port can be configured via cdn.conf - traffic_ops_golang.riak_port.

+1 on the PR

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3185/
Test PASSed.

**Pull request merged**
