### PR TITLE
new certificate chain analyzer test 

### PR DESCRIPTION
**Pull request by serDrem**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1880/
Test PASSed.

**Comment by serDrem** [comment]
This should be good to go, I tested this again just now.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1883/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1885/
Test PASSed.

**Comment by ocket8888** [comment]
If you still want this functionality, please address the requested changes and re-open the Pull Request

**Pull request closed without merging**
