### PR TITLE
Updated GetDeliveryServiceByXMLID function to return a DS nullable struct

### PR DESCRIPTION
**Pull request by ZugNZwang**
## What does this PR (Pull Request) do?

Replaces the struct returned by the `GetDeliveryServiceByXMLID` client function to `DeliveryServiceNullable` instead of `DeliveryService`.
- [X] This PR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Control Go Client 

## What is the best way to verify this PR?

Run the traffic ops tests
## The following criteria are ALL met by this PR

- [X] This PR includes tests OR I have explained why tests are unnecessary
- [X] This PR includes documentation OR I have explained why documentation is unnecessary
- [X] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [X] This PR includes any and all required license headers
- [X] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [X] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rob05c** [comment]
Yeah, like @ocket8888 says, this will break existing things, but it also breaks the stability of the Go library, and it will fundamentally break Go Modules if and when we switch to them (which we'll probably have to at some point).

The way we've typically done this in the past is to add a new function with a similar name, e.g. `DeliveryServiceByXMLID` or `GetDeliveryServiceByXMLIDNullable`, and add a Deprecated comment to the old one.

**Comment by ocket8888** [comment]
The [mailing list decided](https://www.mail-archive.com/search?l=dev@trafficcontrol.apache.org&q=subject:%22Re%5C%3A+Deprecation+period+for+TO+Client+Methods%5C%3F%22&o=newest&f=1) that TO client methods don't have a deprecation period - but this will need a line in CHANGELOG.md

**Comment by ZugNZwang** [comment]
> but this will need a line in CHANGELOG.md
Would this go under `Added`?

**Comment by ocket8888** [comment]
Uhh sure. If you're doing what rob said and adding a new function it goes under Added. Otherwise I would think under Changed.

**Comment by rawlinp** [comment]
Yeah, in addition to the mailing list discussion I'd also add that going the deprecation route would be great if we actually cleaned up deprecated functions, stopped increasing the usage of already-deprecated functions, etc. But historically nobody has really gone back to clean things up, and I've definitely encountered new code that used already-deprecated client methods. At least if you make a breaking change to the TO Go client you're forced to fix all the existing usages in the repo (otherwise the build fails), and we don't end up w/ 3 different client methods that all do the same thing.

**Pull request merged**
