### PR TITLE
Remove file containing only logic for APIv1

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR is not related to any Issue

This PR removes logic for handling the now-removed `/cachegroups/{{ID}}/unassigned_parameters` endpoint that was only in APIv1. CGP in general needs to stick around until we get rid of APIv3, but this is now unused.

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
Make sure all the tests still pass.

## The following criteria are ALL met by this PR
- [x] Tests are unnecessary
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by zrhoffman** [comment]
#6030 seems related enough to #6028 for them to be combined. Any reason not to combine them?

**Comment by ocket8888** [comment]
Supposedly the difference is that this is removing things from Traffic Ops while #6028 is removing things from `lib/go-tc`, but it is true that #6028 still does touch Traffic Ops to change some type names from `RiakPing` to `TrafficVaultPing`. They can probably be combined if you want - but then you need to promise to review the result!

**Comment by zrhoffman** [comment]
Deal

**Comment by ocket8888** [comment]
Closed in favor of #6028

**Pull request closed without merging**
