### PR TITLE
Use the standard Traffic Ops v1 client for atstccfg legacy toreq

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR is not related to any Issue 
- Updates the `atstccfg/toreq` package to use the standard Traffic Ops v1 client.

## Which Traffic Control components are affected by this PR?

- Traffic Ops ORT

## What is the best way to verify this PR?

- Run the `atstccfg/toreq` unit test suite, make sure it passes
- Run `atstccfg`, make sure it works

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] Behavior is unchanged, no documentation necessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
Shouldn't this be using the v2 client now? Unless we're trying to get this into 5.0.0

**Comment by rawlinp** [comment]
4.1 tries /api/2.0 then /api/1.3.

It seems like 5.0 should be trying /api/3.0 then /api/2.0, right? Unless it doesn't need 2.0 yet and is still good with 1.4?

**Comment by zrhoffman** [comment]
Discussed this with @rob05c. It sounds like he's -1 on using non-vendored TO clients for the legacy `atstccfg/toreq` package unless the client library adds the feature of being able to specify the minor version to use for requests. This is so you can upgrade from the earliest minor release of a last major release instead of needing to first upgrade to the last minor of the last major release (example: Supporting upgrading from 3.0 to 4.1, not just 3.1 to 4.1).

@rob05c does that sound right?

**Comment by rawlinp** [comment]
> unless the client library adds the feature of being able to specify the minor version to use for requests

That smells sort of like an anti-pattern, but would that even be necessary anymore per https://github.com/apache/trafficcontrol/pull/5229#issuecomment-719869508? Sounds like you already figured it out.

**Comment by zrhoffman** [comment]
> > unless the client library adds the feature of being able to specify the minor version to use for requests
> 
> That smells sort of like an anti-pattern, but would that even be necessary anymore per [#5229 (comment)](https://github.com/apache/trafficcontrol/pull/5229#issuecomment-719869508)? Sounds like you already figured it out.

Right. AFAIK, because no active PR depends on #5230, we can take our time to decide what we want to do with the vendored TO client library without holding up anything else.

**Comment by rob05c** [comment]
>Discussed this with @rob05c. It sounds like he's -1 on using non-vendored TO clients for the legacy atstccfg/toreq package unless the client library adds the feature of being able to specify the minor version to use for requests. This is so you can upgrade from the earliest minor release of a last major release instead of needing to first upgrade to the last minor of the last major release (example: Supporting upgrading from 3.0 to 4.1, not just 3.1 to 4.1).
>
>@rob05c does that sound right?

I think the right solution is to make the `v1-client` (and other TO clients) figure out the right minor version from TO to use.

As-is, changing ORT's legacy client to `v1-client` technically doesn't break upgrades, but only because TO 5.0 didn't add any minors to 1.3. But it will as soon as we do.

As soon as ORT's client is on the latest and next-latest versions, it's going to break. For example, suppose ORT had `v2-client` and `v3-client`, and Traffic Control 4.0 had `/api/2.0`, ATC 4.1 added `/api/2.1`, and ATC 5.0 adds `/api/3.0`. Then, if a user had Traffic Ops running 4.0, and used Go Modules (or otherwise updated to the latest), and updated their ORT, it's going to update `v2-client` to the latest, ATC 4.1, which will request `/api/2.1`, which doesn't exist on their TO. But Go Modules promised they could upgrade minors without breaking things, which they're supposed to be able to do safely. Except we broke them.

This isn't limited to ORT: fundamentally, if the TO `vx-client` libraries request the latest minor, and don't fall back, they're going to break Go Modules for everyone using them. So, I think making the TO clients fall back to previous minors is the right solution for Go Modules, and to generally work with older TO's anyway.

That should be safe, as long as we're only adding new symbols in new ATC minors in `lib/go-tc`, and making sure their default/zero/null values make everything behave like it did without them.

We should be able to either use `/ping` today to figure out the latest version the TO supports (I actually have a personal script to do that, because I needed it), or we could add the `/api/x/versions` endpoint @jhg03a has been asking for for years. And if `lib/go-tc` is compatible like it should be, we should be able to just change the request path and nothing else.

**Comment by zrhoffman** [comment]
Supersede by #5247

**Comment by rob05c** [comment]
Bearing in mind what I mentioned above: we can't use v2-client until it falls back to the oldest minor.

**Comment by zrhoffman** [comment]
Understood. But since [`/traffic_ops_ort/atstccfg/toreq/vendor`](/apache/trafficcontrol/commits/master/traffic_ops_ort/atstccfg/toreq/vendor) is gone, it no longer blocks #5229, the Go modules PR.

**Pull request closed without merging**
