### PR TITLE
Fixed logging.yaml generation.

### PR DESCRIPTION
**Pull request by alficles**
## What does this PR (Pull Request) do?

The logging.yaml file was generating a separate logs section for each
log file. This was allowing the yaml parser in ATS to accept the file,
but fail to process any but one of the log files. This corrects that by
putting all the logs in the same object.

- [x] This PR is not related to any existing open issue 

## Which Traffic Control components are affected by this PR?

- Traffic Ops ORT

This does not change any existing functionality, it just updates the generation to be correct and to match the existing documentation.

## What is the best way to verify this PR?
Run ORT against a Traffic Ops instance to generate a config files for a cache that has multiple logging formats configured in a logging.yaml file.

Additionally, this functionality is verified in a unit test as part of lib/go-atscfg, so those unit tests should run and pass.

## If this is a bug fix, what versions of Traffic Control are affected?
This fixes a bug that was copied from Traffic Ops in Perl. So no version of Traffic Ops has ever properly rendered this file.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] An update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
Does this change the [current declared conversion of `logging.yaml` Parameters to chunks of the `logging.yaml` file](https://traffic-control-cdn.readthedocs.io/en/latest/overview/profiles_and_parameters.html#logging-yaml)?

**Comment by alficles** [comment]
@ocket8888 Nope. It makes it match, actually. The documentation indicates, correctly, that `logs:` should be listed only once, but it was actually being generated for every chunk.

**Comment by ocket8888** [comment]
Now that's what I like to hear

**Comment by jrushford** [comment]
I built this, ran unit tests and ort against on a lab machine agains staging and the logging.yaml was built correctly.

**Pull request merged**
