### PR TITLE
Reorder SQL migrations to fix some upgrade issues

### PR DESCRIPTION
**Pull request by hbeatty**
## What does this PR (Pull Request) do?

This moves some SQL migrations past the last one in 5.0.x that were not in the 4.1.x and 5.0.x branch.

- [x] This PR  is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Do a DB upgrade from 5.0.0 to 5.1.0

## If this is a bug fix, what versions of Traffic Control are affected?

- 5.0.0
- 5.1.0

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
Ok, once this is merged it can be backported to 5.1.x, so we don't need https://github.com/apache/trafficcontrol/pull/5528.

**Comment by ocket8888** [comment]
Yeah, I can do that for you. No need of a separate PR

**Comment by hbeatty** [comment]
Just curious what the difference is?

**Comment by rawlinp** [comment]
By cherrypicking, we include the original commit hash from master by using the `-x` option. It also helps ensure that the `master` version and the `5.1.x` version are actually the same changes (in case we request changes here which would cause it to diverge from the 5.1.x PR that was opened simultaneously).

**Review by rawlinp — APPROVED** [review]
LGTM, DB upgrades from `2020110200000000_add_service_category_deleted.sql` (first migration script in 5.0) to the latest and downgrades back successfully.

**Pull request merged**
