### PR TITLE
Fix t3c report mode to be less spammy

### LINKED ISSUE #6201: t3c-apply report mode doesn't appear to work (no output)
I'm trying to reproduce the results produced by using the following command:

```
traffic_ops_ort.pl -dispersion=0 report WARN
```

I can't seem to get the diff for the configuration files. If I enable the verbose (`-vv`) mode, it seems to display the configuration, although it is highly cryptic for a human to use. 

The command used is:

```
t3c-apply -m report -o -F
```

- Traffic Control Client 

## Current behavior:
Please see summary

## Expected behavior:
Difference in configuration seen in the output

## Steps to reproduce:

Compare `t3c-apply -m report -o -F` versus `traffic_ops_ort.pl -dispersion=0 report WARN`

### PR DESCRIPTION
**Pull request by rob05c**
Fixes #6201

Also fixes some related issues around logging lines without prefixes (which break log parsers), and logging that Traffic Ops was updated when it wasn't.

## Which Traffic Control components are affected by this PR?
- Traffic Control Cache Config (T3C, formerly ORT)

## What is the best way to verify this PR?
Run t3c-apply --run-mode=report, verify diff is printed and nothing else.

## If this is a bugfix, which Traffic Control versions contained the bug?
- `master`

## PR submission checklist
- ~[x] This PR has tests~ no tests, report mode output is not defined strictly
- ~[x] This PR has documentation~ no docs, report mode output is not defined or documented strictly
- ~[x] This PR has a CHANGELOG.md entry~ no changelog, changes are not in a release
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by jrushford — COMMENTED** [review]
When testing file diffs are not shown.

**Comment by rob05c** [comment]
@jrushford This PR doesn't change the diff output. It just changes where it goes.

I can change the output, if we feel the need, for the release. @smalenfant ?

**Comment by smalenfant** [comment]
@rob05c The diff output shows in the output in `-m report`. Although they don't show up when applying in `syncds` mode. They don't get logged anywhere either (stdout, sdterr or logs).

Also, I don't think you can debug anymore by adding `-vv`.

```
[root@cdn1cdedge0002 ~]# t3c-apply -m report -vv
file '/opt/trafficserver/etc/trafficserver/records.config' changes begin
diff: -CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.5
diff: +CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.500000
diff: -CONFIG proxy.config.http.background_fill_completed_threshold FLOAT 0.0
diff: +CONFIG proxy.config.http.background_fill_completed_threshold FLOAT 0.000000
diff: -CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.10
diff: +CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.100000
diff: 
file '/opt/trafficserver/etc/trafficserver/records.config' changes end
```

**Comment by jrushford** [comment]
> @rob05c The diff output shows in the output in `-m report`. Although they don't show up when applying in `syncds` mode. They don't get logged anywhere either (stdout, sdterr or logs).
> 
> Also, I don't think you can debug anymore by adding `-vv`.
> 
> ```
> [root@cdn1cdedge0002 ~]# t3c-apply -m report -vv
> file '/opt/trafficserver/etc/trafficserver/records.config' changes begin
> diff: -CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.5
> diff: +CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.500000
> diff: -CONFIG proxy.config.http.background_fill_completed_threshold FLOAT 0.0
> diff: +CONFIG proxy.config.http.background_fill_completed_threshold FLOAT 0.000000
> diff: -CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.10
> diff: +CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.100000
> diff: 
> file '/opt/trafficserver/etc/trafficserver/records.config' changes end
> ```

@smalenfant @rob05c and @zrhoffman After building the t3c apps from this PR and installing them in /usr/bin, I ran tests on the cache-34 lab machine and began with a badass to ensure all config files were up to date.  I then introduced changes to remap.config and parent.config, 1 add to remap.config, 2 deletions from remap.config and 3 deletions from parent.config.  I ran:

`# t3c-apply -m report -vv
file '/opt/trafficserver/etc/trafficserver/remap.config' changes begin
diff:
file '/opt/trafficserver/etc/trafficserver/remap.config' changes end
file '/opt/trafficserver/etc/trafficserver/parent.config' changes begin
diff:
file '/opt/trafficserver/etc/trafficserver/parent.config' changes end`

It shows that there are differences in remap.config and parent.config but there is no actual output showing the diffs, as you can see above.

**Comment by rob05c** [comment]
@jrushford Ok, it should be fixed. It wasn't this PR, `t3c-diff` was accidentally changed to output the diff on the stderr logger instead of stdout. Most things should be logged, but an app's primary output (like t3c-diff's diff) still needs to be un-prefixed stdout. I went ahead and fixed it in this PR.

I also changed the report-mode diff to have the Info logger prefix, per @smalenfant request.

**Review by jrushford — APPROVED** [review]
looks good.  I've retested following the latest change and diff output is as it should be now.

**Pull request merged**
