### PR TITLE
CIAB: remove rpm path, load postgres from repo

### LINKED ISSUE #3492: CIAB postgresql rpm availability
in `cdn-in-a-box`,  the trafficops-perl container won't build currently because the specific rpm included in the Dockerfile has apparently been archived in favor of a newer patch level.

It shouldn't be specifying a specific file to be downloaded, but use the yum repo provided.

### PR DESCRIPTION
**Pull request by dangogh**
## What does this PR (Pull Request) do?

Fixes #3492 by providing a yum repo configuration rather than a path to a specific rpm file (the one listed there disappeared).   Also upgrades Go to same version used for builds.

No procedural change, so no tests or doc or CHANGELOG changes needed.

## Which Traffic Control components are affected by this PR?
- CDN in a Box

## What is the best way to verify this PR?

With a clean docker installation, run these commands and verify that rpm installation succeeds:
```
cd infrastructure/cdn-in-a-box
docker-compose up --build -d
docker-compose logs -f trafficops-perl
```

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3533/
Test FAILed.

**Comment by Shihta** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3536/
Test PASSed.

**Comment by Shihta** [comment]
I use the latest code (21e50eedf1b824f11869d678fd9439a3d4a73d3c) and then test this PR.
trafficops-perl shows error:
```
[2019-04-18 14:54:37,717] [ERROR] Global symbol "$ds" requires explicit package name at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 2896.
Compilation failed in require at (eval 1260) line 1.
[2019-04-18 14:54:37,719] [ERROR]
[2019-04-18 14:54:39,202] [ERROR] Global symbol "$ds" requires explicit package name at /opt/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm line 2896.
Compilation failed in require at (eval 1252) line 1.
[2019-04-18 14:54:39,215] [ERROR]
```

**Comment by rob05c** [comment]
Hm, looking at the code, that looks like a different issue, this code doesn't change Perl things.

I'm building it now, but, we should probably open a different issue for that. Unless it looks like this code is somehow breaking that?

**Comment by Shihta** [comment]
there is another commit  just be merged (56ef95e1783360b4afb600b06cf138255fb34c89)
I'm not sure if that fix this issue

**Comment by rob05c** [comment]
@Shihta It sounds like it; but I haven't tested. I'm merging this, it looks like this fixes its bug. Definitely open another case for that issue, if it's still an issue. Or if it turns out this was somehow causing that, we can revert this.

**Comment by dangogh** [comment]
@Shihta -- no..   those were 2 separate issues..   both are fixed and merged now..

**Pull request merged**
