### PR TITLE
Update flot libraries to earliest stable version

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR is not related to any Issue 

Currently TP is using a version of flot that is not stable or supported. This updates the flot libraries.
[Flot.tooltip changes](https://github.com/krzysu/flot.tooltip#v090)
[Flot changes](https://github.com/flot/flot/blob/master/CHANGELOG.md#201)

Note: flot.tooltip has been unsupported since 2016 and the repo makes no mention of what version of flot it depends on. That having been said, none of the breaking changes made in flot are applicable to the flot.tooltip repo (it's a single file).

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Ensure TP integration tests work
Verify charts (and tooltips on charts) still work.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information
With these changes, it is now possible to remove `bower` as these dependencies were the only ones not present in `npm`.

### CODE REVIEW

**Comment by zrhoffman** [comment]
> This should not be merged until 5.x is cut.

Would it make sense to make this a draft until 5.x is cut?

**Comment by shamrickus** [comment]
5.0 is cut

**Review by ocket8888 — APPROVED** [review]
TP still works and passes its tests with the new `flot`

**Comment by mitchell852** [comment]
image

**Comment by shamrickus** [comment]
Hmm, I'm seeing the same thing. I'll look into it today.

**Pull request merged**
