### PR TITLE
Removed some weird quotes (Mac?)

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
Removed some odd quote marks that don't display properly in e.g. Vim. I know Mac likes to insert two spaces after periods when you only press space once, so maybe that was a Mac thing?
- [x] This PR is not related to any Issue

## Which Traffic Control components are affected by this PR?
- Traffic Portal

## What is the best way to verify this PR?
Check out the new quotes, make sure they display properly. Change is too trivial for a CHANGELOG entry and/or tests and/or docs.

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3627/
Test PASSed.

**Comment by mitchell852** [comment]
while you're in this file can you change

`separated by __RETURN__...`

to

`separated by __RETURN__ or new line characters`

**Comment by ocket8888** [comment]
Good idea.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3639/
Test PASSed.

**Pull request merged**
