### PR TITLE
Fix t3c test duplication and upgrade to v4

### PR DESCRIPTION
**Pull request by rob05c**
Moves the TO test setup to a shared library to remove duplication in the ORT/t3c integration tests, because that was easier than upgrading t3c tests to API v4, which was necessary to test multiple profiles.

It turned out, moving the TO test data setup to a library was easier than fixing all the changes in v4. 

It's a lot of lines changes (3k duplicate lines removed), but there's no logic change in the tests, just moving and renaming things. More conveniences could be added, like moving the WithObjs helpers to the library and removing the wrappers. But it seemed better to keep this as small as possible; it's already huge.

## Which Traffic Control components are affected by this PR?
- Traffic Control Cache Config (`t3c`, formerly ORT)
- Traffic Control Client Go

## What is the best way to verify this PR?
Run tests.

## If this is a bugfix, which Traffic Control versions contained the bug?
Not a bug fix.

## PR submission checklist
- [x] This PR has tests 
- ~[x] This PR has documentation~ no docs, no interface change 
- ~[x] This PR has a CHANGELOG.md entry~ no changelog, no user interface change 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by rob05c** [comment]
It'd be really good to do this to v5 as well, so the t3c Integration Tests can easily share that too, when it comes time to upgrade them.
But that can be done separately.

**Comment by traeak** [comment]
Testing:
Check out rob's branch, create t3c pre PR and t3c post PR.
Run against same host and compare files.

Sample commands and then compare:
```for hdr_rw in hdr_rw* ; do echo $hdr_rw ; grep -v '^#' ${hdr_rw} | md5sum ; done > ~/hdr_rw_sums.txt; md5sum ~/hdr_rw_sums.txt```
```grep -v '^#' parent.config  | md5sum```
```grep -v '^#' records.config  | md5sum```

**Review by traeak — APPROVED** [review]
Generated files with previous git has and with this git has and compared for multiple configurations and tiers in our prod.  File contents were the same.

**Comment by ericholguin** [comment]
This was included in #7287

**Pull request closed without merging**
