### PR TITLE
Specify nodejs version in TP spec

### LINKED ISSUE #5438: TP rpmspec does not specify nodejs version
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:
Any version of nodejs is accepted as a dependency to TP

## Expected behavior:
The nodejs version should either be pinned or restricted to prevent major updates to nodejs which might break TP. Currently the documentation says nodejs 12 or above is required.

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5438

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Build the TP RPM and verify that it depends on Nodejs 12 instead of any nodejs version.

## If this is a bug fix, what versions of Traffic Control are affected?

- master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by zrhoffman** [comment]
> Currently the documentation says nodejs 12 or above is required.

https://github.com/apache/trafficcontrol/blob/f2cb7e12d2b437480e1b5b16c2f6f6429fe8ce61/traffic_portal/build/traffic_portal.spec#L28

Does TP not run correctly on Node 13 or above? If so, that should be documented.

**Comment by shamrickus** [comment]
There's no reason it shouldn't, but I think we want to pin our nodejs to a tested version.

**Comment by zrhoffman** [comment]
> [...] I think we want to pin our nodejs to a tested version.

That's an environment decision. The NodeSource yum repos are separated by Node.js major version (example: `https://rpm.nodesource.com/pub_12.x/el/8/x86_64/nodesource-release-el8-1.noarch.rpm`), so there's no danger of upgrading an existing `nodejs` package to a new major version. Since the EPEL `nodejs` versions for CentOS 7 and CentOS 8 are both under 12 anyway, specifying minimum version only should be sufficient.

**Review by zrhoffman — APPROVED** [review]

**Review by mitchell852 — APPROVED** [review]
lgtm

**Pull request merged**
