### PR TITLE
Added Alerts to several response structs

### LINKED ISSUE #3447: TO Client: Alerts are not returned even when they exist?
I am writing an api test for a PR I submitted: #3445

I have the following code:

```
func TryToDeleteDivision(t *testing.T) {
    division := testData.Divisions[0]
    resp, _, err := TOSession.DeleteDivisionByName(division.Name)

    fmt.Printf("resp: %v\n", resp)
    fmt.Printf("err: %v\n", err)

    if err == nil {
        t.Errorf("should not be able to delete a division prematurely")
        return
    }

    if len(resp.Alerts) == 0 {
        t.Errorf("error occurred while deleting division, but no alerts exist")
        return
    }

    switch resp.Alerts[0].Text {
    case "Resource not found.":
        t.Errorf("division with name %v does not exist", division.Name)
    case "This division is currently used by regions.":
        // expected return message
    default:
        t.Errorf("unexpected alert occurred: %v", resp)
    }
}
```

Below is the result. You can see that the error clearly returns the alert message I'm looking for, but when an error occurs the client doesn't return the alerts. At first glance this is confusing. Is there a particular reason this is done? I believe there is a go convention that says a returned error implies the first value is nil, but I don't think that makes sense in this case.

I can write this particular test differently, but maybe this makes sense to change?

```
resp: {[]}
err: 400 Bad Request[400] - Error requesting Traffic Ops https://localhost:6443/api/1.3/divisions/name/division1 {"alerts":[{"level":"error","text":"This division is currently used by regions."}]}
--- FAIL: TestDivisions (4.38s)
	divisions_test.go:47: error occurred while deleting division, but no alerts exist
FAIL
```

### PR DESCRIPTION
**Pull request by ZugNZwang**
## What does this PR (Pull Request) do?

Adds the `Alerts` struct to several response structs. 

- [X] This PR fixes #3447  

## Which Traffic Control components are affected by this PR?

- Traffic Control Go Client 

## What is the best way to verify this PR?

Run Traffic Ops API Tests 
Run Go Client tests
## The following criteria are ALL met by this PR

- [X] This PR includes tests OR I have explained why tests are unnecessary
- [X] This PR includes documentation OR I have explained why documentation is unnecessary
- [X] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [X] This PR includes any and all required license headers
- [X] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [X] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
Why'd you add all those new structures? They aren't used anywhere as far as I can see.

**Comment by ZugNZwang** [comment]
They will be used when testing the multiple federation routes.

**Comment by ocket8888** [comment]
But you didn't add them to any tests?

**Comment by ZugNZwang** [comment]
No, they'll be useful in replacing the similar structures that exist in the internal tests. We wouldn't need to redeclare them, because we could use the ones declared here.

**Pull request merged**
