### PR TITLE
[TC-157] router fail to restart due to failed to get SSL keys

### PR DESCRIPTION
**Pull request by zhilhuan**
need to return from the while loop when shutting down.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/31/

**Comment by zhilhuan** [comment]
What's happening here? Is this due to build server not reachable any more?

**Comment by hbeatty** [comment]
GH issue #914

**Comment by rawlinp** [comment]
Closing this because this doesn't appear to be an issue anymore (was unable to reproduce).

**Pull request closed without merging**
