### PR TITLE
cdn-in-a-box -- adds enroller to register containers into traffic ops

### PR DESCRIPTION
**Pull request by dangogh**
#### What does this PR do?

Adds new service to cdn-in-a-box called `enroller`.   `curl -X POST https://enroller?name=<service>` will register a container and its IP info with Traffic Ops.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other cdn-in-a-box

#### What is the best way to verify this PR?

- from `infrastructure/cdn-in-a-box`,  `docker-compose up trafficops enroller`. 
- `docker-compose exec trafficops bash`
- `curl -k -X POST https://enroller?name=trafficops`

Examine the db or use the TO API to list the servers -- you should see the `trafficops` server in that list with its IP info.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [ ] This PR does *NOT* fix a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2316/
Test PASSed.

**Comment by rob05c** [comment]
Just wondering, what's the advantage of a service here? Versus encapsulating this code as a library/app instead of a service, and making each component use the library to register itself? I'm just having trouble seeing the advantage of `component-->--enroller-->--TO` versus `component-->--TO`. 

Seems like a lot of additional complexity, both code and at the network and communication levels. What are the advantages?

**Comment by dangogh** [comment]
good question -- the advantage is not having all components have to have access to the docker server and admin access to TO.   Only this one service has the socket mounted, so it can grab info from docker and hand to TO.  Plus,  the others only need to have knowledge of TO only for purposes of interoperating with it in their normal capacity.

**Comment by rob05c** [comment]
>Only this one service has the socket mounted, so it can grab info from docker

>       - /var/run/docker.sock:/var/run/docker.sock

Ah, that makes sense. I don't fully understand why containers need access to Docker to register themselves, but sure, it makes sense to only have 1 container with that access.

>Plus, the others only need to have knowledge of TO only for purposes of interoperating with it in their normal capacity.

I'm not seeing the difference in a component needing knowledge of TO vs needing knowledge of an intermediary.

But sure, needing the socket makes sense. Thanks,

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2321/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2325/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2328/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2329/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2330/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2344/
Test FAILed.

**Comment by JBevillC** [comment]
This exception seems to happen if trafficops hasn't been seeded with the cachegroup(s).  Seems to be a race condition that happens infrequently. 

```enroller_1         | 2018/08/28 13:25:19 http: panic serving [fc01:9400:1000:8::5]:49740: runtime error: index out of range
enroller_1         | goroutine 26 [running]:
enroller_1         | net/http.(*conn).serve.func1(0xc420268d20)
enroller_1         |     /usr/local/go/src/net/http/server.go:1726 +0xd0
enroller_1         | panic(0x861a80, 0xb8e110)
enroller_1         |     /usr/local/go/src/runtime/panic.go:502 +0x229
enroller_1         | main.(*session).getCachegroupID(0xc42041c1c0, 0x1, 0x0, 0x0)
enroller_1         |     /go/src/github.com/apache/trafficcontrol/infrastructure/cdn-in-a-box/enroller/enroller.go:155 +0xfb
enroller_1         | main.(*session).enrollContainer(0xc42041c1c0, 0xc420306dc0, 0xbbe4c8, 0x0, 0x0, 0xc4201b0780, 0xc42019d300, 0x1, 0x4, 0xc4201b0f00)
enroller_1         |     /go/src/github.com/apache/trafficcontrol/infrastructure/cdn-in-a-box/enroller/enroller.go:221 +0x4f9
enroller_1         | main.(*session).enrollerHandler.func1(0x957c00, 0xc42024a000, 0xc420294a00)
enroller_1         |     /go/src/github.com/apache/trafficcontrol/infrastructure/cdn-in-a-box/enroller/enroller.go:325 +0x9b9
enroller_1         | net/http.HandlerFunc.ServeHTTP(0xc42053e000, 0x957c00, 0xc42024a000, 0xc420294a00)
enroller_1         |     /usr/local/go/src/net/http/server.go:1947 +0x44
enroller_1         | net/http.(*ServeMux).ServeHTTP(0xba0840, 0x957c00, 0xc42024a000, 0xc420294a00)
enroller_1         |     /usr/local/go/src/net/http/server.go:2337 +0x130
enroller_1         | net/http.serverHandler.ServeHTTP(0xc420544000, 0x957c00, 0xc42024a000, 0xc420294a00)
enroller_1         |     /usr/local/go/src/net/http/server.go:2694 +0xbc
enroller_1         | net/http.(*conn).serve(0xc420268d20, 0x9580c0, 0xc420418700)
enroller_1         |     /usr/local/go/src/net/http/server.go:1830 +0x651
enroller_1         | created by net/http.(*Server).Serve
enroller_1         |     /usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2355/
Test PASSed.

**Pull request merged**
