### PR TITLE
Use exact matching of requested name to certificate for SNI fields

### LINKED ISSUE #2821: Traffic Router may choose wrong certificate when SNI names overlap

### PR DESCRIPTION
**Pull request by limited**
#### What does this PR do?

Fixes #2821

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [X] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Provision two HTTPS delivery services with overlapping domain names
i.e. 4k-live.test.com and live.test.com

Verify the correct certificate is returned for requests to each DS

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [X] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2438/
Test PASSed.

**Comment by limited** [comment]
@ajschmidt @rawlinp Could you please review?

**Comment by rawlinp** [comment]
@limited yeah, sorry, I was taking a look at this on Friday but had an issue with my local TR dev environment that took most of the day to solve. I'll test it out today and merge if I don't see any issues.

**Pull request merged**
