### PR TITLE
Fix issues with flot

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR fixes some issues resultant from updating flot.

It also updates flot to the latest minor version `2.1.2 -> 2.1.6`.
`jquery-flot-axislabels` was removed as it is now a default plugin in flot.
Moved the flot installation from bower to npm (unrelated to fix).

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Ensure the dashboard charts all work.
Ensure charts under `delivery services > view charts` work.
Make sure TP build is successful for both dev and prod

## If this is a bug fix, what versions of Traffic Control are affected?
-master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by mitchell852** [comment]
Not sure why i'm seeing no values on the X axis

image

**Comment by shamrickus** [comment]
Fixed the labels for all charts with time axis

**Review by mitchell852 — CHANGES_REQUESTED** [review]
looks good but broken TP test. can you investigate @shamrickus

**Comment by shamrickus** [comment]
Fixed

**Pull request merged**
