### PR TITLE
renamed tr-tests GHA to tr-unit-tests

### LINKED ISSUE #5436: Rename tr-tests github action to tr-unit-tests for clarity of scope
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Router
-  CI tests

## Current behavior:
Currently the scope of the tr-tests github action is a bit unclear. Yes, you can read the README but, you know...

## New behavior:
Renaming to tr-unit-tests clarifies the scope of the GHA.

### PR DESCRIPTION
**Pull request by bueale**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5436 

## Which Traffic Control components are affected by this PR?

- Traffic Router
- .github/actions/tr-unit-tests/action.yml
- .github/actions/tr-unit-tests/README.md
- .github/workflows/tr.unit.tests.yaml

## What is the best way to verify this PR?

On the GitHub Actions run page: Run unit tests

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR does not require necessary documentation updates.
- [x] This PR includes NO necessary changes to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by mitchell852** [comment]
@alebricio - make sure you complete the PR template

**Review by zrhoffman — CHANGES_REQUESTED** [review]
Everything changed so far looks fine. On the GitHub Actions *run* page:
*test* and *Run unit tests*
1.Can *tests* be reworded?
2. Can *Run unit tests* be reworded to specify which unit tests are being run?

**Comment by alebricio** [comment]
> @alebricio - make sure you complete the PR template

@mitchell852 I believe this was intended for @bueale

**Comment by mitchell852** [comment]
> > @alebricio - make sure you complete the PR template
> 
> @mitchell852 I believe this was intended for @bueale

haha. sorry. @bueale ^^

**Review by zrhoffman — APPROVED** [review]
Looks good! On second thought, no need to rename the *test* job, because there is only 1 job, and all places where it is mentioned, you can see the name of the workflow anyway.

**Pull request merged**
