### PR TITLE
Fix Traffic Ops auth failure returning 200, catastrophically breaking clients

### PR DESCRIPTION
**Pull request by rob05c**
This specifically fixes a major bug, where auth failure returns a 200.

This causes a major bug in the TO Go client, (and likely other
clients) which assumes a 200 to be success, and then goes on to request
data, gets more auth failures with 200's, but thinks they're success,
and thinks the JSON is just missing all fields, which are defaulted
to 0/empty string/null.

This causes other bugs that just went unnoticed, like missing the
Access-Control headers, X-Server-Name, and gzipping.

Includes API Tests.

#### What does this PR do?

This specifically fixes a major bug, where auth failure returns a 200, breaking clients.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Run TO API Tests.

Run Traffic Ops and e.g. `curl -Lvsk https://your-traffic-ops.example.net/api/1.2/cdns`, you should get a `401`, along with `access-control` and `x-server-name` headers. 

Run `curl -Lvsk -H "Accept-Encoding: gzip" https://localhost/api/1.2/cdns | gunzip`, and verify a `content-encoding: gzip` header, and successful decoding by `gunzip`.

Go to `https://your-traffic-ops.example.net/api/1.2/cdns` in a web browser (which hasn't previously logged in, and therefore doesn't have an auth cookie), and verify the same results in a debug console (Readable error, `content-encoding: gzip`, `401` code).

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2823/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2826/
Test FAILed.

**Comment by rob05c** [comment]
@dangogh I'd value your review of this. I don't think anyone else still active on the project is as familiar with it. I'm not 100% positive there wasn't a good reason for it being the way it was.

But it's certainly an issue for auth failure not to include the headers and gzip, even if it weren't for the critical status code bug. And it's not like it could be skipped AFAIK, wrappers can't make the system skip a different wrapper.

Thanks,

**Comment by mitchell852** [comment]
@rob05c - is this something that will get backported to 3.0.x? And if so, is there a 3.0.x RC that needs to get -1'd?

**Comment by rob05c** [comment]
@mitchell852 No, I tested 3.0.x and the critical bug isn't in it. The general problem of misordered auth wrapping omitting headers and gzip is, but I don't think those are worth -1'ing the RC for.

**Comment by ezelkow1** [comment]
I have tested with this in CIAB and my TM changes that flip between disk and url usage. This fix allowed it to work properly where as before TM could not login

**Pull request merged**
