### PR TITLE
Add Dockerfile, docker-compose and build scripts for ATS and astats [WIP]

### PR DESCRIPTION
**Pull request by limited**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by smalenfant** [comment]
@limited Do you have some instructions to go with this? Tried to bring up with docker-compose but it failed to find the build.sh.

From root:
`docker-compose -f infrastructure/docker/build/docker-compose.yml up ats_build`

or from the docker directory:
`docker-compose up ats_build`

**Comment by limited** [comment]
I haven't used this script in a few months. Do you have an exact error message? I can try to bring this up to date

**Comment by smalenfant** [comment]
Here's the output.
```
Creating build_ats_build_1 ... done
Attaching to build_ats_build_1
ats_build_1              | + cp -a /trafficcontrol /tmp/.
ats_build_1              | + cd /tmp/trafficcontrol
ats_build_1              | + rm -rf dist
ats_build_1              | + mkdir -p /trafficcontrol/dist
ats_build_1              | + ln -s /trafficcontrol/dist dist
ats_build_1              | + read x
ats_build_1              | + ./build/build.sh traffic_server
ats_build_1              | + tee ./dist/build-traffic_server.log
ats_build_1              | git is /usr/bin/git
ats_build_1              | rpmbuild is /usr/bin/rpmbuild
ats_build_1              | + echo 1
ats_build_1              | Build environment has been verified.
ats_build_1              | ==================================================
ats_build_1              | WORKSPACE: /tmp/trafficcontrol
ats_build_1              | BUILD_NUMBER: 8690.6261067f
ats_build_1              | RHEL_VERSION: el7
ats_build_1              | TC_VERSION: 2.3.0
ats_build_1              | --------------------------------------------------
ats_build_1              | traffic_server/build/build_rpm.sh not found
ats_build_1              | The following subdirectories had errors: 
ats_build_1              |    traffic_server
ats_build_1              | + exit 1
ats_build_1              | + cleanup
ats_build_1              | + setowner /trafficcontrol /trafficcontrol/dist
ats_build_1              | ++ stat -c %u:%g /trafficcontrol
ats_build_1              | + own=0:0
ats_build_1              | + shift
ats_build_1              | + [[ -n /trafficcontrol/dist ]]
ats_build_1              | + chown -R 0:0 /trafficcontrol/dist
build_ats_build_1 exited with code 1
```

**Comment by limited** [comment]
@smalenfant PR was missing a file, just added it

**Pull request closed without merging**
