### PR TITLE
Go client upgrade

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR is not related to any Issue

Upgrades the Go client to use TO API v2. The old v1 client is now available in `traffic_ops/v1-client/` and the v1 API/client integration tests have been updated to import it properly from that path. This PR also came with a few improved GoDocs, and a consistent format for constants that hold API routes e.g. API_ABOUT instead of API_v13_About or API_v3_ABOUT or case transformations thereof. Which isn't to say all files use these constants, just that those that do use the consistent naming.

This PR also removes client methods for endpoints that don't exist in API v2 (not from the v1 client).

## Which Traffic Control components are affected by this PR?
- Traffic Control Client (Go), and therefore:
	- Grove
	- Traffic Monitor
	- Traffic Ops ORT (ATSTCCFG)
	- Traffic Stats

## What is the best way to verify this PR?
Run all of the applicable Go unit tests, run the client v1 API/integration tests, run the individual affected components and make sure they can still reach and parse the data they need.

## The following criteria are ALL met by this PR
- [x] Tests will be added in #4374 
- [x] GoDocs make the client self-documenting
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by ocket8888** [comment]
ah, that must be rebase issues. I'll fix it

**Comment by mhoppa** [comment]
missing one more new method 
```
# github.com/apache/trafficcontrol/traffic_ops/testing/api/v1 [github.com/apache/trafficcontrol/traffic_ops/testing/api/v1.test]
./parameters_test.go:54:27: TOSession.CreateMultipleParameters undefined (type *"github.com/apache/trafficcontrol/traffic_ops/v1-client".Session has no field or method CreateMultipleParameters)
```
FAIL    github.com/apache/trafficcontrol/traffic_ops/testing/api/v1 [build failed]

**Comment by mhoppa** [comment]
still getting failures on the tests are you having them pass locally?

```
--- FAIL: TestCacheGroupParameters (1.40s)
    types_test.go:32: ---- CreateTestTypes ----
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    types_test.go:39: Response:  {[{type was created. success}]}
    parameters_test.go:55: Response:  {[]}
    parameters_test.go:57: could not CREATE parameters: 400 Bad Request[400] - Error requesting Traffic Ops https://localhost:6443/api/1.4/profiles {"alerts":[{"text":"json: cannot unmarshal array into Go value of type profile.TOProfile","level":"error"}]}
    types_test.go:96: ---- DeleteTestTypes ----
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 2085 [running]:
testing.tRunner.func1(0xc0005dca00)
        /usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1558720, 0x1aadef0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/apache/trafficcontrol/traffic_ops/testing/api/v1.CreateTestCacheGroupParameters(0xc0005dca00)
        /Users/mhoppa509/go/src/github.com/apache/trafficcontrol/traffic_ops/testing/api/v1/cachegroups_parameters_test.go:56 +0x61e
github.com/apache/trafficcontrol/traffic_ops/testing/api/v1.WithObjs(0xc0005dca00, 0xc0013b3f68, 0x4, 0x4, 0xc0013b3f88)
        /Users/mhoppa509/go/src/github.com/apache/trafficcontrol/traffic_ops/testing/api/v1/withobjs_test.go:31 +0x61
github.com/apache/trafficcontrol/traffic_ops/testing/api/v1.TestCacheGroupParameters(0xc0005dca00)
        /Users/mhoppa509/go/src/github.com/apache/trafficcontrol/traffic_ops/testing/api/v1/cachegroups_parameters_test.go:26 +0x82
testing.tRunner(0xc0005dca00, 0x162a990)
        /usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:916 +0x35a
exit status 2
FAIL    github.com/apache/trafficcontrol/traffic_ops/testing/api/v1     18.486s
```

**Comment by ocket8888** [comment]
I haven't run the api/integration tests since the rebase, you're reviewing faster than I can test (I have to push to test because I run the tests on a remote machine)

**Comment by ocket8888** [comment]
_Now_ they're passing for me locally.

**Pull request merged**
