### PR TITLE
Updated traffic_ops.spec to be golang >= 1.9.4 instead of =

### PR DESCRIPTION
**Pull request by hbeatty**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

Fixes # yum install issue with Traffic Ops 3.0.0

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

Build the Traffic Ops rpm and do a "yum install traffic_ops" on CentOS 7.6.

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3239/
Test PASSed.

**Comment by dg4prez** [comment]
Hank, there is an RC out for 3.0.x currently.  is this intended to be a -1 against it?

**Comment by hbeatty** [comment]
I would not call this a -1 but, if someone else comes up with a -1 I think this should go in.

The rpm will not install on an up-to-date CentOS 7.6 as-is. This fixes that. Also, I think the recommended minimal version of golang is 1.10.x.

Maybe @dneuman64 and/or @rob05c could weigh in with thoughts.

**Comment by dg4prez** [comment]
I'm going to close this PR, as it's not needed for 3.0.x and we haven't really tested against those two versions of cent/go much yet.  Will merge into master for the next release.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3316/
Test PASSed.

**Pull request merged**
