### PR TITLE
Now ignoring editor/IDE-specific configuration files

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR is not related to any Issue

Adds editor/IDE-specific temporary/configuration files to `.gitignore` files. This also removes some of the pre-existing editor/IDE-specific configuration files from the repositiory.

## Which Traffic Control components are affected by this PR?
None. Just a tracking change.

## What is the best way to verify this PR?
Make sure I didn't add something like `**.go` to the `.gitignore`s.

## The following criteria are ALL met by this PR

- [x] Tests are unnecessary
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3757/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3818/
Test FAILed.

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3822/
Test PASSed.

**Pull request merged**
