### PR TITLE
Configure session tracking on TO side

### PR DESCRIPTION
**Pull request by weifensh**
This PR work together with PR #643

### CODE REVIEW

**Comment by limited** [comment]
Thanks John-
  The diff is quite large, mostly because of whitespace and some formatting related changes. 

Can you please try to minimize the size of the diff to just changes directly related to the Session Tracking code so that its easier to review?

**Comment by weifensh** [comment]
@limited Thanks Eric. The white spaces and tabs are mostly introduced by perltidy. Some are caused by reformatting with the new code. And others are because it appears some original files are not following the formatting conventions at https://trafficcontrol.incubator.apache.org/docs/latest/development/traffic_ops.html and thus they are reformatted by perltidy in this PR. I might be asked to run perltidy if I reduce the diff;-)

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/14/

**Comment by dewrich** [comment]
@limited @weifensh Is there a way we can prevent adding yet another field to the Delivery Service Table?  If we are tracking sessions, maybe that should be a separate table (with the session metadata we care about) that points back to the Delivery Service table.

**Comment by mitchell852** [comment]
and was this discussed on the ML because i'm a pretty hard -1 on more DS table columns (if possible). That table is way out of control imo (50+ columns already?). @knutsel did introduce ds profiles...maybe that could be leveraged instead? i don't know.

**Comment by limited** [comment]
There's 2 fields- a boolean and a list of the keys to use from the cookie. The list is expected to be short, just a few entries long. No session metadata is stored in the TO DB. 

I agree we need better approach to DS options, but I don't think this is the PR to hinge things on.

**Comment by anna-k-1** [comment]
@weifensh We are going to close this - sorry! If you still want this feature, please rewrite in Go and resubmit and someone will check it out.

**Pull request closed without merging**
