### PR TITLE
ensure tenant set where needed; add not null constraint

### LINKED ISSUE #2520: TO Go API: deliveryservices_regexes gets 500 error
After loading Kabletown data (`cd /opt/traffic_ops/app; ./bin/db/setup_kabletown.pl`),  I hit the `GET api/1.3/deliveryservices_regexes`  endpoint and got a 500 error with this return JSON:

```
{
  "alerts": [
    {
      "text": "querying: sql: Scan error on column index 1: converting driver.Value type <nil> (\"<nil>\") to a int: invalid syntax",
      "level": "error"
    }
  ]
}
```

Hitting the Perl endpoint instead,  I get this (cut for brevity):
```
{
  "response": [
    {
      "regexes": [
        {
          "pattern": ".*\\.images\\..*",
          "setNumber": 0,
          "type": "HOST_REGEXP"
        }
      ],
      "dsName": "cdl-c2"
    },
...
```

### LINKED ISSUE #2521: TO Go API: GET .../deliveryservices returns empty list
Initialized traffic ops db using  Kabletown test data (`cd /opt/traffic_ops/app; ./bin/db/setup_kabletown.pl`):
`curl https://.../api/1.3/deliveryservices`  returns `{"response":[]}`

The same query on the Perl endpoint returns an array with 8 entries.

### PR DESCRIPTION
**Pull request by dangogh**
Adds sql to set tenant on tm_user, deliveryservice, and origin tables and then adds NOT NULL constraint to ensure it is set from here on.   This should allow us to move forward with eliminating dependency on the `use_tenancy` parameter.

Fixes #2520 
Fixes #2521 
partially addresses #2273

### CODE REVIEW

**Comment by dangogh** [comment]
apply to existing data using `./db/admin.pl -env production patch`

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2060/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2061/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2068/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2069/
Test PASSed.

**Comment by dangogh** [comment]
added WIP label as we need to evaluate this approach.   Please do not merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2094/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2133/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2134/
Test PASSed.

**Comment by dangogh** [comment]
To test,   set up kabletown data and upgrade the db:
```
cd /opt/traffic_ops/app
./bin/db/setup_kabletown.pl
./db/admin.pl -env production upgrade
```

then hit an endpoint that failed previously, e.g. `/api/1.1/deliveryservices_regexes`

**Pull request merged**
