### PR TITLE
add profile constraint cdn not null

### LINKED ISSUE #2710: TO Go -- db access error if profile.cdn is null
hitting the `POST /api/1.3/servers` endpoint.   If the profile indicated has a null cdn, I get a db access error:
```
ERROR: servers.go:128: could not scan cdnID from profile: sql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int: invalid syntax
```

The `POST .../profiles` endpoint doesn't allow a null cdn, but the profiles in `seeds.sql` create the initial set that way.   That needs to be fixed and a not null constraint placed on it,  or the servers endpoint needs to handle it appropriately.

### PR DESCRIPTION
**Pull request by dangogh**
#### What does this PR do?
Adds constraint to profile table to disallow null cdn.
Only does this after ensuring that any null cdn currently in the db is set to the `ALL` cdn.

Fixes #2710 

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
From a previous version of TO, get a copy of the database.

`psql ... traffic_ops -c '\d profile'` should not show `not null` in the description of the cdn column.    Run `db/admin.pl upgrade` and do the same psql command -- should now show `not null`.

Run `db/admin.pl reset` to put the db back to initial state.  That column should show `not null`.

Tests included in the api tests:
```
cd traffic_ops/testing/api/v13
go test -v -cfg=... -run TestProfiles
```
#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [x] This PR does *NOT* fix a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2285/
Test FAILed.

**Comment by mitchell852** [comment]
@dangogh - how about some kind of test. i.e. try to make a profile thru the api with a null cdn and ensure that it fails

**Comment by dangogh** [comment]
@mitchell852 - api test added to attempt to create a bad profile -- one each for all the required fields.
```
cd traffic_ops/testing/api/v13
go test -v -cfg=... -run TestProfiles
```

**Comment by rob05c** [comment]
For the record, I don't approve of testing Postgres itself. It's certainly valuable to test the API, for example, verifying that an attempt to insert a profile without a CDN returns a proper 4xx or 5xx with a proper message (assuming those tests aren't too relatively expensive to write).

But IMO we shouldn't be writing tests which do nothing but verify that PostgreSQL behaves correctly. The only thing this test verifies, is that PostgreSQL database constraints work correctly. IMO it's not the job of Traffic Control to verify PostgreSQL' behavior, and such tests obfuscate and obstruct the useful tests.

But, I'm merging, because the value of this fix far outweighs any undesirability.

**Comment by dangogh** [comment]
@rob0c actually,  it doesn't test the constraint at all.  It tests the validation on the profile object which prevents it from even doing a query.

Point taken,   though

**Comment by rob05c** [comment]
Ah, you're right, I was mistaken

**Comment by dangogh** [comment]
fixes #2682

**Pull request merged**
