### PR TITLE
Add TO client v4 fallback

### LINKED ISSUE #5518: Add Traffic Ops Client Minor Fallback to v4-client
There's a new `traffic_ops/v4-client`, the fallback logic in https://github.com/apache/trafficcontrol/pull/5430 needs added to it, in order to support one Traffic Control release prior in apps that use the client (like TM and ORT), to make upgrading possible.

## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Control Client

## Current behavior:
v4-client doesn't fall back.

## New behavior:
v4-client falls back to previous minors

## Minimal reproduction of the problem with instructions:
Make a request with v4-client to the previous minor Traffic Ops, observe failure.

### PR DESCRIPTION
**Pull request by rob05c**
Also moves duplicate fallback and other duplicate client code
to a shared lib.

No new tests, existing TO API Tests cover these changes.
No docs, no interface change.
No changelog, client fallback already has a changelog entry.

- [x] This PR fixes #5518 OR is not related to any Issue

## Which Traffic Control components are affected by this PR?
- Traffic Control Client Go

## What is the best way to verify this PR?
Run tests. Make requests with the client, verify they work as expected.

## If this is a bug fix, what versions of Traffic Control are affected?
Not a bug fix.

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

### CODE REVIEW

**Comment by ocket8888** [comment]
Looks like it failed to build the enroller:

```
2021-02-22T00:34:57.7359211Z #6 45.14   Running scriptlet: gettext-0.19.8.1-17.el8.x86_64                       19/21#17 8.163 github.com/apache/trafficcontrol/traffic_ops/v4-client imports
2021-02-22T00:34:57.7360512Z #17 8.163 	github.com/apache/trafficcontrol/traffic_ops/toclientlib: no matching versions for query "latest"
```

**Comment by rob05c** [comment]
Fixed the Enroller

**Review by rawlinp — APPROVED** [review]
This looks good -- I just want to try it out locally before merging.

**Comment by ocket8888** [comment]
I don't believe this can go into 5.1.1 unless we're putting APIv4 into that release. Which I don't want to do.

**Pull request merged**
