### PR TITLE
Add support for Centos8 and optionally including openssl

### LINKED ISSUE #5624: ATS build doesn't produce el8 rpms from pkg
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  ATS build

## Current behavior:
`./pkg -v -o -8 ats`
produces
`trafficserver-8.0.8-11.d8c530a.el7.x86_64.rpm`

## Expected behavior:
I expect it to produce `trafficserver-8.0.8-11.d8c530a.el8.x86_64.rpm`

## Minimal reproduction of the problem with instructions:

`./pkg -v -o -8 ats`

### PR DESCRIPTION
**Pull request by jhg03a**
Closes #5624

## What does this PR (Pull Request) do?

- [x] This PR fixes #5624

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- ATS Build

## What is the best way to verify this PR?

`./pkg -v -o -7 ats && ./pkg -v -o -8 ats`

## If this is a bug fix, what versions of Traffic Control are affected?

- master (74c07997b9)

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by jhg03a** [comment]
Notably, making the inclusion of openssl along with the RPM optional was actually needed for Centos8 support as there is a conflict between the version we package and the system kerberos libraries that are also used.

**Review by zrhoffman — CHANGES_REQUESTED** [review]
The CentOS 8 RPM (but not the CentOS 7 RPM) includes a `/usr/lib/.build-id` directory.

**Review by zrhoffman — COMMENTED** [review]
Also, I have trouble installing the RPM on CentOS 8:

```shell
[root@8c5e2e457462 /]# dnf -y install trafficserver-8.0.8-11.13ba7009f.el8.x86_64.rpm
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:05:13 ago on Fri Mar 12 23:50:24 2021.
Error:
 Problem: package trafficserver-11318:8.0.8-11.13ba7009f.el8.x86_64 requires libcjose.so.0()(64bit), but none of the providers can be installed
  - conflicting requests
  - package cjose-0.6.1-2.module_el8.2.0+463+d53af530.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by jhg03a** [comment]
The new .build-id files are [a feature, not a bug](https://bugzilla.redhat.com/show_bug.cgi?id=1724153).

**Review by zrhoffman — CHANGES_REQUESTED** [review]
This all looks good, it just needs a changelog entry.

**Review by zrhoffman — APPROVED** [review]
* Confirmed that the CiaB readiness container exits successfully when using ATS 8.0.x built for CentOS 8 (02b8f117fb).
* Confirmed that the CiaB readiness container exits successfully when using ATS 8.0.x built for CentOS 7 (452704bc53).
* Can choose to build for CentOS 8 or CentOS 7 using the `-8` or `-7` flag, or by setting the `RHEL_VERSION` environment variable to `8` or `7`, which matches our build behavior for the other components.

**Pull request merged**
