### PR TITLE
GitHub Actions: Cache Maven dependencies

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- This PR fixes building Traffic Router in GitHub Actions by caching Maven dependencies. It looks like GitHub Actions doesn't rate-limit downloads the same way if you use caching.
- [x] This PR is not related to any Issue 

This will speed up building TR as well, which always takes the longest of any component to build on GitHub Actions
## Which Traffic Control components are affected by this PR?

- CI tests

## What is the best way to verify this PR?

Check the Traffic Router GitHub Actions result, since GHA is the only place experiencing rate limiting.

## If this is a bug fix, what versions of Traffic Control are affected?

 - master (cd75524e6e)

## The following criteria are ALL met by this PR

- [x] Not reproducible outside of GitHub Actions since GitHub Actions is the thing rate-limiting our TR-building action's request
- [x] Project components are unchanged, no documentation necessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by ocket8888 — APPROVED** [review]
Clearly fixes CI because the actions worked

**Comment by ocket8888** [comment]
We should also be doing this for TP's node_modules dependencies, btw.

**Comment by MylesBock** [comment]
I got on this topic last night and threw a few more things in the mix that may aid this job:

https://github.com/MylesBock/trafficcontrol/runs/1129862202

Performs roughly the same caching of maven artifacts, adds a little finegrained control over `settings.xml`, but also tweaks how `traffic_router` is built by limiting the number of artifact download and build threads

**Comment by zrhoffman** [comment]
Sorry, I didn't know anyone else was working on it (and should have made a GitHub issue before submitting a PR to fix). If you aren't there already, feel free to join #traffic_router on the Apache Traffic Control slack (there's an invite link [in the docs](https://traffic-control-cdn.readthedocs.io/en/latest/faq.html#how-do-i-get-help-with-traffic-control)). If think it can be improved further, though, feel free to open a PR.

I also opened #5042 to document that we don't cache NPM dependencies.

**Pull request merged**
