### PR TITLE
systemd: traffic_router.service is marked executable

### LINKED ISSUE #3011: tr: systemd: traffic_router.service is marked executable
Seeing the following in systemd. Tomcat RPM is installing service with 755 permissions.

```
Nov 12 12:23:19 cdn1cdcrs0002 systemd: Configuration file /usr/lib/systemd/system/traffic_router.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

### LINKED ISSUE #3014: traffic_router rpm creates backup up traffic_router.service on removal
When uninstalling/upgrading tomcat, the traffic_router.service file is preserved under `traffic_router.rpmsave`. This creates a problem when installing a new version of traffic router with updated `.service.` file. The old settings are kept.

```
# ls -l /usr/lib/systemd/system | grep traffic_router
-rwxr-xr-x 1 root root 1225 Nov 12 13:14 traffic_router.service
-rwxr-xr-x 1 root root 1224 Nov 12 12:54 traffic_router.service.rpmsave

```

### PR DESCRIPTION
**Pull request by smalenfant**
#### What does this PR do?

Fixes #3011
Fixes #3014 

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [X] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

After installing Traffic Router, verify /var/log/messages to make sure this message doesn't appear:

```
systemd: Configuration file /etc/systemd/system/tomcat.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```
Also, verify that traffic_server.service has proper permission (644)

```
]# ls -l /usr/lib/systemd/system/traffic_router.service
-rw-r--r-- 1 root root 1224 Nov 12 13:58 /usr/lib/systemd/system/traffic_router.service
```

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2764/
Test PASSed.

**Comment by smalenfant** [comment]
There was 2 problems. Although not sure why we have both tomcat and traffic_router services.

```
systemd: Configuration file /usr/lib/systemd/system/traffic_router.service is marked executable. Please remove executable permission bits. Proceeding anyway.
systemd: Configuration file /etc/systemd/system/tomcat.service is marked executable. Please remove executable permission bits. Proceeding anyway.
```

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2766/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2769/
Test PASSed.

**Comment by smalenfant** [comment]
Closing. Will be part of bigger PR.

**Pull request closed without merging**
