### PR TITLE
Updates and bugfixes for ToDSCPCheck.pl

### PR DESCRIPTION
**Pull request by hbeatty**
* added 2 command line options
  * -s for specifying server
  * -d for delivery servers
* made the logging level more granular
* ignores servers that are OFFLINE or CCR_IGNORE
  * before it was only doing reported
* checks the port on the server before checking the delivery service
  * assures the server is actually up and reachable. if the server wasn't there the script would hang.
* if the curl version is great enough it defaults to checking via HTTPS
* added matchList back in
* cut down on duplcated code

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/15/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/23/

**Comment by dneuman64** [comment]
@hbeatty would you still like to see this merged?  If so, can you please fix the merge conflicts and get with me to merge?  If not, can you please close?

**Comment by hbeatty** [comment]
@dneuman64 I'll roll these changes in with my new changes.

**Pull request closed without merging**
