### PR TITLE
Pin node version in dev ciab TP/TPv2

### PR DESCRIPTION
**Pull request by shamrickus**
Currently the TP/TPv2 dev containers have issues starting due to node/npm versioning. `node:alpine` uses a recent node which is v19, many of our dependencies don't support this version causing the install to fail. This PR pins the node to version 14. Node 14 is in maintenance mode as of [two weeks ago](https://github.com/nodejs/release#release-schedule), so whenever angular in tpv2 is updated these can be bumped to 16.
<hr/>

## Which Traffic Control components are affected by this PR?

- CDN in a Box (dev)

## What is the best way to verify this PR?
Verify the TP/TPv2 dev containers are able to startup. The containers should also not complain about node version mismatch.

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
When I run the dev env on this branch, Traffic Router and tpv2 fail to start.

<details><summary>Traffic Router Logs</summary>

```
trafficrouter_1   | [INFO] Scanning for projects...
trafficrouter_1   | [INFO] ------------------------------------------------------------------------
trafficrouter_1   | [INFO] Reactor Build Order:
trafficrouter_1   | [INFO] 
trafficrouter_1   | [INFO] traffic_router                                                     [pom]
trafficrouter_1   | [INFO] traffic_router_shared                                              [jar]
trafficrouter_1   | [INFO] traffic_router_connector                                           [jar]
trafficrouter_1   | [INFO] traffic_router_config                                              [jar]
trafficrouter_1   | [INFO] traffic_router_geolocation                                         [jar]
trafficrouter_1   | [INFO] ROOT                                                               [war]
trafficrouter_1   | [INFO] 
trafficrouter_1   | [INFO] ------< org.apache.traffic_control.traffic_router:traffic_router >------
trafficrouter_1   | [INFO] Building traffic_router 7.1.0                                      [1/6]
trafficrouter_1   | [INFO] --------------------------------[ pom ]---------------------------------
trafficrouter_1   | [INFO] 
trafficrouter_1   | [INFO] --< org.apache.traffic_control.traffic_router:traffic_router_shared >---
trafficrouter_1   | [INFO] Building traffic_router_shared 7.1.0                               [2/6]
trafficrouter_1   | [INFO] --------------------------------[ jar ]---------------------------------
trafficrouter_1   | Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
trafficrouter_1   | [INFO] ------------------------------------------------------------------------
trafficrouter_1   | [INFO] Reactor Summary for traffic_router 7.1.0:
trafficrouter_1   | [INFO] 
trafficrouter_1   | [INFO] traffic_router ..................................... SUCCESS [  0.003 s]
trafficrouter_1   | [INFO] traffic_router_shared .............................. FAILURE [  5.638 s]
trafficrouter_1   | [INFO] traffic_router_connector ........................... SKIPPED
trafficrouter_1   | [INFO] traffic_router_config .............................. SKIPPED
trafficrouter_1   | [INFO] traffic_router_geolocation ......................... SKIPPED
trafficrouter_1   | [INFO] ROOT ............................................... SKIPPED
trafficrouter_1   | [INFO] ------------------------------------------------------------------------
trafficrouter_1   | [INFO] BUILD FAILURE
trafficrouter_1   | [INFO] ------------------------------------------------------------------------
trafficrouter_1   | [INFO] Total time:  5.883 s
trafficrouter_1   | [INFO] Finished at: 2022-11-01T15:06:13Z
trafficrouter_1   | [INFO] ------------------------------------------------------------------------
trafficrouter_1   | [ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom: Unknown host repo.maven.apache.org: Try again -> [Help 1]
trafficrouter_1   | [ERROR] 
trafficrouter_1   | [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
trafficrouter_1   | [ERROR] Re-run Maven using the -X switch to enable full debug logging.
trafficrouter_1   | [ERROR] 
trafficrouter_1   | [ERROR] For more information about the errors and possible solutions, please read the following articles:
trafficrouter_1   | [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

</detalis>

TPv2 logs are just... empty. The container is running, but it never does anything.

**Comment by shamrickus** [comment]
> TPv2 logs are just... empty. The container is running, but it never does anything.
If it's not displaying anything then `npm ci/install` is probably still doing it's thing. I have no idea why but it _can_ take a lot longer to do that in the container.

**Comment by ocket8888** [comment]
No it's not displaying anything, at all. Like I would show you the logs but they're literally empty.

**Comment by shamrickus** [comment]
> No it's not displaying anything, at all. Like I would show you the logs but they're literally empty.
Assuming the container is still running, I stand by what I said. It took 10 minutes for it to display anything for me this morning.

Regardless I've tested on two separate machines using OSX and linux and they both work flawlessly.

**Comment by zrhoffman** [comment]
> When I run the dev env on this branch, Traffic Router and tpv2 fail to start.

Both TR and TPv2 start as expected for me on Linux on #7164's branch

**Comment by ocket8888** [comment]
Well, I don't know what exactly the issue was, but after 7 hours there was still nothing in the logs. So I purged my docker cache, removed most directories from my local repo and restored from the tip of this branch, then tried again. And it works now.

**Review by ocket8888 — APPROVED** [review]

**Pull request merged**
