### PR TITLE
[TC-385] check origin host name is IPv6 address

### PR DESCRIPTION
**Pull request by zhilhuan**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/19/

**Comment by hbeatty** [comment]
GH issue #899

**Comment by rob05c** [comment]
So, it looks like #899 was closed, with the idea that Origins should always be hostnames. I can certainly see the use case of needing IPs for origins, if you don't have a DNS hostname.

This was also in Perl, the code is now in Go in `traffic_ops/traffic_ops_golang`. If you still need this, can you start a discussion on the mailing list, to get consensus to allow IPs in Origin FQDNs? Thanks,

**Pull request closed without merging**
