### PR TITLE
removed JDNSSEC from Traffic Router

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR do?
Removes JDNSSEC from Traffic Router's code base and build script.
Also includes documentation updates fixing some inaccuracies/things that were overlooked in previous updates, as well as spelling, grammar and indentation fixes.

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

## What is the best way to verify this PR?
Try to build, install and test Traffic Router (tested with CIAB and appears to build and run fine under normal conditions, but CIAB doesn't support DNSSEC yet)

## Check all that apply

- [ ] This PR includes tests
- [x] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2809/
Test PASSed.

**Comment by mitchell852** [comment]
TR unit tests all pass? mvn clean test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2819/
Test PASSed.

**Comment by ocket8888** [comment]
Tests are passing, now that I know how to run them - this PR now also includes an update to the docs on how to run the tests.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2822/
Test PASSed.

**Pull request merged**
