### PR TITLE
Refactor deliveryservice API minor versioning

### LINKED ISSUE #3497: TO API clients that don't specify the latest minor version will overwrite/default any fields introduced in later versions
For example:
1. POST a new deliveryservice using the **1.4** API with `deepCachingType = "ALWAYS"`
2. GET the new deliveryservice using the **1.4** API and observe that `deepCachingType == "ALWAYS"`
3. Using the resulting deliveryservice json from the GET request without making any changes, PUT the new deliveryservice using the **1.2** API.
4. GET the updated deliveryservice using the **1.4** API and observe that the `deepCachingType` field has been inadvertently _overwritten_ to `"NEVER"` (the default value).

This example was for `deepCachingType`, but this issue most likely affects all other deliveryservice fields between the different minor versions too.

### PR DESCRIPTION
**Pull request by rawlinp**
Remove all version-specific logic from the deliveryservices API
implementation except for the logic of upgrading requests of previous
minor versions into requests of the latest minor version to be handled
as such. All main logic now uses and belongs to the "latest" struct, so
it is no longer confusing as to which methods need updated/called for
various minor version structs. The versioned structs are now only
required and used for unmarshalling requests of a specific minor
version, upgrading those requests to the latest minor version, and
marshalling responses back down into the requested version. It should be
much more clear now how to implement and add a new minor version to the
deliveryservices API (also with updated README instructions).

## What does this PR (Pull Request) do?

- [x] This PR fixes #3497 

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops

## What is the best way to verify this PR?

Review the added TO API tests and verify that they sufficiently cover the expected minor version functionality (e.g. fields that don't belong to the requested minor version should be ignored by the API, and the API should only return fields that belong to the requested minor version). Then, run the TO API tests and verify that they pass.

## If this is a bug fix, what versions of Traffic Ops are affected?

- master (7efe4d0aa32148d4922c5710c3493d6a3c557ab7)
- 3.0.0
- 3.0.1

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3939/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3940/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3941/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3944/
Test PASSed.

**Comment by rob05c** [comment]
Sure, that sounds fine. I don't feel strongly enough to hold this up.

**Pull request merged**
