### PR TITLE
[TC-161] ort does not restart ATS when it should

### LINKED ISSUE #913: [TC-161] ort does not restart ATS when it should
<p>ort does not restart ATS when ATS is already running</p>

Author: John Shen
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-161">https://issues.apache.org/jira/browse/TC-161</a>
Found Version: 2.1.0

### PR DESCRIPTION
**Pull request by weifensh**
Fixes #913

ort does not restart ATS, because ort mistakenly thought ATS is not running when ATS is actually running

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/44/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/30/

**Comment by hbeatty** [comment]
GH issue #913

**Comment by dneuman64** [comment]
can you please rebase?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-whatchanged/54/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/185/

**Comment by dg4prez** [comment]
I hate to ask, but if you can rebase this again I can merge it, now.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/512/

**Comment by weifensh** [comment]
@dg4prez rebased, please check

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/560/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/516/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/871/
Test PASSed.

**Comment by ocket8888** [comment]
This has already been implemented at some point, and this PR should be closed.

**Pull request closed without merging**
