### PR TITLE
Fixes #2397 - Removed required validation on 'value' from parameters…

### LINKED ISSUE #2397: TP - empty value field for parameter not accepted
With the old TO UI we do currently have parameters that have/use empty value fields, i.e. various ATS plugins. These were valid in the TO ui but if you open them now are invalid the TP UI.  This also prevents you from adding a new parameter that is similar to these

### PR DESCRIPTION
**Pull request by chadgilloth**
… table. Removed api validation on 'value'. Removed required in ui for 'value.'

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by mitchell852** [comment]
This looks fine to me and is the simplest solution (which is good). My only concern is are there any downstream impacts of a null parameter value?

**Comment by rob05c** [comment]
I have the same concerns. What's the valid use case for a value-less parameter?

I thought the old UI/API set values to the empty string, when someone submitted an empty value--is that not true?

**Comment by dangogh** [comment]
@mitchell852 -- I agree with @rob05c on this one -- removing "required" validation on value in the go code would take care of this.  The column in the db should be NOT NULL with a default of empty string.  This eliminates the need to distinguish between empty string and null in code.

**Comment by DylanVolz** [comment]
+1 After discussing with @dewrich I think the consensus is that the column should be NOT NULL as well due to how parameters are used to generate config files.

**Comment by chadgilloth** [comment]
@DylanVolz - Requested changes compete. db migration removed and nil value is changed to empty string before create and update queries.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2315/
Test PASSed.

**Pull request merged**
