### PR TITLE
Fix code that checks the use_tenancy parameter

### LINKED ISSUE #2695: TO Go remove `use_tenancy` code
`use_tenancy` is now on by default.   We can simplify quite a bit of code including sql by no longer checking this parameter.

NOTE:  the Perl code should not be touched except where it gets the value of that parameter (always assume 1);  only Go code should be cleaned up.

### PR DESCRIPTION
**Pull request by rawlinp**
Tenancy is always enabled, so we no longer have to check the use_tenancy
parameter. This should allow us to delete the use_tenancy parameter now (can do in a follow-up PR that also fixes the patches.sql + seeds.sql).

#### What does this PR do?

Fixes #2695

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Run the TO API integration tests and TO unit tests.

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3191/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3523/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3524/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3529/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3534/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3535/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3537/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3540/
Test PASSed.

**Comment by rawlinp** [comment]
I've added a bunch of tenancy tests to the users, delivery services, and origins API tests around attempting CRUD outside of your tenant, so I've removed the `wip` label now.

**Pull request merged**
