### PR TITLE
properly handle missing listen field in cdn.conf fixes #1590

### LINKED ISSUE #1590: Traffic Ops Golang Panics if Listen Config is Missing
Traffic Ops Golang should print or log an error if the config is invalid, rather than panicing.

Issue is here:
https://github.com/apache/incubator-trafficcontrol/blob/317a82a522ee75e870a22267e4c6bad6fabd9e27/traffic_ops/traffic_ops_golang/config.go#L214

### PR DESCRIPTION
**Pull request by DylanVolz**
fixes #1590

### CODE REVIEW

**Comment by DylanVolz** [comment]
retest please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2129/
Test PASSed.

**Comment by dewrich** [comment]
@DylanVolz To test, I manually removed the "listen" section from the cdn.conf and I'm seeing this error:

```panic: runtime error: index out of range

goroutine 1 [running]:
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/config.ParseConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202306b0, 0x4, ...)
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/config/config.go:259 +0x7d7
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/config.LoadConfig(0x7ffeefbfe49a, 0x19, 0x7ffeefbfe4bb, 0x23, 0x0, 0x0, 0x15d63c5, 0xb, 0x0, 0x0, ...)
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/config/config.go:167 +0x817
main.main()
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/traffic_ops_golang.go:65 +0x234
```

**Comment by dewrich** [comment]
@DylanVolz please add double quotes around the key in error for clarity

**Pull request merged**
