### PR TITLE
Multi delivery services with same domain name and different path prefixes

### PR DESCRIPTION
**Pull request by jifyang**
For the issue #TC-55.

### CODE REVIEW

**Comment by dneuman64** [comment]
Hey @jifyang, the PR has conflicts, can you please rebase?

**Comment by jifyang** [comment]
Done. Thanks!

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/35/

**Comment by dneuman64** [comment]
Unfortunately I am going to close this PR.  It is really old and most of the files that are changed in this PR have been re-written in go. If you feel that this functionality is still desired please port it to go and submit a new PR.

**Pull request closed without merging**
