### PR TITLE
show / hide TP views based on a users capabilities

### LINKED ISSUE #2039: Show/hide UI views based on capabilities
Currently, in TP all views are displayed regardless of role. However, role is enforced when trying to access each view. This can result in an unpleasant user experience.

Once capabilities are used as the mechanism for authorizing user access, TP should use the capabilities of the user to show/hide relevant UI views.

### PR DESCRIPTION
**Pull request by mitchell852**
fixes #2039

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1886/
Test PASSed.

**Comment by mitchell852** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2207/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2223/
Test PASSed.

**Pull request merged**
