### PR TITLE
Disallow updating regexes that have set number 0 and type HOST_REGEXP

### LINKED ISSUE #2805: Traffic Ops Does Not Update DNSSEC Keys on Delivery Service Update
Traffic Ops Does Not Update DNSSEC Keys on Delivery Service Update.

As far as I can tell, this has been a bug forever. The old Perl endpoint doesn't update them either, and it appears it never has.

This means updating anything in a DS which changes the served FQDNs (e.g. Routing Name, Regexes) will break DNSSEC.

### LINKED ISSUE #5296: Cannot update any regex in Traffic Ops/ Traffic Portal
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Ops

## Current behavior:

If you have a regex for a delivery service, you cannot update it.
## Expected behavior:

All regexes should be updateable, with the exception of the following:
1.) If the regex in question has set number `0` and type `HOST_REGEXP`
2.) If there already is another regex with the same order.

## Minimal reproduction of the problem with instructions:

Go to Traffic Portal.
In an existing or new delivery service, try changing the pattern of a regex thats associated with this DS.
You'll notice that it fails stating that there already is another regex with the same order.
This is incorrect, because "updating" something means that it has to be already available.

### PR DESCRIPTION
**Pull request by srijeet0406**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5296 and potentialy #2805   

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Ops

## What is the best way to verify this PR?

Make sure all the unit/ API tests pass
Go to Traffic Portal
Try modifying a regex for any DS
This should be possible as long as the following two conditions are met:
1.) The regex in question does not have set number `0` and type `HOST_REGEXP`
2.) No other regex exists with the set number that you're trying to update the current regex to
## If this is a bug fix, what versions of Traffic Control are affected?

- master

## The following criteria are ALL met by this PR

- [x] This PR includes tests 
- [x] I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by mitchell852** [comment]
fyi the text needs to look like this:

```
This PR fixes #2805 and fixes #5296
```

to autoclose both tickets.

**Review by mitchell852 — CHANGES_REQUESTED** [review]
I found a bug. I was able to change the regex type of the position 0 regex from HOST_REGEXP to:

image

**Comment by srijeet0406** [comment]
@mitchell852 Fixed in the latest commit

**Review by mitchell852 — APPROVED** [review]
LGTM!

**Pull request merged**
