### PR TITLE
Update the Python TO client to API 3.0

### PR DESCRIPTION
**Pull request by rawlinp**
## What does this PR (Pull Request) do?
Update the Python TO client to API 3.0. Also, fix up the topologies methods.

## Which Traffic Control components are affected by this PR?
- Traffic Control Client (Python)

## What is the best way to verify this PR?
Write a script that uses the python TO client (or use it interactively). Make requests using the various methods, verify they work successfully.

## The following criteria are ALL met by this PR
- [x] python TO client doesn't have tests
- [x] no docs necessary
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by ocket8888 — APPROVED** [review]
LGTM

**Comment by rawlinp** [comment]
Something seems up w/ the CiaB origin/ats possibly. The logs show successful 302 but then ats returns 502.

**Comment by ocket8888** [comment]
Yeah, I was just running it locally to see if I can find the problem

**Comment by ocket8888** [comment]
Found it. Line 49 in `infrastructure/cdn-in-a-box/ort/traffic_ops_ort/to_api.py`. It's setting the ORT API version to 2.0, but if the client only supports 3.0 then that needs to get updated.

**Comment by rawlinp** [comment]
Ah, I think I know the issue. Python ORT is setting the version to 2.0, which is likely causing an exception since 2.0 is "not supported".

**Comment by rawlinp** [comment]
JINX 1, 2, 3!

**Pull request merged**
