### PR TITLE
Fixed unreachable code on logout_test.go and plugin_verifier.go

### LINKED ISSUE #5766: `go vet`: unreachable code
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Ops ORT

## Current behavior:

`go vet -unreachable ./...` finds 2 issues:

<table><thead><th>Message</th><th>Line of code</th></thead><tbody>

<tr><td><code>unreachable code</code></td><td>

https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/traffic_ops_ort/plugin_verifier/plugin_verifier.go#L261
https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/traffic_ops/traffic_ops_golang/login/logout_test.go#L135
</td></tr>
</tbody></table>

## Expected behavior:

`go vet -unreachable ./...` should find 0 issues.

## Minimal reproduction of the problem with instructions:

```shell
go vet -unreachable ./...
```

### PR DESCRIPTION
**Pull request by Ayushsunny**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5766  

## Which Traffic Control components are affected by this PR?

- Traffic Ops
- Traffic Ops ORT

## What is the best way to verify this PR?

`go vet -unreachable ./...` should find 0 issues.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by zrhoffman — APPROVED** [review]
Fixes to *unreachable code* make sense and `go vet -unreachable ./...` succeeds.

Thanks for your contribution!

(Will merge once the CI passes)

**Review by zrhoffman — CHANGES_REQUESTED** [review]
Everything you've done so far is correct, but your fix has uncovered a bug in `login.TestLogout()`.

These 2 strings (`"test"` and `"secret"`) should instead be the same string:
https://github.com/apache/trafficcontrol/blob/55dbb7eacd399d3ccef9d4eb34bfaeb0c5e2e7ad/traffic_ops/traffic_ops_golang/login/logout_test.go#L103
https://github.com/apache/trafficcontrol/blob/55dbb7eacd399d3ccef9d4eb34bfaeb0c5e2e7ad/traffic_ops/traffic_ops_golang/login/logout_test.go#L135

Once they are the same string, the test should pass.

**Comment by Ayushsunny** [comment]
> Everything you've done so far is correct, but your fix has uncovered a bug in `login.TestLogout()`.
> 
> These 2 strings (`"test"` and `"secret"`) should instead be the same string:
> 
> https://github.com/apache/trafficcontrol/blob/55dbb7eacd399d3ccef9d4eb34bfaeb0c5e2e7ad/traffic_ops/traffic_ops_golang/login/logout_test.go#L103
> 
> https://github.com/apache/trafficcontrol/blob/55dbb7eacd399d3ccef9d4eb34bfaeb0c5e2e7ad/traffic_ops/traffic_ops_golang/login/logout_test.go#L135
> 
> Once they are the same string, the test should pass.

Thank you @zrhoffman.
I have amend the changes.

**Review by zrhoffman — APPROVED** [review]
All looks good. Thanks again!

**Comment by Ayushsunny** [comment]
Hello @zrhoffman Is there any other issue present that I can work on as a beginner?

**Comment by zrhoffman** [comment]
Any interest in #5762?

**Pull request merged**
