### PR TITLE
Fixed a Python2 compatibility issue in the Traffic Control client

### LINKED ISSUE #3112: Python TO Client breaks with python 2.7
The client is supposed to work with python 2.7 and 3.6, but I've come across this syntax error using 2.7:
```
...
from trafficops.tosession import *   File "/.../traffic_control/clients/python/trafficops/trafficops/tosession.py", line 211     raise
restapi.LoginError(msg) from e  
   ^ SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR do?
Fixes #3112 

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Traffic Ops python client

## What is the best way to verify this PR?
Try to use the Python client in Python 2.7

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by dangogh** [comment]
can you change the commit comment "Fixed #3112" to something that describes the change?  That doesn't mean anything without going back to github to see the PR comments.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2947/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2948/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2949/
Test PASSed.

**Pull request merged**
