### PR TITLE
Add TO Go users/id/deliveryservices

### PR DESCRIPTION
**Pull request by rob05c**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1700/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1702/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1764/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1804/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1930/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1936/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1974/
Test FAILed.

**Comment by dewrich** [comment]
API Tests are broken: ```Dewayne Richardson [4:09 PM]
2339 the API tests are broken

```DEBUG: userdeliveryservices_test.go:33: 2018-07-02T16:09:12.882921-06:00: CreateTestDeliveryServices
DEBUG: userdeliveryservices_test.go:35: 2018-07-02T16:09:12.9655-06:00: CreateTestUsersDeliveryServices
--- FAIL: TestUsersDeliveryServices (0.85s)
    userdeliveryservices_test.go:65: cannot GET users: json: cannot unmarshal string into Go struct field User.id of type int
FAIL
exit status 1
FAIL    github.com/apache/trafficcontrol/traffic_ops/testing/api/v13    1.038s``````

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1996/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2004/
Test PASSed.

**Pull request merged**
