### PR TITLE
Add TO Go regions/name

### PR DESCRIPTION
**Pull request by rob05c**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1728/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1803/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1938/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1939/
Test PASSed.

**Comment by dewrich** [comment]
@rob05c Doesn't compile either due to package changes: ```rob05c-to-go-regions-name-2353 ᐅ go build && ./traffic_ops_golang -cfg ~/cdn.conf -dbcfg ~/database-traffic_ops.conf
region/name.go:27:2: cannot find package "github.com/apache/incubator-trafficcontrol/lib/go-tc" in any of:
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/vendor/github.com/apache/incubator-trafficcontrol/lib/go-tc (vendor tree)
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/vendor/github.com/apache/incubator-trafficcontrol/lib/go-tc
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/vendor/github.com/apache/incubator-trafficcontrol/lib/go-tc
	/usr/local/Cellar/go@1.9/1.9.7/libexec/src/github.com/apache/incubator-trafficcontrol/lib/go-tc (from $GOROOT)
	/Users/dricha209/projects/go/src/github.com/apache/incubator-trafficcontrol/lib/go-tc (from $GOPATH)
region/name.go:28:2: cannot find package "github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api" in any of:
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/vendor/github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api (vendor tree)
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/traffic_ops/vendor/github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api
	/Users/dricha209/projects/go/src/github.com/apache/trafficcontrol/vendor/github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api
	/usr/local/Cellar/go@1.9/1.9.7/libexec/src/github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api (from $GOROOT)
	/Users/dricha209/projects/go/src/github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang/api (from $GOPATH)
```

**Comment by rob05c** [comment]
@dewrich Fixed

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1994/
Test PASSed.

**Pull request merged**
