### PR TITLE
Fix TO ats config meta to accept names

### LINKED ISSUE #3673: TO API test failure with atsconfig_test.go
`--- FAIL: TestATSConfigs (14.11s) atsconfig_test.go:50: Getting server by name 'atlanta-edge-01' config list: 400 Bad Request[400] - Error requesting Traffic Ops https://localhost:8443/api/1.4/servers/atlanta-edge-01/configfiles/ats {"alerts":[{"text":"getting integer parameters: parameter 'id' not an integer","level":"error"}]}`

This appears to be related to #3516

### PR DESCRIPTION
**Pull request by rob05c**
Fixes #3673

## What does this PR (Pull Request) do?

- [x] This PR fixes #3673 OR is not related to any Issue

Tests exist, this fixes them.
No documentation, no interface change.
No changelog, issue was introduced after prior release.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Request /api/1.2/servers/<hostname>/configfiles/ats, verify 200 and correct config.

Run TO API tests.

## If this is a bug fix, what versions of Traffic Ops are affected?

- master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3857/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3858/
Test PASSed.

**Comment by Shihta** [comment]
tested in both CIAB and my personal environment, seems good!

**Comment by ocket8888** [comment]
> _"tested in both CIAB and my personal environment, seems good!"_

You can submit an approving Review by clicking on Files changed &rarr; Review Changes &rarr; Approve &rarr; Submit Review

**Comment by Shihta** [comment]
@ocket8888 @dangogh 
if there is no other special comment, can I merge this PR directly?

**Comment by dangogh** [comment]
@Shihta   Once you have verified that:
- it has fixed the problem
- introduces no other problem
- tested appropriately
- requires no copyright or documentation changes

then yes,  please do merge.   And since you are the one who has done all that,  I want to make sure you get credit for merging  in the git history.

**Pull request merged**
