### PR TITLE
Query servers by topology

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR is not related to any Issue 
- This PR lets you query servers by topology, meaning querying servers whose cachegroups belong to a given topology.

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops
- Traffic Portal

## What is the best way to verify this PR?

Run the Traffic Ops API tests, which includes a test for the `topology` query parameter on GET `/api/3.0/servers`

In TP, create a topology, add cache groups, save. Then on the topology page under `More` you'll see `View Servers`. This will show you all the servers associated with the topology.

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
@zrhoffman this PR has merge conflicts

**Comment by zrhoffman** [comment]
Conflict is in `traffic_portal/app/src/common/modules/form/topology/form.topology.tpl.html`, @mitchell852 has been working on rebasing I believe

**Comment by zrhoffman** [comment]
Merge conflicts fixed. Thanks @mitchell852!

**Review by rawlinp — APPROVED** [review]
LGTM, appears to work like a charm

**Pull request merged**
