### PR TITLE
Make pkg.ps1 compatible with PowerShell Core (OSS version)

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

This PR adds a shebang to `pkg.ps1`, makes it executable, and separates each argument of the Docker commands with spaces only (no commas).

From my testing, it runs successfully on Mac and Linux using PowerShell Core version 6.2.4 and on Windows using PowerShell version 5.1.19546.1000.

We don't have PowerShell integration tests. Also, because we don't officially support development on Windows (see #3767), the documentation is unchanged.

- [x] This PR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Packaging scripts

## What is the best way to verify this PR?

* Run pkg.ps1 on Windows, verify RPMs are generated
* Run pkg.ps1 on Mac, verify RPMs are generated
* Run pkg.ps1 on Linux, verify RPMs are generated

## If this is a bug fix, what versions of Traffic Control are affected?

- master (626fb05932)

## The following criteria are ALL met by this PR

- [x] I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
I was looking into this, but neither this version nor the script in master are capable of generating RPMs for me.

**Comment by zrhoffman** [comment]
On which platform does it not generate RPMs for you? I just ran it on Linux and got RPMs.

**Comment by ocket8888** [comment]
Windows 10

**Comment by zrhoffman** [comment]
Ran on Windows 10 with Docker Desktop 2.2.0.3, got all expected RPMs. I am actually only building traffic ops:
```powershell
.\pkg.ps1 traffic_ops_build
```

Does `build-*.log` have any errors?

**Comment by ocket8888** [comment]
`build-*.log` files are not output. The only one that works is `weasel` which outputs as expected (no errors). I swear I had this working when I opened the original PR...

I have Docker Desktop 2.2.0.3 with Powershell version 5.1.17763-771 and (virtually) every build fails with:
```pwsh
PS D:\golang\src\github.com\apache\trafficcontrol> .\pkg.ps1 traffic_ops_build                                          Building traffic_ops_build                                                                                              Building traffic_ops_build                                                                                              D:\golang\src\github.com\apache\trafficcontrol\pkg.ps1 : Failed to execute traffic_ops_build                            At line:1 char:1                                                                                                        + .\pkg.ps1 traffic_ops_build                                                                                           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                               + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,pkg.ps1 
```

**Comment by zrhoffman** [comment]
I wonder if trying in a freshly-cloned repo or running as admin would make Windows's wacky permissions errors go away.

I don't know if it's relevant, but all of my Windows 10 testing is on Insider build 19546.1000 (January 16). The RPMs build both without and with Docker Desktop's experimental WSL 2 based engine, so I wouldn't think that is a factor.

**Comment by zrhoffman** [comment]
Looking into it, Brennan found that the `.git` directory isn't copied to the temp build directory when the rest of the repo is. Fixed in 6d2b6fc18, please retest.

**Pull request merged**
