### PR TITLE
Add TO Go cdns/name/dnsseckeys

### PR DESCRIPTION
**Pull request by rob05c**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1649/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1756/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2044/
Test PASSed.

**Comment by ocket8888** [comment]
This endpoint has already been rewritten to go, so I think this PR should be closed.

**Comment by rawlinp** [comment]
Yes, this endpoint has been rewritten.

**Pull request closed without merging**
