### PR TITLE
[TC-115] make sure ats config files are owned by ats.ats

### PR DESCRIPTION
**Pull request by weifensh**
make sure ats config files are owned by ats.ats, which makes the config files be more friendly to ATS. This is because if the owner of a config file is not ats.ats, ATS sometimes does not reload the config while receiving a "traffic_line -x".

Issue at https://issues.apache.org/jira/browse/TC-115

### CODE REVIEW

**Comment by weifensh** [comment]
@dg4prez Thanks for the comments, revised accordingly.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/43/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/32/

**Comment by hbeatty** [comment]
GH issue #1015

**Comment by dg4prez** [comment]
It looks like you're only filtering out cron files.  That's a little specific - can you filter out anything not in the /opt/trafficserver directory?

**Comment by weifensh** [comment]
@dg4prez revised accordingly, please help to check, thanks.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/561/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/517/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/828/
Test PASSed.

**Comment by weifensh** [comment]
@smalenfant revised accordingly.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/829/
Test PASSed.

**Comment by ocket8888** [comment]
I believe this has already been implemented [in traffic_ops_ort.pl](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/bin/traffic_ops_ort.pl#L1528-L1534) - though the difference seems to be that this PR would make *all* files that don't fall under `/opt/trafficserver` owned by root whereas currently only those files with `/cron/` in the pathname will be made owned by root and everything *else* is owned by ATS.

If the current implementation is acceptable, please close this PR.

**Pull request closed without merging**
