### PR TITLE
[TC-262] Allow specification of the 'id' parameter for storage.config

### PR DESCRIPTION
**Pull request by jschmerge**
This patch adds three new parameters to control/configure the seed
strings for the consistent hash used for cachekey->drive mapping in
ATS... This allows an arbitrary string to be assigned as the key for
drives instead of relying on the OS's device node name as the seed for
the hash. The three parameters added are:
 * Drive_Hash_Id
 * RAM_Drive_Hash_Id
 * SSD_Drive_Hash_Id
And they specify the id keys for spinning, ram, and ssd devices.

If this parameter is missing from the TO config for a server, the
generated file ommits any specification of the id parameter (preserving
the previous file generation behavior).

Also note that the csv id strings for these three new parameters should
order their entries to match the order of the Drive_Letters parameter.

### CODE REVIEW

**Comment by dg4prez** [comment]
I'm seeing a few issues here, like lack of declaration for @tmp_list, and trying to use @postfix in a different sub than where it was declared without passing it.  I'm not sure what ($$) is either but that could be a lack of knowledge on my part - I just know it refuses to run with that in place.

**Comment by dg4prez** [comment]
Tested with the changes.  Works as designed.  Please merge with PR 527 for the API to match.

**Comment by mitchell852** [comment]
@jschmerge - can you create a jira ticket for this? https://issues.apache.org/jira/browse/TC

**Comment by limited** [comment]
What values would one typically set for the  *_Hash_Id? Does it need to correspond to a property of the disks?

**Comment by oren-shemesh** [comment]
Indeed, an entry in the documentation explaining the purpose and usage of these parameters would be in place.

**Comment by jschmerge** [comment]
The parameter is actually rather nicely documented with examples in the ATS documentation: https://docs.trafficserver.apache.org/en/latest/admin-guide/files/storage.config.en.html#linux-example

This patch just exposes the configuration item as a knob in traffic-ops.

**Comment by limited** [comment]
I understand the ATS storage.config parameter, but how is this ID configured/generated in Traffic Ops? Is there a per-disk ID parameter (i.e. if i have 72 disks there are now 72 new parameters)?

I looked at the referenced PR but it didnt seem to contain API changes

**Comment by jschmerge** [comment]
I thought i had left a comment regarding this patch a few weeks back answering the question @limited posed...

I'm going to focus on just the Drive_Letters and Drive_Hash_Id params, the RAM_* and SSD_* work the same way.

The Drive_Hash_Id param takes a CSV string for *_all_* the drives, and the order is expected to match the order in the Drive_Letters CSV string. Provisions have been taken to allow for omitting a hash id for a drive, in that if:

Drive_Letters = "a,b,c,d,e"

and

Drive_Hash_Id = ",,foo,,bar"

You'll end up with a storage.config that contains:

`/dev/sda volume=1
/dev/sdb volume=1
/dev/sdc volume=1 id=foo
/dev/sdd volume=1
/dev/sde volume=1 id=bar`

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/27/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1116/
Test FAILed.

**Comment by anna-k-1** [comment]
@jschmerge Is this PR still valid? If you still need this feature, please comment and let us know.

**Comment by mitchell852** [comment]
closing. please reopen if still relevant.

**Pull request closed without merging**
