### PR TITLE
updated the Traffic Router docker compose file

### PR DESCRIPTION
**Pull request by dewrich**
Now creates a host volume for the .m2 directory to improve build performance

### CODE REVIEW

**Comment by dangogh** [comment]
@rawlinp made a previous change to the other volume there:  add a `:z` to allow selinux-enabled hosts to recognize the volume as one that can be modified -- I think you need that here, too.  Shouldn't affect anything else.

**Comment by dewrich** [comment]
@dangogh I forgot to put that back because I ran into an error that was something else, so I wasn't sure what the `:z` was for

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1668/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1669/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1673/
Test PASSed.

**Pull request merged**
