### PR TITLE
Should use "dest_ip" instead of "dest_domain" in "parent.config" and …

### PR DESCRIPTION
**Pull request by jifyang**
…"cache.config" when ofqdn is ip

Fix the issue #TC-85.

### CODE REVIEW

**Comment by dg4prez** [comment]
Can you explain the purpose of this?  I'm not sure what this is needed for.

**Comment by jifyang** [comment]
According to the document of Apache Traffic Server,
https://docs.trafficserver.apache.org/en/5.3.x/reference/configuration/parent.config.en.html,
"dest_ip" is used for IP address.

It's bette to be compliant with the specification to avoid potential problem.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/33/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/73/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/113/

**Comment by hbeatty** [comment]
GH issue #890

**Comment by limited** [comment]
@jifyang Hey Jifeng-
  Can you please make same changes to ApacheTrafficServer.pm 

Also can you please add a unit test case for this?

**Comment by rawlinp** [comment]
This PR addresses issue #890.

**Comment by dneuman64** [comment]
Is this something you would still like to see merged into the project?  If so, then please fix the merge conflicts and work with one of the committers [1] to get this PR merged.  If not, then please close the PR.  

[1] https://projects.apache.org/committee.html?trafficcontrol

**Pull request closed without merging**
