### PR TITLE
TP: adds the ability to rearrange delivery service table columns as well as toggle column visibility/searchability

### PR DESCRIPTION
**Pull request by mitchell852**
NOTE: #3680 needs to be merged before this one.

## What does this PR (Pull Request) do?

- [x] This PR is not related to any Issue

This PR adds checkboxes to toggle the visiblity/searchability of ds table columns as well as adds the ability to reorder the columns.

image

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Navigate to https://tp.doman.com/#!/delivery-services and
1. reorder the columns; refresh the screen to ensure that the new order persists itself across browser sessions.
2. click on the drop down to toggle the visiblity/searchability of columns; refresh the screen to ensure that the selected columns are visible/hidden across browser sessions. also, ensure that values in hidden columns are not considered in the table search.

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [ ] This PR includes any and all required license headers
- [ ] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [ ] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3970/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3979/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3980/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3981/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3983/
Test PASSed.

**Comment by mitchell852** [comment]
closing this in favor of #3739 as i was having difficulties with git conflicts.

**Pull request closed without merging**
