### PR TITLE
Rename tsb directory to _tsb to have `go` ignore it

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

As @jhg03a mentioned in #5635, the sources that *tsb* leaves behind after building Traffic Server causes Go components to fail to build. This PR renames the *tsb* directory to *_tsb* so that `go` will ignore it.

- [x] This PR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Server

## What is the best way to verify this PR?

1. Build Traffic Server:
  ```shell
  ./pkg -o -v ats
  ```
2 Make sure you can still vendor dependencies:
  ```shell
  go mod vendor -v
  ```

## If this is a bug fix, what versions of Traffic Control are affected?

- master (c52ba7baf4)

## The following criteria are ALL met by this PR

- [x] Building components is sufficient to test
- [x] Intended behavior is unchanged, documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by jhg03a** [comment]
This fails to build with the error:
```
Step 16/16 : CMD	["/usr/bin/tsb", "cd", "/opt/tsb-ats", "fetch", "prebuild"]
 ---> Running in 443820f2385f
Removing intermediate container 443820f2385f
 ---> 530598fda0ac

Successfully built 530598fda0ac
Successfully tagged build_ats:latest
WARNING: Image for service ats was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating build_ats_run ... done
Failed to run command: git --git-dir=/opt/tsb-ats/src/openssl/.git --work-tree=/opt/tsb-ats/src/openssl remote
exit status 128
fatal: Not a git repository: '/opt/tsb-ats/src/openssl/.git'
```

**Review by jhg03a — CHANGES_REQUESTED** [review]
Fails to build

**Comment by jhg03a** [comment]
I'm testing on a linux host as follows:
```
(docker ps -qa | xargs docker rm -f; docker image list -qa | xargs docker image rm -f; docker system prune -a -f --volumes) && ./pkg -v -7 traffic_monitor_build && ./pkg -v -7 -o ats && ./pkg -v -7 traffic_monitor_build && ./pkg -v -8 -o ats && ./pkg -v -8 traffic_monitor_build
```

**Comment by jhg03a** [comment]
Also, please merge #5624 before this to make life easier.

**Comment by zrhoffman** [comment]
> I'm testing on a linux host as follows:
> 
> ```
> sudo rm -rf traffic_server/tsb; (docker ps -qa | xargs docker rm -f; docker image list -qa | xargs docker image rm -f; docker system prune -a -f --volumes); ./pkg -v -7 traffic_monitor_build && ./pkg -v -7 -o ats && ./pkg -v -7 traffic_monitor_build && ./pkg -v -8 -o ats && ./pkg -v -8 traffic_monitor_build
> ```
> 
> sudo is required here most likely because the tsb src directory is owned by another user.

This all succeeds for me. Would you please include logs for whatever failed?

**Review by jhg03a — APPROVED** [review]
After doing a `sudo git clean -xfd`, it's building now.

**Pull request merged**
