### PR TITLE
CIAB: Dynamically choose the first mid server

### PR DESCRIPTION
**Pull request by bakerolls**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

This PR would enable renaming the default Mid Server by removing the hard coded name `CDN_in_a_Box_Mid`. It now calls the API until a cachegroup exists. If there are more than one cachegroups, the first is selected.

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] CDN in a Box

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

Change the `name` in [060-ciabMid.json](infrastructure/cdn-in-a-box/traffic_ops_data/cachegroups/060-ciabMid.json), `parentCachegroupName` in [070-ciabEdge.json](infrastructure/cdn-in-a-box/traffic_ops_data/cachegroups/070-ciabEdge.json) and start CIAB. The default Mid server should have the new name.

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by bakerolls** [comment]
After #3413 gets merged, `$CDN` has to be renamed to `$CDN_NAME `.

**Comment by Shihta** [comment]
mid server should use `MID_LOC` cachegroup so you can not randomly choose one.

**Comment by ocket8888** [comment]
I agree with @Shihta , I don't think assigning the mid server to the cache group of the first server randomly enrolled/returned by the API is a good idea.

**Comment by bakerolls** [comment]
Sorry, I honestly did not check the full response of `/api/1.3/servers`. Do you think a random mid server would be sufficient? If yes, we could just add `?type=MID`. If no, should the default be defined inside `variables.env`?

**Comment by ocket8888** [comment]
That won't work at all. Before the mid the server is enrolled, you shouldn't be able to find a mid server, so it'll just loop endlessly.

**Comment by Shihta** [comment]
For me, I would like adding a parameter rather than random choice.
Even you specified the type, directly picking the first one is still a random selection method.
If you want to reuse the same mid container for larger system (more than 1 mid server/cachegroup), uncontrollable random selection method should not be a good idea.

**Comment by bakerolls** [comment]
It worked once, but there were probably some volumes not removed or containers still running. In the end, I used a variable that defined the name. Thank you for your comments.

**Pull request closed without merging**
