### PR TITLE
For cdn-in-a-box add optional loading of a pg_dump.

### PR DESCRIPTION
**Pull request by jrushford**
An update to optionally load a pg_dump file when the to database is created.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2101/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2102/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2103/
Test PASSed.

**Comment by dangogh** [comment]
nice idea..   I'd like to modify it a bit, though, to make it a little more flexible, e.g. if it's a `.dump` file, use `pg_restore`; for `.sql`,  use `psql`,  etc.

**Comment by dangogh** [comment]
see #2612 -- covers this capability more generally

**Comment by dangogh** [comment]
this is handled automatically now by adding a .dump file to the `traffic_ops/initdb.d` directory.

**Pull request closed without merging**
