### PR TITLE
TrafficMonitor IPV6 improvements

### LINKED ISSUE #2735: Traffic Monitor Polling over ipv6
Currently, Traffic Monitor only polls caches over IPv4, this can lead to issues if a DS is ipv6 enabled and the ipv6 interface is down on a cache.  Traffic Monitor should be modified such that it can poll on the necessary interfaces and report status based on the interfaces. Ideally this would be a config that can be set to tell TM to monitor IPv4, Ipv6 or both and make health determinations based on those configs.

### PR DESCRIPTION
**Pull request by serDrem**
Enables TM to poll health information over IPV6, and optionally combine it with IPV4 information for traffic router.

fixes #2735

### CODE REVIEW

**Comment by alficles** [comment]
This is pretty cool. It looks like there are two separate PRs in here, and the second one could really use a squash. The astats changes can stand on their own, so they should probably get their own PR. And the IPv6 for TM should be squashed. There are some confusing reverts of inadvertent changes that probably shouldn't go in, even as intermediate changesets.

It'll be a lot easier to review it that way, I think.

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dneuman64** [comment]
+1 to @alficles comments.  @serDrem can you please make this two PRs?  One for astats and one for TM?

**Comment by dneuman64** [comment]
This should also be linked to this issue: https://issues.apache.org/jira/browse/TC-230

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/18/

**Comment by serDrem** [comment]
been absorbed by another PR.

**Pull request closed without merging**
