### PR TITLE
Add documentation generation to pkg

### PR DESCRIPTION
**Pull request by jhg03a**
#2463.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
add to whitelist

**Comment by jhg03a** [comment]
ok to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1912/
Test PASSed.

**Comment by jhg03a** [comment]
Observe that the ASF Jenkins build artifacts now include a build_docs.log & docs tarball.

**Pull request merged**
