### PR TITLE
Fix TO Go API PUT/POST type checking

### LINKED ISSUE #2560: TO Go cachegroups, DS regexes, and staticdnsentries don't validate their type
These TO Go endpoints do not validate that the requested `type` is actually a usable type for that endpoint. Right now you can create a cachegroup of type `A_RECORD`, a staticdnsentry of type `HOST_REGEXP`, and so on.

Since there are several different entities that use the `type` table, I'd propose handling this in the shared handlers alongside the call to `foo.Validate()`. We can create an interface like the following that the affected structs can implement:
```
type RequiredTyper interface {
    RequiredType() (*int, string)
}
```
with implementations that just return their *TypeID and string value of the `use_in_table` they expect of their type. If the type is missing, not found, or incorrect, the shared handler would return a `400 Bad Request`.

Entities that don't use the shared handlers could import the same code that the shared handler would use to do the validation.

EDIT: title originally said the servers endpoints were affected, but in fact they are not. However, they can benefit from a unified approach.

### PR DESCRIPTION
**Pull request by rawlinp**
For entities that have a required type from the type table, validate
the type.

Fix the DS regex PUT/POST handlers to use transactions and some of the
shared api.NewInfo functionality.

Fixes #2560

### CODE REVIEW

**Comment by rawlinp** [comment]
I opened this for review but still need to do more testing before clearing this to merge.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2132/
Test PASSed.

**Comment by rawlinp** [comment]
Local integration testing and the API integration tests all pass, but the cachegroup and staticdnsentry unit tests need to be fixed up to mock out the DB transaction which is now used in their validation.

**Comment by rawlinp** [comment]
Unit tests have been fixed up and pass, so this is no longer WIP.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2139/
Test PASSed.

**Pull request merged**
