### PR TITLE
Wrong error code when requesting cdn ats configfile with bad ds id

### LINKED ISSUE #4128: TO: Internal Server Error when filename in the request path param doesn't exist
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

```http
GET /api/{{api_version}}/cdns/Kabletown2.0/configfiles/ats/hdr_rw_.*.config HTTP/1.1
Content-Length: 0
```
returns
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

404 if the file doesn't exist

### PR DESCRIPTION
**Pull request by mhoppa**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4128 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Request a cdn ats configfile with an invalid ds id and you should now get a 404 back 

## If this is a bug fix, what versions of Traffic Control are affected?

-master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rob05c** [comment]
I agree, this is the right response code. But, it's currently serving a 500, and so does Perl.

Would you mind if we held off on this, until we've been running the Config Generator for a little bit and are sure it's all working as expected?

I've been trying to avoid changes from the Perl as much as possible, just for safety. The config gen is so much code, there's so much to go wrong. In theory, ORT shouldn't be requesting configs that don't exist. But it makes me anxious to make any change in behavior, until we've had this 20k lines of code running for a while.

Again, I'm +1 on merging this in; I'd just like to wait on behavioral changes, until we've been running it and have confidence in it.

**Comment by mhoppa** [comment]
Good with me! @rob05c  can you put WIP tag on it or DO NOT MERGE if there is one

**Comment by ocket8888** [comment]
No, he can't. Because I'm too fast.

**Comment by mitchell852** [comment]
closing as this endpoint has been deprecated

**Pull request closed without merging**
