### PR TITLE
Updates to the trafficcontrol-health-client

### PR DESCRIPTION
**Pull request by jrushford**
Updates to the trafficcontrol-health-client:

- Fixes a bug where a hosts UnavailablePollCount is not reset
  once the host is available.
- Fixes a bug in the RPM spec file that prevents the health-client
  from being restarted when it is updated.
- Logs the traffic control version on startup.

## Which Traffic Control components are affected by this PR?

- Traffic Control Health Client (tc-health-client)

## What is the best way to verify this PR?

Run the unit tests.

## If this is a bugfix, which Traffic Control versions contained the bug?

- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by jpappa200 — APPROVED** [review]
👍

**Review by jpappa200 — APPROVED** [review]
👍

**Comment by jpappa200** [comment]
LGTM

**Review by rob05c — APPROVED** [review]
LGTM, and I trust Joe's review

**Pull request merged**
