### PR TITLE
Fix enroller build issues

### LINKED ISSUE #6226: Error building Enroller in CiaB
## This Bug Report affects these Traffic Control components:

- CDN in a Box

## Current behavior:
When trying to build enroller in CiaB (with debugging), the following error occurs:
```
Err:24 http://deb.debian.org/debian buster/main amd64 linux-libc-dev amd64 4.19.181-1
  404  Not Found [IP: 151.101.70.132 80]
Get:25 http://deb.debian.org/debian buster/main amd64 libc6-dev amd64 2.28-10 [2691 kB]
Get:26 http://deb.debian.org/debian buster/main amd64 libstdc++-8-dev amd64 8.3.0-6 [1532 kB]
Fetched 32.2 MB in 2s (16.8 MB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/l/linux/linux-libc-dev_4.19.181-1_amd64.deb  404  Not Found [IP: 151.101.70.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
This appears to be because `libstdc++-8-dev` is no longer in the debian repo.

## Expected behavior:
Enroller should build without issue

## Steps to reproduce:
Occurs when running `docker-compose -f docker-compose.yml -f docker-compose.expose-ports.yml -f optional/docker-compose.debugging.yml -f docker-compose.readiness.yml build`

### PR DESCRIPTION
**Pull request by shamrickus**
This fixes #6226 
<hr>

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?
Run `docker-compose -f docker-compose.yml -f docker-compose.expose-ports.yml -f optional/docker-compose.debugging.yml -f docker-compose.readiness.yml build` and verify enroller build successfully.

## If this is a bugfix, which Traffic Control versions contained the bug?
- 5.1.x
- 6.x
- master 

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by zrhoffman — CHANGES_REQUESTED** [review]
> When trying to build enroller in CiaB (with debugging),

`enroller` is not the only service broken when you try to build for debugging. Other services broken:
* caches (`edge`, `mid-01`, `mid-01`)
* `trafficmonitor`
* `trafficops`
* `trafficstats`

For those other services, skipping updating `dlv`'s dependencies by changing
```shell
go get -u github.com/go-delve/delve/cmd/dlv
```
to
```shell
go get github.com/go-delve/delve/cmd/dlv
```
should work.

**Comment by shamrickus** [comment]
From my local testing, the `go get` change only needs to be in the `enroller`. Am I missing something?

**Comment by zrhoffman** [comment]
Maybe try building one of the services listed with `--no-cache`?

```shell
docker-compose -f docker-compose.yml -f optional/docker-compose.debugging.yml build --no-cache
```

Also, a new CentOS 8 Docker image was published 5 days ago. I wouldn't think that that's the issue since I reproduce it with CentOS 7 base images too, but if you want, you could try downloading a new `centos:8` image (which removes the need for `--no-cache` to reproduce)

**Comment by zrhoffman** [comment]
Running the above command, building `enroller` fails for me:

```
#21 [get-delve 1/1] RUN go get -u github.com/go-delve/delve/cmd/dlv
#21 sha256:7fb07becfeefe03127939184b89111ced4bf2bf8cba033ce13d76785fc290bec
#21 6.307 go: downloading github.com/mattn/go-runewidth v0.0.3
#21 6.427 go: downloading github.com/mattn/go-runewidth v0.0.13
#21 6.538 go: downloading github.com/rivo/uniseg v0.2.0
#21 6.678 go get: installing executables with 'go get' in module mode is deprecated.
#21 6.678 	Use 'go install pkg@version' instead.
#21 6.678 	For more information, see https://golang.org/doc/go-get-install-deprecation
#21 6.678 	or run 'go help get' or 'go help install'.
#21 8.888 # github.com/go-delve/delve/service/dap
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:222:36: non-integer slice index "stopOnEntry"
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:222:51: invalid type assertion: request.GetArguments()["stopOnEntry"].(bool) (non-interface type byte on left)
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:226:37: non-integer slice index "stackTraceDepth"
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:226:56: invalid type assertion: request.GetArguments()["stackTraceDepth"].(float64) (non-interface type byte on left)
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:230:39: non-integer slice index "showGlobalVariables"
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:230:62: invalid type assertion: request.GetArguments()["showGlobalVariables"].(bool) (non-interface type byte on left)
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:234:12: assignment mismatch: 2 variables but 1 value
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:234:37: non-integer slice index "substitutePath"
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:770:11: assignment mismatch: 2 variables but 1 value
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:770:31: non-integer slice index "mode"
#21 8.888 go/pkg/mod/github.com/go-delve/delve@v1.7.1/service/dap/server.go:770:11: too many errors
#21 ERROR: executor failed running [/bin/sh -c go get -u github.com/go-delve/delve/cmd/dlv]: exit code: 2
```

**Comment by zrhoffman** [comment]
> From my local testing, the `go get` change only needs to be in the `enroller`. Am I missing something?

I'm having trouble reproducing it with the other images now. You're right, just enroller

**Comment by shamrickus** [comment]
Fixed the issue in enroller, the change doesn't appear to break the other services (removing `-u`) so I can add those if need be.

**Comment by zrhoffman** [comment]
> Fixed the issue in enroller, the change doesn't appear to break the other services (removing `-u`) so I can add those if need be.

IMO no reason to avoid `-u`since they're not failing to build

**Review by zrhoffman — APPROVED** [review]

**Pull request merged**
