### PR TITLE
Delivery service requests comments

### LINKED ISSUE #2848: TP - Delivery Service Requests, comments shows no data message when data is returned
In the Delivery Service Requests page, the comments table shows, "No data available for this table" even though the comments actually load.

### PR DESCRIPTION
**Pull request by chadgilloth**
#### What does this PR do? 
Fixes a minor issue where an incorrect message of 'no data available' was shown on the comments table even if there is data.

Fixes #2848

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Run TP with dsRequests set to true in properties. Go to Delivery Service Requests, pick a DS, notice there is no error message below the comments table.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2474/
Test PASSed.

**Comment by mitchell852** [comment]
Can you create a fake row or something when comments.length == 0?

image

looks kinda weird with no table body

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2492/
Test PASSed.

**Comment by mitchell852** [comment]
looks good. thanks for making requested changes.

**Pull request merged**
