### PR TITLE
Fix t3c to parent.config gen for IP origins

### PR DESCRIPTION
**Pull request by rob05c**
Currently, the cache config doesn't do any insight into the Delivery Service OrgServerFQDN field, and simply injects it as if it were a URI with an FQDN.

This causes issues as a parent.config `dest_domain=x` with an IP address is silently ignored by ATS, causing the corresponding remap.config line to either fall through to the `dest_domain=.` default rule, or to not use parent.config at all and go direct if no default rule exists in parent.config. ATC cache config should always create a default rule, with default parents. But these parents won't be the parents specifically assigned to that service, and won't contain any custom rules like retry codes and number of retries.

This fixes the cache config to generate `dest_ip=x` instead of `dest_domain=x` if the DS OrgServerFQDN is an IP address.

* I tested, and this is not an issue with strategies.yaml
* I tested both IPv4 an IPv6 addresses, both work correctly with this change
* This is not an issue for MSO, as the issue is with the `dest_` parent.config directive, and MSO uses the OrgServerFQDN as the remap target and parent dest, with real origins being inserted in the `parent=` directive where IPs are fine.
* Note this will _not_ send any proper hostname in the `Host` header of the request. If the origin requires a particular host be requested, it must be in the DS Origin. ATC simply lacks the data otherwise, and moreover ATS itself will always use the remap target as the host header, ATC doesn't have the ability to change that.

## Which Traffic Control components are affected by this PR?
- Traffic Control Cache Config (`t3c`, formerly ORT)

## What is the best way to verify this PR?
Run tests. Set an IP as an origin on a Delivery Service that uses cache parents, generate config, verify parent.config `dest_ip` is set, verify a request uses the parents specified on the line and not the parents specified in the default rule and doesn't go direct.

* note the DS OrgServerFQDN must be a URI, not an FQDN, contrary to the field name. I.e. `http://192.0.2.1` not simply `192.0.2.1`.

## If this is a bugfix, which Traffic Control versions contained the bug?
All prior versions.

## PR submission checklist
- [x] This PR has tests 
- ~[x] This PR has documentation~ no docs, no interface change 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by rawlinp** [comment]
Does this fix the following issue? https://github.com/apache/trafficcontrol/issues/890

**Comment by rob05c** [comment]
> Does this fix the following issue? #890

Yes, I added a link.

> it seems to work.

It doesn't work, that statement is wrong. I think we just didn't realize it before, because it falls back to the default, and we didn't used to have complex custom parents until recently.

I'd also note, that issue doesn't capture the complete issue with the bug. #890 just says we should do it, it doesn't say why. The reason and bug is that `dest_domain=ip` is silently ignored by ATS as if the entire line doesn't exist.

**Comment by rawlinp** [comment]
#890 mentions cache.config too, do we already use `dest_ip` in that file?

**Comment by rob05c** [comment]
> https://github.com/apache/trafficcontrol/issues/890 mentions cache.config too, do we already use dest_ip in that file?

No, that's a separate bug. I removed the Fixes directive.

**Review by jpappa200 — APPROVED** [review]
👍 Looks good to me!

**Review by ocket8888 — APPROVED** [review]

**Pull request merged**
