### PR TITLE
TP Use Correct Name in Role Put

### LINKED ISSUE #6925: Cannot update role name in Traffic Portal
## This Bug Report affects these Traffic Control components:

- Traffic Portal

## Current behavior:

When attempting to change a role's name in Traffic Portal, it fails with "no such role".
Screen Shot 2022-06-24 at 8 56 04 AM
Screen Shot 2022-06-24 at 8 56 32 AM

## Expected behavior:

Traffic Portal should pass the _original_ role name in the request query parameters instead of the _new_ name, which would allow a user to change the role's name.

## Steps to reproduce:

Try to change the name of a role in Traffic Portal. This affects at least the `master` branch.

### PR DESCRIPTION
**Pull request by shamrickus**
This PR fixes #6925
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Verify that a user is able to update a role through TP.

## If this is a bugfix, which Traffic Control versions contained the bug?

- master

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by ericholguin** [comment]
I was able to update a role's description, but a role's name cannot be updated. Is this normal?

**Comment by ocket8888** [comment]
> I was able to update a role's description, but a role's name cannot be updated, you will get the TP alert `role was updated.` displayed but the name remains the same. Is this normal?

Yes and no. It's normal in that the endpoint as-is cannot change Role names. But that is itself a bug - but it's a bug with TO, and that's not the bug this PR claims to fix.

**Comment by ericholguin** [comment]
> Yes and no. It's normal in that the endpoint as-is cannot change Role names. But that is itself a bug - but it's a bug with TO, and that's not the bug this PR claims to fix.

I see, so this fixes the TP issue. Is there an issue for TO. Looking at the code quickly the update query looks off

https://github.com/apache/trafficcontrol/blob/235256986342c411c515554d871a2269b0169d5d/traffic_ops/traffic_ops_golang/role/roles.go#L69-L74

**Comment by mitchell852** [comment]
is it possible to just fix both with this PR? TP and TO?

**Comment by ocket8888** [comment]
> is it possible to just fix both with this PR? TP and TO?

Yes it's certainly possible, but it's not strictly necessary. This PR fixes the linked bug, so there's no reason it can't be merged.

Also, based on that query, it's possible that we meant to make Role names immutable but simply forgot to document it and make the TP changes. I'd want to `git blame` it and ask the person who modified the query.

**Review by ericholguin — APPROVED** [review]
TP works as it should.

**Comment by ocket8888** [comment]
re-running CiaB action

**Comment by ericholguin** [comment]
> > I think names have been mutable, per this legacy query that exists above the new one
> 
> This makes me more sure the new behavior is intentional, otherwise the existing query language would've been re-used to a greater extent. I could still be wrong, but we'd need to hunt down the original proposal/PR to be sure. If that was the author's intent but was never communicated - or we just don't like that behavior -, we could reverse the decision even if it was intentional.

@srijeet0406

**Comment by srijeet0406** [comment]
I _think_ the intention was to keep the role names immutable, but I'm totally on board with reversing that. As long as the `admin` role is immutable, which I believe it is, we should be fine.

**Comment by ericholguin** [comment]
> I _think_ the intention was to keep the role names immutable, but I'm totally on board with reversing that. As long as the `admin` role is immutable, which I believe it is, we should be fine.

Thanks for clearing that up @srijeet0406 . I believe in the issue that @rawlinp created he was trying to change the name of a user. So this is probably something we would want. I don't see any harm in having mutable role names, but I may be wrong. Also this change would match our docs, which currently don't say they are immutable. If no one is opposed I can create the PR.

**Comment by mitchell852** [comment]
> I _think_ the intention was to keep the role names immutable, but I'm totally on board with reversing that. As long as the `admin` role is immutable, which I believe it is, we should be fine.

that makes sense to me. admin name immutable, others mutable. if not, puts extra burden on operators of the system.

**Pull request merged**
