### PR TITLE
CIAB: Add CDN_NAME environment variable

### PR DESCRIPTION
**Pull request by Shihta**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

Add a new environment variable: `CDN_NAME`
It's used to modify the CDN name in CIAB.

This commit also fix a `AUTO_SNAPQUEUE` issue.
If there are more than 1 deliveryservices in the folder `/infrastructure/cdn-in-a-box/traffic_ops_data/deliveryservices`, the feature `AUTO_SNAPQUEUE` will be failed.

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other CIAB

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

1. Modify the `CDN_NAME`. e.g. `TESTCDN`
2. Start CIAB
3. CIAB will work correctly and it's CDN name should be `TESTCDN`

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
add to whitelist

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3349/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3351/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3359/
Test PASSed.

**Comment by Shihta** [comment]
ok! I didn't aware this function. I'll change to use it.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3396/
Test PASSed.

**Pull request merged**
