### PR TITLE
enroller acts as http server and dir watcher

### PR DESCRIPTION
**Pull request by dangogh**
#### What does this PR do?

For cdn-in-a-box,  adds capability for enroller to act as an http server rather than directory watcher (can do either).  This allows cdn-in-a-box to be modified to not depend on the shared volume for enrolling the data to traffic ops.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other : cdn-in-a-box

#### What is the best way to verify this PR?
```
cd infrastructure/cdn-in-a-box/enroller
export TO_URL=... TO_USER=... TO_PASSWD=...
go run enroller.go -http :6060
curl localhost:6060/api/1.4/cdns -X POST -d@cdn.json
```

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2838/
Test PASSed.

**Comment by ocket8888** [comment]
This appears to be breaking CiaB. For every file it encounters it reports that it has "no method for creating". For example, here's the last few:

```
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.929208811Z: new file : /shared/enroller/profiles/070-RASCAL-Traffic_Monitor.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.929221467Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.93132868Z: new file : /shared/enroller/servers/010-bind_server.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.93135688Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.932527614Z: new file : /shared/enroller/servers/020-db_server.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.93254621Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.934031231Z: new file : /shared/enroller/servers/030-enroller_server.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.934075226Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.935240441Z: new file : /shared/enroller/servers/040-trafficvault_server.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.935254824Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.93670469Z: new file : /shared/enroller/deliveryservice_servers/010-demo1.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:49.93671806Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:50.839055476Z: new file : /shared/enroller/servers/trafficops.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:50.839123592Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:50.902078713Z: new file : /shared/enroller/servers/trafficrouter.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:50.902114676Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:51.024709059Z: new file : /shared/enroller/servers/trafficportal.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:51.024739141Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:51.073211498Z: new file : /shared/enroller/servers/trafficmonitor.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:51.073249112Z: no method for creating 
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:55.01766885Z: new file : /shared/enroller/servers/trafficops-perl.json
enroller_1         | INFO: asm_amd64.s:1333: 2018-11-28T17:07:55.017709787Z: no method for creating 
```

**Comment by ocket8888** [comment]
Enrollment no longer complains that it can't create objects.... but seemingly only because it doesn't realize it should. TP shows no servers, CDNs (besides ALL) or Delivery Services. I tried `touch`ing the CIAB CDN file at `/shared/enroller/cdns/010-CDN-in-a-Box.json`, and I tried moving that file out of the `/shared` directory and back in, but it never picked up that a change occurred. Here's the logs after I did those two tests  - trimmed out everything before the actual `enroller` binary was started:

```
enroller_1         | INFO: proc.go:201: 2018-11-29T14:44:09.48759042Z: Starting TrafficOps session
enroller_1         | INFO: proc.go:201: 2018-11-29T14:44:09.615855155Z: TrafficOps session established
enroller_1         | INFO: proc.go:201: 2018-11-29T14:44:09.615923996Z: Watching directory /shared/enroller
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616099736Z: watching /shared/enroller/types
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616179421Z: watching /shared/enroller/cdns
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616245319Z: watching /shared/enroller/deliveryservices
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616306557Z: watching /shared/enroller/phys_locations
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.61636532Z: watching /shared/enroller/regions
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616424773Z: watching /shared/enroller/cachegroups
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616480638Z: watching /shared/enroller/profiles
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616538626Z: watching /shared/enroller/parameters
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616599333Z: watching /shared/enroller/servers
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616673721Z: watching /shared/enroller/users
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616741662Z: watching /shared/enroller/asns
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.61680061Z: watching /shared/enroller/deliveryservice_servers
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616863315Z: watching /shared/enroller/divisions
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616931333Z: watching /shared/enroller/origins
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.616997728Z: watching /shared/enroller/statuses
enroller_1         | INFO: enroller.go:757: 2018-11-29T14:44:09.617052286Z: watching /shared/enroller/tenants
enroller_1         | INFO: proc.go:201: 2018-11-29T14:44:09.617110653Z: Created enroller-started
```

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2850/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2855/
Test PASSed.

**Pull request merged**
