### PR TITLE
CIAB: update postgres version to 9.6.12

### PR DESCRIPTION
**Pull request by Shihta**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

CIAB db can not be build anymore because its repository has been removed.
Check the following snapshot and this [path](http://cdn-fastly.deb.debian.org/debian/dists/) for details: 
螢幕快照 2019-03-27 下午3 38 51

## Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other CIAB

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

1. build CIAB and start it
2. check if the demo page can be accessed

## Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3401/
Test PASSed.

**Comment by ocket8888** [comment]
Maybe it'd be more prudent to use the `postgres:9.6` (or even `postgres:9` ?) image instead, in case this happens again?

**Comment by Shihta** [comment]
that's ok~
change to use 9.6-alpine

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3403/
Test FAILed.

**Comment by dangogh** [comment]
retest this please

**Comment by dangogh** [comment]
and yes -- I agree with Brennan on using 9.6 rather than a specific minor version.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3405/
Test PASSed.

**Pull request merged**
