### PR TITLE
Fix optional vnc container

### PR DESCRIPTION
**Pull request by JBevillC**
#### What does this PR do?

This PR fixes a number of problems with the existing vnc `testclient` container:

Documentation updated. Depends on PR #3040

1) rename the container to `vnc` since that is its purpose
2) add `vnc.infra.ciab.test` hostname entry into the static dns server configuration.
3) move the vnc container under the `optional` containers directory for better organization
4) updates the shared volume required to get access to shared CA x509 SSL certificate
5) fixes to allow firefox to start up in a  container without dbus or systemd
6) default vnc password is now random by default. Override via environment at runtime.
7) Port changed to 5909 to avoid port collision

New proposed directory structure for optional containers: 
```
cdn-in-a-box/optional
cdn-in-a-box/optional/docker-compose.$NAME.yml
cdn-in-a-box/optional/$NAME/
```

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [x] Other _cdn-in-a-box________

#### What is the best way to verify this PR?

1) Add VNC_PASSWD with six alphanumeric password to variables.env
2) Start up the CIAB stack using the following alias:
```
alias vncdc='docker-compose -f docker-compose.yml -f optional/docker-compose.vnc.yml'
vncdc build 
vncdc kill && vncdc rm -fv 
docker volume prune -f
vncdc up
```
3) Connect with vnc client to localhost 5909 with $VNC_PASSWD
4) firefox should start as soon as the traffic portal is available.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2758/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2816/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2817/
Test FAILed.

**Comment by JBevillC** [comment]
Absolutely.

**Comment by JBevillC** [comment]
Documentation updated.  Depends on PR #3040

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2903/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2904/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2916/
Test PASSed.

**Pull request merged**
