### PR TITLE
CiaB: added log path of traffic monitor in variables.env

### PR DESCRIPTION
**Pull request by Shihta**
## What does this PR (Pull Request) do?

1. added log path of traffic monitor in variables.env
2. shows log in `stdout` directly

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

1. Start CiaB
2. You should get TM log by `docker logs`

Since there is no any new feature so I didn't provide test

## If this is a bug fix, what versions of Traffic Ops are affected?

master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3831/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3832/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3906/
Test PASSed.

**Comment by Shihta** [comment]
@dangogh not sure what happened...  but why you can merge `apache/trafficcontrol:master` into my `Shihta/trafficcontrol:CIAB_TM_LOG` ....?
is that github bug?

**Comment by dangogh** [comment]
I was able to fix the merge conflict with master so I could test and maybe merge.   If you think that was in error,  please make necessary changes and I will again check tomorrow.

**Comment by dangogh** [comment]
in direct answer to your question,  see this:  https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3914/
Test PASSed.

**Comment by Shihta** [comment]
It seems a little strange...
I use `rebase` to fix the conflicts.
I think that looks better

**Comment by dangogh** [comment]
ah,   good..  I'll try and finish checking this today.

**Pull request merged**
