### PR TITLE
[TC-166] Traffic Router now updates the lastConfigCheck stat if timestamps of …

### PR DESCRIPTION
**Pull request by dneuman64**
…CrConfigs match

This fixes [TC-166](https://issues.apache.org/jira/browse/TC-166)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-traffic_ops-test-PR/18/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR-trafficops-test/29/

**Comment by dneuman64** [comment]
This PR was an attempt to fix an edge case related to running Java TM and Go TM at the same time in production.  Since Java TM is no longer supported, users should not be running in a configuration like this.  Closing.

**Pull request closed without merging**
