### PR TITLE
Change Monitor stat history to sync.Map

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Based on #3000 - recommend merging that first.

Change Monitor stat history to sync.Map

    This significantly improves performance. In my testing, for a large
    CDN, processing Stat results can take ~5 seconds, where ~1s of that
    was copying and setting the mutexed stat history variable. This
    essentially eliminates that 1s or 1/5 of stat processing time, for
    every stat process. This significantly reduces CPU, and/or makes
    the monitor able to poll stats in significantly less time.
    
    Also changes the stat history array to not reallocate memory,
    but move the data when prepending a new result. Which is also
    significantly faster, in my testing.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Run Monitor, verify health and stats are polled correctly. This PR does not change the interface; it's an internal performance improvement.

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2759/
Test PASSed.

**Comment by rob05c** [comment]
Can you give me an idea of what you want to see here? This is really just changing a mutexed map, to a sync.Map. I'm having a hard time coming up with a good test, for the changes this makes. I mean, I could write a test to verify the data put in the map is what we get out; but testing the Go Standard Library doesn't seem that valuable.

I agree, the `CreateStats` function that this is used by at a high level would benefit from a test. But it's a pretty big function, arguably about 1/3 of the overall logic in the Monitor, likely several weeks to write. I'd certainly support prioritizing and writing that. But in the context of this PR, several weeks of tests, for several days of code?

I'm having a hard time coming up with a useful test that's any smaller.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2801/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2803/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2804/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2805/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2812/
Test FAILed.

**Pull request merged**
