### PR TITLE
Add Grove to TO unit tests and TO API tests Docker images

### LINKED ISSUE #4839: Traffic Ops unit tests Docker container exits on go get
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The Traffic Ops unit tests Docker container exits on `go get` (running at 78e4b005fc).

## Expected / new behavior:

Traffic Ops unit tests Docker container should exit with no errors after running unit tests

## Minimal reproduction of the problem with instructions:

```shell script
docker-compose -f traffic_ops/app/bin/tests/docker-compose.yml up --build
```

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4839

- #4665 introduced Grove as a dependency of Traffic Ops Golang, so now the unit tests Docker image needs to include Grove. This PR adds it to the Docker image.
- #4665 introduced Grove as a dependency of the TO Go client library, and Grove requires `golang.org/x/sys/unix`. This PR adds Grove and `golang.org/x/sys/unix` as Traffic Ops API Tests Docker image build dependencies.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

```shell script
docker-compose -f traffic_ops/app/bin/tests/docker-compose.yml up --build
```

```shell script
docker-compose -f infrastructure/cdn-in-a-box/docker-compose.traffic-ops-test.yml up integration
```

## If this is a bug fix, what versions of Traffic Control are affected?

- master (78e4b005fc)

## The following criteria are ALL met by this PR

- [x] This PR fixes an existing test
- [x] Bugfix from master only, no documentation necessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by rob05c** [comment]
>#4665 introduced Grove as a dependency of Traffic Ops Golang, so now the unit tests Docker image needs to include Grove. This PR adds it to the Docker image.

I don't object to this fix - but, we should really fix that dependency. TO shouldn't depend on Grove. We should move the `grove/web` things it needs to `lib/go-rfc`.

**Comment by mitchell852** [comment]
> Made sure `docker-compose -f traffic_ops/app/bin/tests/docker-compose.yml up --build` passes. Thanks for fixing this.
> I do agree with @rob05c that we should remove that dependency in the future.

@srijeet0406 or @rob05c - want to create an issue so this doesn't get lost?

**Comment by srijeet0406** [comment]
@mitchell852 I'll create an issue

**Comment by rob05c** [comment]
@srijeet0406 I just did: https://github.com/apache/trafficcontrol/issues/4841

**Pull request merged**
