### PR TITLE
Fix TO Go cdn dnssec generate to accept numbers

### LINKED ISSUE #2716: To go cdns dnssec generate does not work
screen shot 2018-08-20 at 12 47 28 pm

Steps to reproduce in Traffic Portal:
1. Select a CDN from the "CDNs" tab
2. click the "More" dropdown
3. Click "Manage DNSSEC Keys"
4. click "Regenerate DNSSEC Keys"
5. click "Yes"
6. Click "Generate"
7. Type in the name of the CDN to confirm
8. Click "Confirm"

### PR DESCRIPTION
**Pull request by rob05c**
The docs say they're strings, but it appears Perl accepts both,
and the Portal sends numbers. This changes Go to emulate the Perl.

Fixes #2716

#### What does this PR do?

Fixes #2716

#### Which TC components are affected by this PR?

- [x] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Steps to Reproduce in #2716

Be aware this endpoint takes a long time, reproducing will likely require increasing http and db timeouts.

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [x] This PR does *NOT* fix a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2299/
Test PASSed.

**Comment by mitchell852** [comment]
@rob05c - can you write a unit test for this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2303/
Test PASSed.

**Comment by rob05c** [comment]
>@rob05c - can you write a unit test for this? or an integration test? or whatever makes the most sense?
@mitchell852 https://github.com/apache/trafficcontrol/pull/2720/files#diff-548856fd9ea3ae645fc12cb9afde3e31R31

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2308/
Test PASSed.

**Pull request merged**
