### PR TITLE
CIAB: Let auto-snapqueue and add-sslkeys be functions

### PR DESCRIPTION
**Pull request by Shihta**
## What does this PR (Pull Request) do?

- [x] This PR  is not related to any Issue

auto-snapqueue and add-sslkeys are good features and worth reusing.
This commit changes them into separate functions.

This PR doesn't change the CIAB usage so I didn't attach the document.

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

1. Start CIAB
2. Check the snapshot can be automatically took
3. Check the demo site can be accessed via `HTTPS` protocol.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3495/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3497/
Test PASSed.

**Comment by ocket8888** [comment]
You know, looking at the auto snap/queue code I'm starting to wonder if maybe we're pushing the limits of what Bash should be doing. Every iteration parses these JSON responses seven times and I can't help but think how much cleaner this would be if we could parse those into objects immediately and iterate over them with `for x in y` instead of a while loop with condition checking

**Comment by Shihta** [comment]
I can try to improve that.
However, do you mean we should use another method instead of continually improving this piece of bash code?

**Comment by ocket8888** [comment]
Yeah, I think maybe we're approaching a level of complexity that might be better handled by a Python script. Or a Perl script, I guess, but I think we're moving away from Perl as a project.

**Comment by Shihta** [comment]
I think you are right and I have raised a discussion on slack.
I need more suggestion.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3557/
Test PASSed.

**Pull request merged**
