### PR TITLE
TO Golang: Small CRUDer change to allow interface use for a single method type

### PR DESCRIPTION
**Pull request by moltzaum**
#### What does this PR do?

This should allow the CRUDer interfaces to work with just an updater, or just a creator, or some mix that doesn't include all CRUD operations.

#### Which TC components are affected by this PR?

Traffic Ops

#### What is the best way to verify this PR?

Commenting out one of the already existing handlers (I did the create for cdns), then
testing the endpoint with curl.
`curl -XPOST --cookie $mc -Lvsk 'https://localhost:6443/api/1.3/cdns' -d @cdn.json | jq`

This should yield an internal server error, which also logs an error.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by moltzaum** [comment]
I was trying to get something similar to that originally. I'm glad it doesn't use an interface, but I also wish it wasn't so long: `api.ReadHandler(api.ToReadFactory(example.GetTypeSingleton()))`
Seems a little repetitive in my opinion.

I was thinking about how it was a runtime error and thought it would be fine since it seems like a pretty hard thing to miss. It would be especially if api tests are associated with the endpoint, which is standard pratice. Would you still reject the PR for this?

**Comment by moltzaum** [comment]
Looking at the playground again, it seems endpoint writers have two options. 1) implement either full CRUDer or 2) create a factories for each operation individually. Supposing every operation is needed except for the delete (as an example), would you expect the implementor to have an extraneous delete function, or to create three separate factories?

Before I realized this, I was a little more on the fence. I suppose you could argue that most operations are CRUDer only anyway, which is why support for single or mixed endpoints hasn't been implemented yet. Overall I think I'd prefer what I perceive to be both better readability and writability.

I realize tests aren't perfect in the general case, but an internal server error that gets triggered depending on the presence of a method seems similar to how a 404 would behave as if the endpoint wasn't written at all. One would only need to curl the endpoint once and we get an error no matter what. Would it be better to turn it into a 404, that also logged an error internally?

**Comment by moltzaum** [comment]
@rob05c I am willing to rewrite it so that it uses strong typing, but still want to see if you think this is the best approach.

**Comment by rob05c** [comment]
>Looking at the playground again, it seems endpoint writers have two options. 1) implement either full CRUDer or 2) create a factories for each operation individually. Supposing every operation is needed except for the delete (as an example), would you expect the implementor to have an extraneous delete function, or to create three separate factories?

I don't think that's a common case, and if it is, creating Factories for each type doesn't seem unreasonable. Each Factory should only be 3 lines, 

```
func CreateFactory() api.CreateFactory {
	return func(reqInfo *api.APIInfo) api.Creator { return &TODivision{reqInfo, tc.DivisionNullable{}} }
}
func ReadFactory() api.ReadFactory {
	return func(reqInfo *api.APIInfo) api.Reader { return &TODivision{reqInfo, tc.DivisionNullable{}} }
}
```

In fact, I've wondered if we should just get rid of the `CRUDer` interface, and require every endpoint to implement its own type. I'm not sure there's really a reason to keep them together, except saving a few lines of code.

Actually, there's another option too: we could get rid of the factories altogether, by adding a method to populate the `APIInfo`, `func (v *TODivision) SetInfo(i *api.APIInfo) { v.ReqInfo = i }`, and changing the "CRUDer" funcs to take the actual object instead of a factory:

```Go
{1.1, http.MethodGet, `divisions/?(\.json)?$`, api.ReadHandler(division.TODivision{}), auth.PrivLevelReadOnly, Authenticated, nil},
```

and then calls `v.SetInfo()` on the object it receives.

Now that I think about it, I like that solution. That fixes the fundamental issue, that Go polymorphism can't perform duck typing on function parameters. And IMO factories are a pain to deal with anyway.

What do you think about that solution, getting rid of factories altogether? That provides the flexibility you want, allowing a type to only implement the CRUD types it uses, while still preserving type safety, and also being a simpler and more idiomatic solution than factories.

**Comment by moltzaum** [comment]
I agree, and can update this PR accordingly.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3090/
Test FAILed.

**Comment by moltzaum** [comment]
I've updated it for a discussion.

The thing I'm not 100% on right now is the names and file content.
Eg.
   - APIInfo is the original typename of ReqInfo
   - APIInfoer is the interface that names getters and setters for APIInfo
   - APIInformer gives a simple implementation that can be embedded in a struct

Is there a known naming convention for this pattern? I don't think `APIInfo` is the best name since imo it is a little generic, but didn't want to just change it suddenly. At the moment I think `APIInfo` and `APIInfoer` by themselves fit the golang interface naming convention, but that I should change `APIInformer` to `RequiredInfo` so that it reads: `api.RequiredInfo`, or maybe `api.ReqCRUDInfo`.

About the file content:
I think I should just put all APIInfo stuff into an `api_info.go` file. Either that, or put it all in `api.go`, but have a misc file for the other things in that file. What do you think?

traffic_ops_golang/api:
	
		crud
			generic handlers for the common case
			+ added APIInformer implementation here
		shared_handlers
			boilerplate handlers for everything
		shared_interfaces
			defines the CRUDer interfaces
			+ added APIInfoer interface here
		api
			where APIInfo is defined
			handler writer and error functions
			params

**Comment by rob05c** [comment]
>Is there a known naming convention for this pattern?

`APIInfoer` is correct: https://golang.org/doc/effective_go.html#interface-names

I don't think there's a single convention or idiom for the implementation. `APIInformer` seems fine to me. It's common to be lowercase if it shouldn't be exported, e.g. `apiInfoer`, but here it needs to be. I believe I've seen `*Impl` in the Go source, e.g. `APIInfoImpl`.

>I don't think APIInfo is the best name since imo it is a little generic

I agree, it's not great. But it's a generic thing. It has all the random data an API endpoint needs, params, the user, the db transaction, etc. I'm open to ideas, if you have a better suggestion? 

>but didn't want to just change it suddenly

If there's something better, I don't think we should be hesitant to improve names. It's tech debt like any other.

>I think I should just put all APIInfo stuff into an api_info.go file. Either that, or put it all in api.go, but have a misc file for the other things in that file. What do you think?

I'd kind of rather we kept all the "api helper" stuff in `api.go`, unless it gets too big, which I don't think it is yet. It's easier to search for them, and know this file is the "api helpers", where shared_handlers.go is the "cruder" stuff, and crud.go is the "generic" stuff.

>change APIInformer to RequiredInfo

If all it does is implement the `APIInfo` interface, I think it's easier to read and understand if it has "APIInfo" in the name somehow.

**Comment by moltzaum** [comment]
I don't have a better name, and the more I think about it the more I'm fine with it. I do like the idea of `APIInfoImpl` though. And just to make it clearer from the outside, I think `crud.go` should be `generic_crud.go`

**Pull request merged**
