### PR TITLE
Fix incorrect error handling on validate server capabilities

### LINKED ISSUE #4123: TO: Can link Edge Server, w/o Required Capabilities, to Delivery Service
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` Request to `https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices/{{xml_id}}/servers` 
Where the associated delivery service has a required capability assigned,
and Edge Server has no server capabilities. It is allowed and returns no errors
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
    "response": {
        "serverNames": [
            "testEdgeServer"
        ],
        "xmlId": "test"
    }
}
```

## Expected / new behavior:

Should not allow Edge Server missing required capabilities to be assigned to delivery service
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
    "alerts": [
        {
            "text": "Caching server cannot be assigned to this delivery service without having the required delivery service capabilities: [[FOO]] for server testEdgeServer",
            "level": "error"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by mhoppa**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4123 

`deliveryservices/{id}/servers` handles the errors correctly but the `deliveryservices/{xml_id}/servers` ignores them which is the only difference for required capabilities validation between the two endpoints.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Assign server capability to a delivery service with no servers. Then attempt to assign an edge server (that doesn't have the server capability) to that delivery service via `deliveryservices/{xml_id}/servers` route.

## If this is a bug fix, what versions of Traffic Control are affected?

master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
That issue mentions that the problem exists in `/deliveryserviceservers` as well, do you want to fix that in the same PR? You don't have to, but you shouldn't close the issue if you don't.

**Comment by mhoppa** [comment]
The issue only points out `deliveryservices/{xml_id}/servers` and I tested `deliveryserviceservers` and it works as expected fwiw

**Comment by ocket8888** [comment]
You're right. Idk where I got that. Might've just had a tiny stroke.

**Comment by ocket8888** [comment]
So I created a capability 'foo' and assigned it to a Delivery Service, then created a new Edge-tier server (id 14) and tried to assign it to the Delivery Service (while it didn't have the required capability). What I got was strange:
```http
POST /api/1.4/deliveryservices/demo1/servers HTTP/1.1
User-Agent: python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 19

{"serverIds": [14]}
```

```http
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
X-Server-Name: traffic_ops_golang/
Date: Tue, 19 Nov 2019 16:04:33 GMT
Content-Length: 74

{
	"response": {
		"serverNames": null,
		"xmlId": "demo1"
	}
}
```

**Comment by mhoppa** [comment]
you shouldnt at all - let me try again

**Comment by mhoppa** [comment]
ahh your request body is invalid (which is seperate from this bug fix) -> `https://traffic-control-cdn.readthedocs.io/en/latest/api/deliveryservices_xmlid_servers.html#id3` you should be passing in serverNames not serverIds

**Pull request merged**
