### PR TITLE
CiaB: Enabled remap_stats.so in ats

### PR DESCRIPTION
**Pull request by Shihta**
## What does this PR (Pull Request) do?

Enabled remap_stats.so in ats
Traffic stats can not collect some data without this plugin so we should enable it

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

1. Start CiaB
2. Send some requests to demo site, e.g.
```
curl -L http://video.demo1.mycdn.ciab.test
curl -L http://video.demo1.mycdn.ciab.test/tc_logo.svg
curl -L http://video.demo1.mycdn.ciab.test/1213 # used to generate 4xx status
```
3. Check status in influxdb. you can use the following instructions in influxdb container:
```
# connect influxdb
influx

# query data
use deliveryservice_stats
select * from status_4xx where value != 0  # you should find some records
select * from tps_2xx where value != 0  # you should find some records
```

4. You can also check charts on portal:
```
https://trafficportal.infra.ciab.test/#!/delivery-services/1/charts?type=HTTP
```

Since there is no any new feature so I didn't provide test

## If this is a bug fix, what versions of Traffic Ops are affected?

master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3865/
Test FAILed.

**Comment by Shihta** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3866/
Test PASSed.

**Comment by ocket8888** [comment]
I can't get this to work. I have previously been able to view `stats_{{N}}XX` statistics (which I used when testing my pet Angular 7 project's graphs), but so far using this branch I can't see any changes in the indicated graph. I can see that the plugin was successfully loaded in the edge service's docker-compose logs:
```
edge_1             | [Jun 24 18:02:03.599] Server {0x2af28e0d1400} NOTE: loading plugin '/usr/lib64/trafficserver/plugins/remap_stats.so'
```
so at least that's working, but I'm concerned that this is somehow breaking graphs? unless it's unrelated, and graphs have just stopped working in the past couple of weeks...

**Comment by Shihta** [comment]
I retested it on different machines.
Sometimes the chart is normal but sometimes it's not
I think I can't find out the reason in a short period of time.
I'll send PR again when it's fixed

**Pull request closed without merging**
