### PR TITLE
TO Go: check for missing cert files before starting

### LINKED ISSUE #3479: traffic_ops_golang unhelpful msg when cert file missing
If the cert or key file specified in `cdn.conf` is unreadable,  `traffic_ops_golang` exits with a cryptic error message:  
```
INFO: proc.go:201: 2019-04-09T23:20:00.973182017Z: Listening on 443
ERROR: asm_amd64.s:1333: 2019-04-09T23:20:00.974145892Z: stopping server: open : no such file or directory
```

### PR DESCRIPTION
**Pull request by dangogh**
## What does this PR (Pull Request) do?

Adds an informative message to `traffic_ops_golang` if either the cert file or key file are missing.

- [x] This PR fixes #3479 

## Which Traffic Control components are affected by this PR?
- CDN in a Box
- Traffic Ops

## What is the best way to verify this PR?

In an existing installation, modify `/opt/traffic_ops/app/conf/cdn.conf`.  The cert and key are specified in the `hypnotoad.listen` entry:
```
https://...?cert=/etc/pki/tls/certs/localhost.crt&key=/etc/pki/tls/private/localhost.key&...
```

Change the file names in that listen entry and restart traffic_ops.  `traffic_ops_golang` should produce an error message that the file doesn't exist and exit with a proper error code.

No changes in normal operation,  so no test or documentation or CHANGELOG needed

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3505/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3508/
Test PASSed.

**Comment by dangogh** [comment]
I see your point..

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3510/
Test FAILed.

**Comment by dangogh** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3512/
Test PASSed.

**Pull request merged**
