### PR TITLE
TO Go API: fixed deliveryservice_request missing fields from DeliveryServiceV13 struct

### LINKED ISSUE #2527: TO Go API: deliveryservice_request missing fields from DeliveryServiceV13 struct
When creating a Delivery Service Request in TP, the fields specific to the DeliveryServiceV13 struct are ignored and not included in the jsonb field 'deliveryservice' in the deliveryservice_request table (go fields: DeepCachingType, SigningAlgorithm, Tenant, TRResponseHeaders, TRRequestHeaders). 

Consequently, when opening a Delivery Service Request in TP, these fields are always null and either show an invalid diff, or don't retain changes.

To reproduce:
- Create Delivery Service Request on HTTP delivery service in TP
- Open Delivery Service Request and notice diff on required field 'Deep Caching', and other fields noted above

### PR DESCRIPTION
**Pull request by rivasj**
fixed deliveryservice struct versioning issue. fixes #2527

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by dangogh** [comment]
add to whitelist

**Comment by DylanVolz** [comment]
All tests pass, This looks like an oversight when the structs got versioned. +1

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2109/
Test PASSed.

**Pull request merged**
