### PR TITLE
Removing obsolete statement for previous Traffic Router

### LINKED ISSUE #2994: Traffic Router use of obsolete breaks roll back
The following line of code prevent any rollback of traffic router version previous to 3.0.0.

https://github.com/apache/trafficcontrol/blob/ebd05c703c22ae634398838a011f6715b747838b/traffic_router/build/pom.xml#L228

I recommend removing the line as you can't install any previous RPMS by specifying the version number anymore unless you use special command line for yum.

### PR DESCRIPTION
**Pull request by smalenfant**
#### What does this PR do?

Fixes #2994

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [X] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

Upgrade from previous system works as normal. Secondly, make sure you can rollback to a previous version.

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2746/
Test PASSed.

**Comment by smalenfant** [comment]
I verified in our lab. This is working just as well as the previous RPMS for 2.x.

**Comment by elsloo** [comment]
By verify, do you mean that you verified that the downgrade works properly?

**Comment by mitchell852** [comment]
@smalenfant - see question from @elsloo

**Comment by ocket8888** [comment]
The lines this removes no longer exist in `traffic_router/build/pom.xml` as far as I can see - can this PR be closed?

**Pull request closed without merging**
