### PR TITLE
Minor versioning prototype

### PR DESCRIPTION
**Pull request by rawlinp**
This is a draft PR to illustrate my idea for handling TO API minor versioning.

Essentially, requests that come in at a previous minor version will be "upgraded" into requests of the next latest versions until they are finally handled by one "main" handler that always handles requests at the latest minor version. The result is then passed back down the chain until the result is translated back into the minor version that the client originally requested.

For POST requests, the "upgrade" process is simply just taking the specific minor version, embedding it into the next latest struct version, and passing it up. For PUT requests, the "upgrade" process would include reading the existing fields for the next latest minor version from the DB and passing it up to the next handler.

What we end up with is a chain of "sub-handlers" that simply upgrade requests into the next latest minor version until the request is finally handled at the latest minor version -- the "main" handler -- then downgrade that result until the originally requested minor version is returned.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3607/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3608/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3611/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3615/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3826/
Test PASSed.

**Comment by rawlinp** [comment]
closing this as the refactor has been applied to the DS API in https://github.com/apache/trafficcontrol/pull/3713

**Pull request closed without merging**
