### PR TITLE
Astats plugin - Add null check around strtok_r token usage

### PR DESCRIPTION
**Pull request by ezelkow1**
According to clang analyzer its possible that the token might be null, which you cannot pass to strtok_r as the save pointer (last argument).  Adding a null check before calling those

## What does this PR (Pull Request) do?

- [x] This PR fixes #REPLACE_ME OR is not related to any Issue 

## Which Traffic Control components are affected by this PR?

- Traffic Server

## What is the best way to verify this PR?

Compile the astats plugin and run with an ATS installation and ensure that stats are output properly based on the config file used (correct path and IP blocking, etc)

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
This is being done in a lot of other places in that file, is there a reason this line in particular is a problem?

**Comment by ezelkow1** [comment]
> 
> 
> This is being done in a lot of other places in that file, is there a reason this line in particular is a problem?

Its because of the usage of tok1. So all the other usages of strtok_r in there are taking a single pointer for the save value, and then just iterating over strtok_r until it returns null.  However in these 2 instances they are re-using the tok1 value from previous strtok_r calls.  Strtok_r can return a null value if it doesnt find the string its looking for

So in these 2 instances its possible that the first call to strtok_r will have returned a null value, and then you are using an explicit null pointer as the save value

**Comment by mitchell852** [comment]
@ezelkow1 - can you fix the description of this PR? Looks like this PR has an impact on every TC component which I'm guessing it does not. I thought we had a bullet for Traffic Server. maybe i'm wrong.

**Comment by ezelkow1** [comment]
> @ezelkow1 - can you fix the description of this PR? Looks like this PR has an impact on every TC component which I'm guessing it does not. I thought we had a bullet for Traffic Server. maybe i'm wrong.

Ahh sure, didnt realize I needed to edit that list. I added Traffic Server, it wasnt in there

**Pull request merged**
