### PR TITLE
Update condition used to determine what API version of `Server` to return upon successful update

### LINKED ISSUE #5289: Servers PUT handler returns API v2 servers when requested at v1
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
When modifying a server by requesting API version 1, the server will respond (on success) with an APIv2 server structure.

## Expected behavior:
The API should respond to APIv1 requests with APIv1 structures only.

## Minimal reproduction of the problem with instructions:
Modify a server using APIv1, notice the response includes fields only added in APIv2.

## Anything else:
<details><summary>HTTP Stack</summary>

```http
PUT /api/1.4/servers/6 HTTP/1.1
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Cookie: mojolicious=...
Content-Length: 937

{
	"cachegroup": "CDN_in_a_Box_Edge",
	"ipNetmask": "2.2.2.2",
	"ipGateway": "3.3.3.3",
	"cachegroupId": 1,
	"cdnId": 1,
	"cdnName": "CDN-in-a-Box",
	"domainName": "infra.ciab.test",
	"guid": null,
	"hostName": "test",
	"httpsPort": 443,
	"iloIpAddress": "",
	"iloIpGateway": "",
	"iloIpNetmask": "",
	"iloPassword": "",
	"iloUsername": "",
	"mgmtIpAddress": "",
	"mgmtIpGateway": "",
	"mgmtIpNetmask": "",
	"offlineReason": "",
	"physLocation": "Apachecon North America 2018",
	"physLocationId": 2,
	"profile": "ATS_EDGE_TIER_CACHE",
	"profileDesc": "Edge Cache - Apache Traffic Server",
	"profileId": 8,
	"rack": "a new rack",
	"revalPending": false,
	"routerHostName": "",
	"routerPortName": "",
	"status": "REPORTED",
	"statusId": 3,
	"tcpPort": 80,
	"type": "EDGE",
	"typeId": 11,
	"updPending": false,
	"xmppId": "edge",
	"xmppPasswd": "",
	"ipAddress": "1.1.1.1",
	"interfaceMtu": 1281,
	"ip6Address": "::1",
	"interfaceName": "eth0"
}

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Set-Cookie, Cookie
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json
Set-Cookie: mojolicious=...; Path=/; Expires=Tue, 17 Nov 2020 02:44:52 GMT; Max-Age=3600; HttpOnly
Vary: Accept-Encoding
X-Server-Name: traffic_ops_golang/
Date: Tue, 17 Nov 2020 01:44:52 GMT
Content-Length: 495

{
        "alerts": [
                {
                        "text": "Server updated",
                        "level": "success"
                }
        ],
        "response": {
                "interfaceMtu": 1281,
                "interfaceName": "eth0",
                "ip6Address": "::1",
                "ip6Gateway": null,
                "ipAddress": "1.1.1.1",
                "ipGateway": "3.3.3.3",
                "ipNetmask": "2.2.2.2",
                "cachegroup": "test",
                "cachegroupId": 1,
                "cdnId": 1,
                "cdnName": "ALL",
                "domainName": "infra.ciab.test",
                "guid": null,
                "hostName": "test",
                "httpsPort": 443,
                "id": 6,
                "iloIpAddress": "",
                "iloIpGateway": "",
                "iloIpNetmask": "",
                "iloPassword": "",
                "iloUsername": "",
                "lastUpdated": "2020-11-17 01:44:52+00",
                "mgmtIpAddress": "",
                "mgmtIpGateway": "",
                "mgmtIpNetmask": "",
                "offlineReason": "",
                "physLocation": "test",
                "physLocationId": 2,
                "profile": "RIAK_ALL",
                "profileDesc": "Riak profile for all CDNs",
                "profileId": 8,
                "rack": "a new rack",
                "revalPending": false,
                "routerHostName": "",
                "routerPortName": "",
                "status": "REPORTED",
                "statusId": 3,
                "tcpPort": 80,
                "type": "EDGE",
                "typeId": 11,
                "updPending": false,
                "xmppId": "edge",
                "xmppPasswd": "",
                "ipIsService": true,
                "ip6IsService": true
        }
}
```

</details>

### PR DESCRIPTION
**Pull request by MylesBock**
## What does this PR (Pull Request) do?
Updates the PUT handler for `servers` to properly assess what API version for the `ServerNullable` struct to return.
Previously it looked at the minor revision (as indicated in #5289) and now looks at the major revision.
I am unsure of how to boost the test coverage to validate this, so marking it as a draft.

- [x] This PR fixes #5289 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
I'm hesitantly putting this on the 5.0.x milestone. It appeases my desire for no regression bugs in a major release, but I'm a little nervous with how overdue this release is to add things that are in a draft state.

Hopefully we can get this in today since from what I can see the code changes already fix the bug, but I'm cutting a release candidate for 5.0.x as soon as 4.1.1 is released, so if this doesn't make it, it doesn't make it. The v1 API is deprecated and should be unused by components at the time of upgrade, so I consider it low-risk/impact enough to do that. If anyone seeing this disagrees, lmk.

**Comment by MylesBock** [comment]
I only marked it as a draft because I just don't know how to augment the existing tests to cover this case. If it resolves the issue and is small enough to go untested then I pose no opposition.

**Comment by MylesBock** [comment]
@ocket8888 thoughts? I could still try to get some coverage on this if desired

**Comment by ocket8888** [comment]
No, I think that's fine, I just need to test it now.

**Review by ocket8888 — APPROVED** [review]
Works

**Pull request merged**
