### PR TITLE
Add TO Go cdns/configs/routing

### LINKED ISSUE #2941: /api/1.x/cdns/{{name}}/configs/routing Doesn't work
If you try to hit this endpoint, you get a 500 response with this error message:

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  column cachegroup.latitude does not exist
LINE 1: SELECT cachegroup.name, cachegroup.latitude, cachegroup.long...
                                ^ [for Statement &quot;SELECT cachegroup.name, cachegroup.latitude, cachegroup.longitude FROM server me  JOIN cdn cdn ON cdn.id = me.cdn_id  JOIN cachegroup cachegroup ON cachegroup.id = me.cachegroup WHERE ( cdn.name = ? ) GROUP BY cachegroup.name, cachegroup.latitude, cachegroup.longitude&quot; with ParamValues: 1=&#39;over-the-top&#39;] at /opt/traffic_ops/app/lib/API/Cdn.pm line 693
```

### LINKED ISSUE #3782: Rewrite /cdns/{name}/configs/routing to Go
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/cdns/{{name}}/configs/routing` is handled by Perl

## Expected / new behavior:
`/cdns/{{name}}/configs/routing` should be handled by Go

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else

PR in progress: #2450

### PR DESCRIPTION
**Pull request by rob05c**
Rewrites `/cdns/{{name}}/configs/routing` to Go. Closes #2941 and closes #3782

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1881/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1950/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/1953/
Test PASSed.

**Comment by rawlinp** [comment]
I thought this endpoint was a broken, partial implementation of trying to break up the CRConfig into multiple files. Last time I checked, the Perl version of this endpoint didn't seem to return a useful result.

Is it worth keeping this rewrite, or can we just deprecate the endpoint?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4136/
Test PASSed.

**Comment by mitchell852** [comment]
@rob05c - what do you think? Should we close this and someone can work to deprecate instead?

**Comment by mitchell852** [comment]
Closing as it was decided that this route would be deprecated and not rewritten. I did speak with @rob05c about it first.

**Pull request closed without merging**
