### PR TITLE
Traffic Router tests GHA: Include integration tests

### PR DESCRIPTION
**Pull request by zrhoffman**
This Pull Request
* renames the [*Traffic Router Unit Tests*](https://github.com/apache/trafficcontrol/actions/workflows/tr.unit.tests.yaml) workflow to [*Traffic Router Tests*](https://github.com/apache/trafficcontrol/actions/workflows/tr.tests.yaml)
* Makes the *Traffic Router Tests* GitHub Action run the integration (and external) tests, in addition to the unit tests
* Adds specific paths to the *Experimental Traffic Portal v2* workflow's *push* trigger so it no longer runs on every commit
<hr/>

## Which Traffic Control components are affected by this PR?

- Automation - GitHub Actions

## What is the best way to verify this PR?

Verify that the *Traffic Router Tests* GHA includes the TR integration tests

## PR submission checklist
- [x] This PR has tests 
- [ ] This PR has documentation 
- [ ] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by ocket8888 — COMMENTED** [review]
Looks like it's having some kind of permissions issue uploading the JUnit reports

image

You can see this warning and error as annotations in the check run, even though it was successful (which makes sense because the actual tests themselves pass).

**Comment by zrhoffman** [comment]
> I'm still seeing the same annotations in the latest run on that JUnit-to-annotation conversion.

I think that that is because the *mikepenz/action-junit-report* action is being used in a PR without being in the target branch. See the annotations resulting from the *Build and run tests / Execute integration tests (11)* workflow run on apache/unomi#512, since they already use *mikepenz/action-junit-report*.

They don't seem to be [using it](https://github.com/apache/unomi/blob/c916eaf516/.github/workflows/unomi-ci-build-tests.yml#L57-L61) in any special way, either.

**Comment by ocket8888** [comment]
Well if we can't get annotations on PRs, why have the step for converting JUnit to annotations?

**Comment by zrhoffman** [comment]
But we can get annotations on PRs. See the annotations generated from the PR I linked above: https://github.com/apache/unomi/actions/runs/3129456290

**Comment by ocket8888** [comment]
So you're saying that once this is merged it'll add annotations?

Lemme check that out. Or, well, at least check if the warning and error go away.

**Comment by zrhoffman** [comment]
Switched back to the old annotations we were using that echoes annotations instead of using the API (I wish more of them did that) in 7483eaa032

**Review by ocket8888 — APPROVED** [review]

**Pull request merged**
