### PR TITLE
[Docs] upgrade setuptools prior to installing sphinx

### LINKED ISSUE #2891: docs build failure
The docs build is failing in master due to a dependency change in the python tools being used:
```
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=36.2.7'))
```

The full build log is here: https://builds.apache.org/view/S-Z/view/TrafficControl/job/trafficcontrol-master-build/1090/consoleText

### PR DESCRIPTION
**Pull request by dangogh**
#### What does this PR do?

fixes docs build failure caused by upstream dependency change.

Fixes #2891 

#### Which TC components are affected by this PR?

- [x] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?

`./pkg -v docs`

#### Check all that apply

- [ ] This PR includes tests
- [x] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by dangogh** [comment]
@jhg03a -- please review

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2547/
Test FAILed.

**Comment by dangogh** [comment]
fair enough,  but after adding this line to requirements.txt,  it still fails:  `setuptools>=36.2.7`

```
Collecting setuptools>=36.2.7 (from -r /docs.requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl (569kB)
Collecting Sphinx>=1.4.3 (from -r /docs.requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/35/e0/e9e83b244eaa382ba21896dda6172617e47aff0be225eb72782cca105d3c/Sphinx-1.8.1-py2.py3-none-any.whl (3.1MB)
Collecting sphinx_rtd_theme>=0.4.0 (from -r /docs.requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/87/30/7460f7b77b6e8a080dd3688f750fe5d5666c49358f8941449c5b128fa97d/sphinx_rtd_theme-0.4.1-py2.py3-none-any.whl (5.4MB)
Collecting sphinx_autodoc_typehints>=1.3.0 (from -r /docs.requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/96/f2/194721797bb0d96df240030dd513b41d47fe0640bbbd6a6978f0b488f847/sphinx-autodoc-typehints-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-H9E2gy/sphinx-autodoc-typehints/setup.py", line 7, in <module>
        'setuptools >= 36.2.7'
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=36.2.7'))
```

**Comment by ocket8888** [comment]
I believe the `pip` module itself depends on setuptools, so if that's the case upgrading would necessarily require two separate runs - `pip` can't still be running the outdated instance when it hits that requirement. 
I'd suggest changing the edit from `pip install --upgrade setuptools` to a more explicit `pip instatll --upgrade pip` and see if that helps anything

**Comment by ocket8888** [comment]
Can confirm that pinning in the requirements file doesn't work, but a prior upgrade does. Interestingly, the version of `pip` that it's using is fine with the new setuptools - even though it's over 40 major versions of difference (meaning `pip install -U pip` is unnecessary, Dan's change should fix it).

**Comment by ocket8888** [comment]
Another option, if it makes you feel better, is to just 'pin' (not exactly the right word; `>=` doesn't 'pin' - it'll install the latest available version and fail if that's not at least the specified version) the requirement right there in the dockerfile by using `pip install -U setuptools>=36.2.7` or `pip install -U setuptools==36.2.7` for a more strict version requirement. But that still has to be done in a prior step the same way `yum install -y epel-release` must be done in a separate step from `yum install -y python34`

**Pull request merged**
