### PR TITLE
Add TM monitoring.json validity check for safety

### LINKED ISSUE #3525: Improve resiliancy against malformed json in monitoring.json
When upgrading to a release that contains issue #3104, there is a brief window in which TO will return an invalid json object of `{}` until the first snapshot.  If TM polls during this window it will flag all caches as offline.  This potentially can manifest all the way up to TR which will cause 503 errors on client steering delivery services that nolonger have valid targets similarly to #3521.

TM should perform additional sanity checks on monitoring.json to ensure root json entries are present and subarrays are not empty.

### PR DESCRIPTION
**Pull request by rob05c**
## What does this PR (Pull Request) do?

- [x] This PR fixes #3525 OR is not related to any Issue

Includes unit tests. No documentation, no changelog, no interface change.

## Which Traffic Control components are affected by this PR?

- Traffic Monitor

## What is the best way to verify this PR?

`go test`. Run the Monitor, make sure it works as expected.  Set the Traffic Ops database `snapshot` table `monitoring` column to `{}`, verify an error is logged, and TM continues to function. Restart Monitor, verify an error is logged and Monitor does not startup (you may need to delete the backup tmconfig.backup, to prevent it from starting with the backup when the TO monitoring.json is bad).

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3589/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3590/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3592/
Test FAILed.

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3605/
Test PASSed.

**Pull request merged**
