### PR TITLE
grovetccfg: use kernel host name if -host argument is not used on the command line.

### PR DESCRIPTION
**Pull request by jrushford**
If when using grovetccfg and the host is not specidied with -host on the command line, get and set the host from kernel.

#### What does this PR do?

helps with grove configuration by simplifying automated cron setup of grovetccfg.

Fixes #(issue_number)

#### Which TC components are affected by this PR?

- [ ] Documentation
- [X] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2877/
Test FAILed.

**Comment by jrushford** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2893/
Test FAILed.

**Comment by jrushford** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2907/
Test FAILed.

**Comment by jrushford** [comment]
retest this please

**Comment by jrushford** [comment]
test this please

**Comment by jrushford** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2908/
Test PASSed.

**Comment by dsouza93** [comment]
Looks good.
I ran this on a cdn-in-a-box edge instance, once with the host in the command line and once without. The program successfully uses the os hostname when host flag is not provided and attempts to use the provided hostname when the host flag is provided.

**Pull request merged**
