### PR TITLE
Fix json response for invalid invalidation job. Moved CHANGELOG entry

### PR DESCRIPTION
**Pull request by TaylorCFrey**
Addresses an issue discovered in testing the TO v4.0 `/jobs` endpoint. The validation of the incoming job was wrapping the alert and error response inside another alert and error response.

Incorrect response:
```json
{
  "alerts": [
    {
      "text": "{\"alerts\":[{\"text\":\"deliveryService: cannot be blank.\",\"level\":\"error\"}]}\n",
      "level": "error"
    }
  ]
}
```

Fixed response:
```json
{
  "alerts": [
    {
      "text": "deliveryService: cannot be blank.",
      "level": "error"
    }
  ]
}
```

Also moved a CHANGELOG entry for the _REFETCH_ feature into the correct location for the CHANGELOG.

<hr>

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Run Traffic Ops and attempt to *POST* a new invalidation request to the `/jobs` endpoint. The following json will trigger a validation error, alert response:
```json
{
	"startTime": "2021-11-05T16:24:00.370Z",
	"regex": "/path/to/some/content\\.jpg",
	"ttlHours": 24,
	"invalidationType": "REFRESH"
}
```

## PR submission checklist
- [ ] This PR has tests - Does not have a functional aspect, only asthetic.
- [ ] This PR has documentation - No documented logic is changed, added, or deleted.
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Comment by zrhoffman** [comment]
> Also moved a CHANGELOG entry for the _REFETCH_ feature into the correct location for the CHANGELOG.

If you put that in a separate PR, I'll merge it right away

**Review by srijeet0406 — APPROVED** [review]
LGTM! Manual tests pass. API and unit tests pass.

**Comment by dneuman64** [comment]
retest this please

**Comment by zrhoffman** [comment]
> retest this please

Failing due to the ATS RPM version-calculating issue fixed by #6329

**Comment by zrhoffman** [comment]
In order for CI to pass, #6328 needs to be rebased onto the [`apache:master`](https://github.com/apache/trafficcontrol/commits/master) branch now that the CI fix in apache/trafficcontrol#6329 is merged:
```shell
git remote add apache git@github.com:apache/trafficcontrol.git
git fetch apache
git rebase apache
git push your-fork your-branch --force
```

**Pull request merged**
