### PR TITLE
Fix internal server error in user current put

### LINKED ISSUE #4241: Internal Server Error when updating user's password using /user/current endpoint
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `PUT` request to `/user/current` with the following request body:
```
{
    "user": {
        "localPasswd": "newPassword"
    }
}
```
The response returned is:
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should either allow to change password or block the request.
## Anything else:

Error log: 
`Updating user: resetting password: pq: syntax error at or near "WHERE"`

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4241 

Fixes an error in a SQL query that was causing internal server errors whenever a user's password was updated using a PUT request to `/user/current`. Also updates docs which had an invalid value for `fullName` in the request example.

## Which Traffic Control components are affected by this PR?
- Documentation
- Traffic Ops

## What is the best way to verify this PR?
Besides building and reading the documentation, make a PUT request to `/user/current` with a `localPasswd` key and verify that your password actually changes, and no internal server error occurs. I didn't write a test because I don't fully comprehend the implications of changing a shared user's password partway through testing.

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 4.0 (RC2 - I *think*)

## The following criteria are ALL met by this PR
- [x] I have explained why tests are unnecessary
- [x] This PR includes documentation
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by rawlinp** [comment]
@ocket8888 I'm wondering why this is considered minor -- does this mean without being fixed, nobody would be able to update their password?

**Comment by ocket8888** [comment]
No, there are other methods to update a password. `/user/current/update` is basically the same endpoint, and anyone with a registered email can reset their password. Plus, if the `/user/current` PUT handler was heavily used enough it could just be perlBypassed as of right now.

I can change the severity label, though, I don't have a preference as to what it is.

**Comment by rawlinp** [comment]
Oh, thanks for the clarification -- I forgot we had about 18 endpoints to do the same thing. Minor seems fair then.

**Comment by mitchell852** [comment]
@ocket8888 - this looks like a good backport candidate for the 4.0.x branch

**Comment by rawlinp** [comment]
This bug does not actually affect the 4.0.x branch, since it appears this rewrite was merged _after_ the branch was cut.

**Pull request merged**
