### PR TITLE
Debug TM, TO, TO Perl, or TR CDN-in-a-Box containers

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

This PR lets you use CDN-in-a-Box to debug Traffic Monitor, Traffic Ops, Traffic Ops Perl, and Traffic Router and adds configuration options so that this behavior is only enabled when desired.
- [x] This PR is not related to any Issue

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Documentation
- Traffic Monitor
- Traffic Ops

## What is the best way to verify this PR?

* Build documentation to make sure there are no warnings
* Make sure documentation is accurate and easy to follow
* Ensure RPMs and CDN-in-a-Box build
* Check whether debugging works in CDN-in-a-Box for:
    - Traffic Monitor
    - Traffic Ops
    - Traffic Ops Perl
    - Traffic Router

* Check that no debugging information or behavior is included when debug flags and variables are not used.
    - When `pkg` is used instead of `pkg -d`, or CiaB's `make` is used instead of `make debug`, the `traffic_monitor` and `traffic_ops_golang` binaries should be roughly 2 MB smaller.
    - In CiaB's `variables.env`, if `DEBUGGING_TM`, `DEBUGGING_TO`, `DEBUGGING_TO_PERL`, or `DEBUGGING_TR` are not set to true, timeouts should be short (60 seconds or less) and the services should not try to use Delve, Devel::Camelcadedb, or JPDA to run.

* Jenkins should be able to build everything. That is essentially our test for the build scripts and docker environment.

## If this is a bug fix, what versions of Traffic Control are affected?

Not a bug fix.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md.
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

Debugging can be useful for a developer's own analysis, but it in no way replaces tests.

Comments, feedback, suggestions, and criticism are welcome.

### CODE REVIEW

**Comment by zrhoffman** [comment]
Does anyone have thoughts about this PR? Does anything need to change?

**Comment by ocket8888** [comment]
I can't get the debug configuration to start up. None of the `-nondebug` containers can be started, they all say:
```
ERROR: for cdn-in-a-box_trafficops-perl-nondebug_1  Cannot start service trafficops-perl-nondebug: network a74043e2314f828751aeb9b90594c863e210597b1be710b029c4260c673fa444 not found
```

**Comment by zrhoffman** [comment]
The branch didn't have the Postgres repo RPM URL fix (a5edc1ca82). Rebased onto master. It should work now, the rebase is the version I have been using.

**Comment by ocket8888** [comment]
Well, now the containers start up, but the enroller is waiting on TO, TO is waiting on Perl, and Perl is waiting on the enroller:
```
enroller_1         | + nc -z trafficops.infra.ciab.test 443
enroller_1         | + echo 'Waiting for https://trafficops.infra.ciab.test:443'
enroller_1         | + sleep 5
enroller_1         | Waiting for https://trafficops.infra.ciab.test:443
trafficops-perl_1  | + [[ -f /shared/enroller/enroller-started ]]
trafficops-perl_1  | + echo 'waiting for enroller'
trafficops-perl_1  | + sleep 3
trafficops-perl_1  | waiting for enroller
trafficops_1       | + nc trafficops-perl.infra.ciab.test 443
trafficops_1       | waiting for trafficops-perl.infra.ciab.test:443
trafficops_1       | + echo 'waiting for trafficops-perl.infra.ciab.test:443'
trafficops_1       | + sleep 3
```
resulting in total deadlock. Which probably means one of the TO servers (or both) failed to start and/or listen on the correct port. I didn't find anything glaring in the logs, though.

**Comment by zrhoffman** [comment]
If you have no debug configuration enabled, then that's just CiaB's normal "works most of the time" behavior, restarting should fix

**Comment by zrhoffman** [comment]
Traffic Ops Perl now needs `TO_PERL_SCHEME` set, but the default `variables.env` should provide that.

**Comment by zrhoffman** [comment]
It can be helpful to remove all images, just to make sure there is no issues related to caching. I do that with some frequency when switching branches, using [cb_rebuild_everything](https://github.com/zrhoffman/rc-files/blob/98ec8b5243/bash/bashrc.atc#L719-L732).

**Comment by ocket8888** [comment]
oh, I did a full `docker system prune -af` before that command
and that is me running with debugging turned on for every container

**Comment by zrhoffman** [comment]
Ah I see. Yes that will work, but since Perl debugging is enabled, you have to connect to the Perl process with your IDE before it will continue (otherwise you would not be able to set breakpoints). I explained why [in the docs](https://github.com/zrhoffman/trafficcontrol/blob/debug_cdn-in-a-box/docs/source/development/debugging.rst#traffic-ops-perl):

> Camelcadedb has the limitation that new breakpoints are only recognized if you set them while the debugger is at a breakpoint or before the IDE connects.

**Comment by ocket8888** [comment]
Well now I can get things to build and run, but I can't set breakpoints in TO. I tried to set one at [one of the steps in the `/ping` endpoint handler](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/ping/ping.go#L31) as well as your suggested line in Profile.Read. Neither worked. Here's my config:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "program": "/home/ocket8888/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/",
            "remotePath": "/opt/traffic_ops/app/bin/traffic_ops_golang",
            "port": 2345,
            "host": "127.0.0.1",
            "showLog": true
        }
    ]
}

**Comment by zrhoffman** [comment]
The remote path refers to where the binary was built, not where it currently sits. In your config, `request` needs to be `"launch"` and `remotePath` needs to be `"/tmp/go/src/github.com/apache/trafficcontrol/traffic_monitor"`.

I added an example config for vscode in 71cc81c29e.

**Comment by ocket8888** [comment]
That's odd. It tells me that "launch" is deprecated with "remote" mode.

**Comment by zrhoffman** [comment]
VS Code Go's [remote debugging documentation](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging) says to use `launch`, but it seems to be working with `attach` if the `program` key is changed to `cwd` (updated docs in 9c50eed84a).

**Comment by ocket8888** [comment]
Alright, well I nuked everything and rebuilt it again, and it still doesn't break on breakpoints. I used this debugger config:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "cwd": "/home/ocket8888/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/",
            "remotePath": "/tmp/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang",
            "port": 2345,
            "host": "127.0.0.1",
            "showLog": true
        }
    ]
}
```

**Comment by zrhoffman** [comment]
Your GOPATH is `/home/ocket8888`?

Assuming that your workspace root is your git working tree, `/home/ocket8888/src/github.com/apache/trafficcontrol`, it might better to use a `cwd` relative to the workspace root: `"${workspaceRoot}/traffic_ops/traffic_ops_golang"`

**Comment by zrhoffman** [comment]
After changing `cwd` to be relative to the workspace root, your `attach` configuration works for me.

**Comment by ocket8888** [comment]
> _"Your GOPATH is `/home/ocket8888`?"_

yes

> _"Assuming that your workspace root is your git working tree, `/home/ocket8888/src/github.com/apache/trafficcontrol`..."_

Idk what a "workspace root" is, but I assume it's the folder I have open in VSCode? Because then yes.

This configuration also doesn't pause on breakpoints:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "cwd": "/home/ocket8888/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/",
            "remotePath": "${workspaceRoot}/traffic_ops/traffic_ops_golang",
            "port": 2345,
            "host": "127.0.0.1",
            "showLog": true
        }
    ]
}
```

**Comment by zrhoffman** [comment]
The Traffic Ops RPM should be built with either `make debug` or `make debug traffic_ops/traffic_ops.rpm`. Otherwise, the debugger could fail to break at some lines and will be missing variable info.

**Comment by zrhoffman** [comment]
Your `remotePath` became `"/opt/traffic_ops/app/bin/traffic_ops_golang"` again. It needs to be `"/tmp/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang"`.

**Comment by ocket8888** [comment]
right :facepalm:

**Pull request merged**
