### PR TITLE
Fix the names of the migrations for roles and perms

### PR DESCRIPTION
**Pull request by srijeet0406**
This PR is not related to any issue. It just fixes the names of the migrations added in https://github.com/apache/trafficcontrol/pull/6307
<hr>

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Make sure the migrations run successfully. Also make sure that the GHA todb_tests passes.

## If this is a bugfix, which Traffic Control versions contained the bug?

- master

## PR submission checklist
- [ ] This PR has tests 
- [ ] This PR has documentation 
- [ ] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by rawlinp — CHANGES_REQUESTED** [review]
The underlying issue is more than just these 2 migrations. Since we backported `le_dns_challenge_xml_id` to 6.0, every migration between that one and `fix_indices` needs to be renamed to be later than `le_dns_challenge_xml_id`.

**Comment by rawlinp** [comment]
Oh, I see this is just for removing the extra digits. The issue I just referred to is different, but still needs fixed if you'd like to just take care of that in this PR.

**Comment by srijeet0406** [comment]
> Oh, I see this is just for removing the extra digits. The issue I just referred to is different, but still needs fixed if you'd like to just take care of that in this PR.

Yeah I'll rename all those migrations in this PR.

**Comment by zrhoffman** [comment]
#6321 should be rebased now that @ocket8888's PR to fix for the TO DB GHA in #6322 is merged.

**Review by rawlinp — APPROVED** [review]

**Pull request merged**
